### ISSUE TITLE
add MICN、 Crossformer

### ISSUE THREAD

**Issue by 943fansi** [thuml/Time-Series-Library#1]
MICN: Multi-scale Local and Global Context Modeling for Long-term Series Forecasting
https://github.com/wanghq21/MICN

**Comment by wuhaixu2016** [comment]
Cool, thanks for recommending us this interesting work. We will add MICN soon.

**Comment by 943fansi** [comment]
@wuhaixu2016 Crossformer: Transformer Utilizing Cross-Dimension Dependency for Multivariate Time Series Forecasting https://github.com/Thinklab-SJTU/Crossformer

**Comment by 1915982017** [comment]
麻烦有人能解决一下这个问题吗？
ImportError: cannot import name 'load_data' from 'sktime.utils' (/root/miniconda3/lib/python3.8/site-packages/sktime/utils/__init__.py)
谢谢

**Comment by wuhaixu2016** [comment]
Hi, we have added these two baselines in the latest commit.
