### ISSUE TITLE
数据集长度问题

### ISSUE THREAD

**Issue by Et6an** [thuml/Time-Series-Library#101]
您好，我将ETTh1数据集替换成自己的数据之后运行报错：
![image](https://github.com/thuml/Time-Series-Library/assets/112670349/54f50877-b687-46c3-9737-15340a08520b)
请问数据集长度较短的情况下如何修改解决呢

**Comment by lsl0000** [comment]
更改border1和border2

**Comment by Et6an** [comment]
> 更改border1和border2

感谢

**Comment by feifei05** [comment]
> 更改border1和border2

请问border1和border2是什么，能不能说具体一些什么参数还是哪里哈
