### ISSUE TITLE
About results

### ISSUE THREAD

**Issue by Et6an** [thuml/Time-Series-Library#103]
您好，请问如何得到反归一化预测的数据，data类型为custom的情况下

**Comment by wuhaixu2016** [comment]
您好，您可以对输出结果调用inverse_transform（https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#LL102C9-L102C26）

**Comment by Et6an** [comment]
感谢您的回复。还有一个小问题想问一下，TimesNet如何做数据集以外的未来预测，运行源码的时候好像没有找到类似autoformer中的do_predict命令

**Comment by wuhaixu2016** [comment]
您好，其实只要把autoformer里面的那个函数复制过来就可以了，这个算法库主要是想实现不同模型间的评测，所以没有往serving方向进行优化设计

**Comment by Et6an** [comment]
好的，非常感谢！

**Comment by Et6an** [comment]
您好，我在运行预测的过程中报错：
![image](https://github.com/thuml/Time-Series-Library/assets/112670349/690f982d-6089-4805-b0f0-7b2f8d366e48)
请问怎样更好的解决呢，data_factory需要进一步修改吗

**Comment by Williams-wlc** [comment]
您好 冒昧的问一下 请问您是在代码的那个位置调用inverse_transform()的呢 具体是如何调用的呀

**Comment by Williams-wlc** [comment]
您好 冒昧的问一下 请问您是在代码的那个位置调用inverse_transform()的呢 具体是如何调用的呀

**Comment by Et6an** [comment]
> 您好 冒昧的问一下 请问您是在代码的那个位置调用inverse_transform()的呢 具体是如何调用的呀

我是在处理result.NPY文件的时候进行反归一化

**Comment by warmful-sun** [comment]
> > 您好 冒昧的问一下 请问您是在代码的那个位置调用inverse_transform()的呢 具体是如何调用的呀
> 
> 我是在处理result.NPY文件的时候进行反归一化

你好，这个地方搜了好多编程都没有找到，方便分享一下代码吗？万分感谢！！
