### ISSUE TITLE
anomaly detection threshold

### ISSUE THREAD

**Issue by yexianyao** [thuml/Time-Series-Library#105]
您好，我想问一下您在异常检测的代码中是使用什么方法确定阈值的？有些论文中（如TranAD）使用的是peak over threshold，似乎和您使用的方法不一样

**Comment by wuhaixu2016** [comment]
您好，我们遵循的时候Anomaly Transformer的阈值选择方法，具体可以见Appendix H (https://arxiv.org/pdf/2110.02642.pdf)
