### ISSUE TITLE
Dataset_Custom 类只支持一次一种ID的训练么？

### ISSUE THREAD

**Issue by wentixiaogege** [thuml/Time-Series-Library#108]
详细描述：
   目前提供的数据，在Dataset_Custom类下都是：
      日期 + 特征 + Target 的格式， 可以类比成一个工厂，一个商品等维度

   但是现实往往是，
     一个工厂： 日期 + 特征 + Target
     两个工厂：日期 + 特征 + Target
     等，很多工厂，或者很多商品的维度去做预测；

目前感觉没有这种Dataset_Custom 支持？ 求指导呀~

**Comment by wentixiaogege** [comment]
好像跟这个很像呀
https://github.com/thuml/Time-Series-Library/issues/47

作者有没有考虑搞一个demo呀，深度学习只是训练一条时序感觉就不太合理呀，主要还是得丰富当前的场景。

**Comment by dongxinyu1030** [comment]
你的需求我的场景比较类似，数据由几万条不同的时序组成。部署时，每次都要面对新的时序。 你可以把所有工厂的数据进行切片然后合并到一个dataset里进行训练

**Comment by wentixiaogege** [comment]
> 

求个demo，或者数据加工的脚本呀

**Comment by dongxinyu1030** [comment]
import numpy as np
import os
import pandas as pd
import copy
def get_file_path(path):
    file_path = []
    for root, dirs, files in os.walk(path):
        for file in files:
            if file.endswith('.csv'):
                file_path.append(os.path.join(root,file))
    return file_path    

def process(df, seq_len,label_len,pred_len,interval):
    results = []
    for i in range((len(df)-seq_len-pred_len)//interval-1):
        slice = df[i*interval:i*interval+seq_len+pred_len]
        results.append(slice)

    return np.array(results)
            

if __name__ == '__main__':
    train_files = get_file_path()
    seq_len = 150
    label_len = 75
    pred_len = 75
    interval = 1 
    train_data = np.array([])
    for f in train_files[:]:
        data_frame = pd.read_csv(f, index_col=False)
        # data_frame = data_frame[['hanger_u','hanger_t','plc_rope_pose']].values
        data_frame = data_frame[['t']].values
        if ((len(data_frame)-seq_len-pred_len)//interval-1)<=0:
            continue
        results = process(data_frame,seq_len,label_len,pred_len,interval)
        if train_data.shape[0] == 0:
            train_data = results
        else:
            # print(data_frame.shape)
            train_data = np.vstack((train_data,results))
    np.save('/home/dongxinyu/project/scripts/labeledcsv/tv/train_s150_l75_p75_dimt.npy',train_data)

**Comment by wentixiaogege** [comment]
`import numpy as np
import os
import pandas as pd
import copy
def get_file_path(path):
    file_path = []
    for root, dirs, files in os.walk(path):
        for file in files:
            if file.endswith('.csv'):
                file_path.append(os.path.join(root,file))
    return file_path

def process(df, seq_len,label_len,pred_len,interval):
    results = []
    for i in range((len(df)-seq_len-pred_len)//interval-1):
        slice = df[i:i+seq_len+pred_len]
    results.append(slice)

    return np.array(results)
if __name__ == 'main':
    train_files = get_file_path()
    seq_len = 150
    label_len = 75
    pred_len = 75
    interval = 1
    train_data = np.array([])
    for f in train_files[:]:
        data_frame = pd.read_csv(f, index_col=False)
        # data_frame = data_frame[['hanger_u','hanger_t','plc_rope_pose']].values
        data_frame = data_frame[['t']].values
        if ((len(data_frame)-seq_len-pred_len)//interval-1)<=0:
            continue
        results = process(data_frame,seq_len,label_len,pred_len,interval)
        if train_data.shape[0] == 0:
            train_data = results
        else:
            # print(data_frame.shape)
            train_data = np.vstack((train_data,results))
    np.save('/home/dongxinyu/project/scripts/labeledcsv/tv/train_s150_l75_p75_dimt.npy',train_data)`

**Comment by wentixiaogege** [comment]
```
import numpy as np
import os
import pandas as pd
import copy
def get_file_path(path):
    file_path = []
    for root, dirs, files in os.walk(path):
        for file in files:
            if file.endswith('.csv'):
                file_path.append(os.path.join(root,file))
    return file_path

def process(df, seq_len,label_len,pred_len,interval):
    results = []
    for i in range((len(df)-seq_len-pred_len)//interval-1):
        slice = df[i:i+seq_len+pred_len]
    results.append(slice)

    return np.array(results)
if __name__ == 'main':
    train_files = get_file_path()
    seq_len = 150
    label_len = 75
    pred_len = 75
    interval = 1
    train_data = np.array([])
    for f in train_files[:]:
        data_frame = pd.read_csv(f, index_col=False)
        # data_frame = data_frame[['hanger_u','hanger_t','plc_rope_pose']].values
        data_frame = data_frame[['t']].values
        if ((len(data_frame)-seq_len-pred_len)//interval-1)<=0:
            continue
        results = process(data_frame,seq_len,label_len,pred_len,interval)
        if train_data.shape[0] == 0:
            train_data = results
        else:
            # print(data_frame.shape)
            train_data = np.vstack((train_data,results))
    np.save('/home/dongxinyu/project/scripts/labeledcsv/tv/train_s150_l75_p75_dimt.npy',train_data)
```

**Comment by wentixiaogege** [comment]
朋友还可以看看这个，阿里这个好像比timesnet效果要好了，可惜还没开源~ 

One Fits All:Power General Time Series Analysis by Pretrained LM

https://arxiv.org/abs/2302.11939

**Comment by dongxinyu1030** [comment]
不在公司，明天发一下dataloader。btw我试了这个库里的几个算法，在我的数据上dlinear又快又好。timesnet太慢了

**Comment by wentixiaogege** [comment]
> def process(df, seq_len,label_len,pred_len,interval):
>     results = []
>     for i in range((len(df)-seq_len-pred_len)//interval-1):
>         slice = df[i:i+seq_len+pred_len]

感觉这个没有跟dataset_custom 结合，还是得搞一个比较general的多时序的类，才好搞呀~

**Comment by wentixiaogege** [comment]
> 不在公司，明天发一下dataloader。btw我试了这个库里的几个算法，在我的数据上dlinear又快又好。timesnet太慢了

可以呀可以呀，太感谢了~

**Comment by wentixiaogege** [comment]
求个可以跑的demo，好多算法死在了跑不起来上呀

**Comment by dongxinyu1030** [comment]
> > def process(df, seq_len,label_len,pred_len,interval):
> > results = []
> > for i in range((len(df)-seq_len-pred_len)//interval-1):
> > slice = df[i:i+seq_len+pred_len]
> 
> 感觉这个没有跟dataset_custom 结合，还是得搞一个比较general的多时序的类，才好搞呀~

那倒也是，我的数据都是提前先根据我想要的长度切好片再加载进dataloader的。dataloader其实就是单纯的加载

**Comment by wentixiaogege** [comment]
先求一套您的，我跑跑看哈哈哈~ 多谢~

**Comment by dongxinyu1030** [comment]
邮箱给我发你一份

**Comment by wentixiaogege** [comment]
> 邮箱给我发你一份
多谢多谢~ ，【VX： wentixiaogege 】
wentixiaogege@163.com

**Comment by liuqi0314** [comment]
> 邮箱给我发你一份

老师您好，能否也分享给学生一份
邮箱：upwardliuqi@163.com

**Comment by zhh0998** [comment]
> 邮箱给我发你一份

您好，请问方便也分享学生一份吗？1840794862@qq.com

**Comment by lafans** [comment]
> 邮箱给我发你一份

您好，请问方便给我也分享一份吗 2623155968@qq.com

**Comment by zhangyuyayaya** [comment]
老师您好，能否也分享给学生一份
邮箱：18989490125@163.com

**Comment by songmingjun3** [comment]
> 邮箱给我发你一份

您好，能麻烦给我也分享一份吗？
邮箱：songmingjunjob@163.com
另外想请教下，看您分享的部分代码里面并没使用label_len，这个会造成跟repo里面对应的dataset格式不一致吗？
