### ISSUE TITLE
Discrepancy in anomaly_ratio for SWaT Dataset

### ISSUE THREAD

**Issue by blacksnail789521** [thuml/Time-Series-Library#109]
Hello,

I've been closely examining the settings used in your scripts for anomaly detection and noticed a couple of potential discrepancies I wanted to bring to your attention.

In the original Anomaly Transformer's paper, it's stated:

> For the main results, we set **r = 0.1% for SWaT**, 0.5% for SMD and 1% for other datasets

Upon reviewing your scripts, I found that the `anomaly_ratio` for most datasets matches the settings outlined in the Anomaly Transformer's paper, except for the SWaT dataset. In your scripts, the `anomaly_ratio` for the SWaT dataset is set to [1%](https://github.com/thuml/Time-Series-Library/blob/5e2e8874a5492a7997a5e0e79d7e5ba997888737/scripts/anomaly_detection/SWAT/TimesNet.sh#L19), rather than the 0.1% indicated in the original documentation. I'm curious to understand the rationale behind this alteration.

Additionally, I noticed that in `SWATSegLoader`, swat_train2.csv is loaded as the training data and swat2.csv as the test data. However, in swat2.csv, the normal to attack ratio isn't 0.1% or 1%, but rather 12% (matched with TranAD paper). Could you please help clarify the reasoning for this difference as well?

Thank you for your time, and I appreciate your assistance in understanding these details.

**Comment by wuhaixu2016** [comment]
Hi,

(1) In this paper, we find that setting the anomaly ratio as 1% for SWaT can boost the performance of all the models, including Anomaly Transformer. Thus, we set the hyperparameter as 1%.

(2) Why the set ratio is smaller than the exact anomaly ratio?
This comes from the adjustment strategy for evaluation. Here is a clarification: https://github.com/thuml/Anomaly-Transformer/issues/14
