### ISSUE TITLE
positionEmbedding的实际意义？

### ISSUE THREAD

**Issue by oubahe** [thuml/Time-Series-Library#11]
非常棒的idea创新！请问楼主，源码中下面positionEmbedding每步操作的实际意义是什么呢？
pe = torch.zeros(max_len, d_model).float()
pe.require_grad = False  # 不更新参数
position = torch.arange(0, max_len).float().unsqueeze(1)
div_term = (torch.arange(0, d_model, 2).float() * -(math.log(10000.0) / d_model)).exp()
pe[:, 0::2] = torch.sin(position * div_term)
pe[:, 1::2] = torch.cos(position * div_term)

**Comment by wuhaixu2016** [comment]
您好，这个是标准Transformer中的操作，其思想是使用sin cos函数来处理时间序列的index，您可以通过Transfromer的文章来得到更多的描述

**Comment by oubahe** [comment]
好的，感谢楼主解答。另外在模型调试复现中发现：
period = x.shape[1] // top_list生成的period list可能存在重复冗余，例如period=[2, 2, 3, 4, 4]，
在此基础上去重筛选了相同period对应的最大frequency与强度A，能降低模型复杂度的同时保持模型预测性能。

**Comment by wuhaixu2016** [comment]
Interesting findings, we will update the model after evaluating the performance of this design.
