### ISSUE TITLE
Can't pickle local object 'data_provider.<locals>.<lambda>'

### ISSUE THREAD

**Issue by Karo-kun** [thuml/Time-Series-Library#110]
作者你好！我在运行分类任务时，出现这个问题，数据是从作者提供的数据下载的，请问怎样才能解决这个问题？麻烦了
<img width="1245" alt="image" src="https://github.com/thuml/Time-Series-Library/assets/59633320/586d6123-8d30-415d-908d-a8acf579a59a">

**Comment by zx377262372** [comment]
俺也一样，谢谢作者

**Comment by zx377262372** [comment]
![image](https://github.com/thuml/Time-Series-Library/assets/74412671/f456e30f-9881-4bba-9be3-74ba0cf5c95b)

**Comment by wuhaixu2016** [comment]
您好，这个问题我没有遇到过，请检查package版本
