### ISSUE TITLE
请问能不能发我一份PPT

### ISSUE THREAD

**Issue by VictimHan** [thuml/Time-Series-Library#112]
您好，我在B站看了您在ICLR预讲会关于这个项目的分享，请问可否把您分享的ppt发我一份，如果可以，不胜感激！ 我的qq邮箱是827714185@qq.com

**Comment by wuhaixu2016** [comment]
您好，请见：https://wuhaixu2016.github.io/pdf/ICLR2023_TimesNet.pdf

**Comment by VictimHan** [comment]
我已收到，感谢您的分享



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月3日(周六) 晚上11:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [thuml/Time-Series-Library] 请问能不能发我一份PPT (Issue #112)




 
您好，请见：https://wuhaixu2016.github.io/pdf/ICLR2023_TimesNet.pdf
