### ISSUE TITLE
About Temporal 2D-Variations

### ISSUE THREAD

**Issue by LanZhenFeng** [thuml/Time-Series-Library#113]
Hello, I've been reading the paper "TimesNet: Temporal 2D-Variation Modeling for General Time Series Analysis" and found it quite interesting. I'm curious about how the temporal 2D-variation is visualized in the paper. Specifically, I'd like to know if the visualization is based on the original time series data, or if it's derived from one of the TimesBlock layers' 2D Tensors.
Could you please provide some insights on this matter? If you could also share some sample code or guidelines on how to generate these visualizations, that would be extremely helpful.
Looking forward to your response.

**Comment by remicazorla** [comment]
Based on my understanding, the visualization of the temporal 2D-variation in the "TimesNet: Temporal 2D-Variation Modeling for General Time Series Analysis" paper is generated by creating two-dimensional tensors. These tensors are obtained by dividing the original time series into segments of length "x," where "x" represents the period length of the considered frequency.

To determine the cutoff length, the authors utilize the FFT algorithm to identify the top frequency, denoted as "k." The cutoff length is then calculated by dividing the total length of the time series by "k."

Each segment of the time series is represented as a cut part and arranged in the 2D tensor, with each segment forming a row in the tensor.

Authors please let me know if my explanation is accurate or if any corrections are needed. Thank you, and I look forward to your response. Goodbye!

**Comment by wuhaixu2016** [comment]
Thanks for your great question @LanZhenFeng and kind answer @remicazorla 

Yes, the visualization is based on the 2D tensor as clarified by remicazorla
