### ISSUE TITLE
About Attention map Visualization

### ISSUE THREAD

**Issue by tkjUser** [thuml/Time-Series-Library#114]
Hi, How to visualize the attention map when performing a prediction task?
- When the model is called for output in `exp_long_term_forecasting.py`, attention is returned if the parameter `output_attention=True` is set. But here `outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)[0]` received only the predicted value `output` and ignored the attention returned, So where does the visualized attention map come from?
- What part of the code do I need to modify if I want to visualize the attention map?

**Comment by remicazorla** [comment]
Based on my understanding, the visualization of the temporal 2D-variation in the "TimesNet: Temporal 2D-Variation Modeling for General Time Series Analysis" paper is generated by creating two-dimensional tensors. These tensors are obtained by dividing the original time series into segments of length "x," where "x" represents the period length of the considered frequency.

To determine the cutoff length, the authors utilize the FFT algorithm to identify the top frequency, denoted as "k." The cutoff length is then calculated by dividing the total length of the time series by "k."

Each segment of the time series is represented as a cut part and arranged in the 2D tensor, with each segment forming a row in the tensor.

Authors please let me know if my explanation is accurate or if any corrections are needed. Thank you, and I look forward to your response. Goodbye!

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interest.

You can follow our previous repo (Autoformer: https://github.com/thuml/Autoformer/blob/main/layers/Transformer_EncDec.py#L50), where the attention map is maintained in the return.
