### ISSUE TITLE
如果数据不是显著周期性的

### ISSUE THREAD

**Issue by asfixcb** [thuml/Time-Series-Library#115]
如题，若数据经过fft之后得到的topk个周期是变化的，对应的振幅也是有比较明显的变化。那么对于TimesNet而言,在训练的过程中每个卷积层训练的就不再是单一周期下的特征了。是不是这类的数据用TimesNet就会有比较大的局限性？
举个例子，我有一组长度为96的数据，其中x1的振幅最高的周期是6，x2的振幅最高的周期是16，那么投喂这样的数据进行训练得到的效果是不是比较差？

**Comment by wuhaixu2016** [comment]
您好，感谢提问！很有insight
（1）如果数据在训练和测试阶段的周期性发生了明显，那么目前所有模型应该都会fail掉，因为这个问题的核心在于解决distribution shift。
（2）如果数据本身的周期性很复杂，我觉得TimesNet是可以比较好的捕捉这种情况的，比如TimesNet在M4（预测），UEA（分类），异常检测上效果都不错，而这些数据集本身就是富含多变周期的。
直觉上，您可以这么理解，因为TimesNet是将1D转换为2D，所以不同周期，其实对应着图像中不同大小的物体，在之前已经有很多工作证明了，卷积网络是可以很好的泛化在不同大小物体上的。

**Comment by asfixcb** [comment]
您好，感谢您的回复！
这是一个长度为100，变量为156的时间序列经过fft后得到的top 30的周期，可以看到weight中绝大多数都是在5-7左右
![image](https://github.com/thuml/Time-Series-Library/assets/132628239/197eaa70-2072-4ed7-a0b6-e9eb06b74adc)
这是另一个同一个时间序列对应的周期
![image](https://github.com/thuml/Time-Series-Library/assets/132628239/3701c9d5-d880-4aad-b678-f528a103254a)
是不是意味着信噪比带来的问题会比序列本身周期的复杂性要来的严重？
此外，是不是由于在每个block上都需要对数据进行fft变换，才使得网络训练耗时较长？
