### ISSUE TITLE
Non-stationary Transformers 无法到达论文指标

### ISSUE THREAD

**Issue by Sunting78** [thuml/Time-Series-Library#116]
在源码repo https://github.com/thuml/Nonstationary_Transformers
和本repo中 直接运行给的脚本 无法达到论文指标 相差很大

**Comment by wuhaixu2016** [comment]
您好，感谢您的关注和使用。
（1）如果有官方代码，请尽量使用官方代码实现，我们这个算法库重点是为研究者搭建一个框架，让大家可以自由地测试自己模型在不同时序分析任务上的结果。
（2）如果可以的话，可否具体一下是哪个setting无法达到，我们会尽快更新算法库。

**Comment by WenWeiTHU** [comment]
https://github.com/thuml/Nonstationary_Transformers/issues/25
