### ISSUE TITLE
Train own data set

### ISSUE THREAD

**Issue by czwangry123** [thuml/Time-Series-Library#119]
Very good work ! How do I train my data set with this framework ? Could you give me a brief introduction ?

**Comment by wuhaixu2016** [comment]
Hi, all you need is to write a special dataloader. 

The batch is in the shape of [B T C], where T is the temporal dimension and C is the variate dimension.

**Comment by czwangry123** [comment]
But if my data volume is too small in the time dimension, whether the short-term sequence in timesnet can help me to complete this task. 
For example, I only have the information of the year, but not the month or hour.
![image](https://github.com/thuml/Time-Series-Library/assets/103369082/71b77c4e-c9bd-4067-8b0c-6088424e7c85)
