### ISSUE TITLE
关于M4数据集的含义

### ISSUE THREAD

**Issue by vaeaea** [thuml/Time-Series-Library#120]
您好，请问可不可以简单的介绍一下m4数据集中各个文件的含义？
比如其中的training.npz\ test.npz\ submission-Naive2.csv\ M4-info.csv这几项，非常感谢！！！
![image](https://github.com/thuml/Time-Series-Library/assets/95179140/22b90532-f983-4fd5-bfec-a14db7e61315)

**Comment by wuhaixu2016** [comment]
您好，感谢关注！

具体可以参考N-BEATS论文：https://github.com/ServiceNow/N-BEATS

**Comment by Sunwang-git** [comment]
您好，请问如何才能得到格式为npz的training与test文件？我通过GitHub链接访问M4数据集后，发现下载得到train和test文件夹，文件夹内全部为csv格式文件。期待您的回复，非常感谢！
