### ISSUE TITLE
Multi features to single

### ISSUE THREAD

**Issue by remicazorla** [thuml/Time-Series-Library#121]
Hello,

I've been exploring your codebase and trying to comprehend how inter-relationships between features are leveraged to predict a singular output. However, my current understanding suggests that each feature is predicted independently from one another. Could you please provide clarification if my interpretation is incorrect?

Thank you for your assistance!

**Comment by wuhaixu2016** [comment]
Hi, good question.

For most of the methods (except PatchTST and DLinear), they adopt a value embedding layer to project the multiple variates into deep features. During this process, all the variates will interact with each other.

For Crossformer, it adopts a specially designed cross-attention to communicate multiple variates.
