### ISSUE TITLE
当跑多次结果，即：--itr 5设置为5，指标波动，是正常的吗？

### ISSUE THREAD

**Issue by Sunting78** [thuml/Time-Series-Library#122]
大多数论文中的指标都是itr=1的结果，但跑多次就会发现有比较大的波动，尤其在ill这个小数据集上

为什么不用多次itr的平均作为论文的指标呢？
应该怎么比较不同算法，才是公平的呢？

**Comment by wuhaixu2016** [comment]
您好，我们在论文中提到，所有实验结果都重复了5次。
为了方便大家得到稳定的结果，所以我们才固定了随机种子，以及将itr设置为1。标准做法就是使用随机数，重复5次取平均值。
