### ISSUE TITLE
ValueError报错

### ISSUE THREAD

**Issue by JaaakeTang** [thuml/Time-Series-Library#123]
作者您好，我在尝试使用short_term_forecast_m4的script时出现ValueError的错误，请问是我配置的问题吗？

![09f0a579d2ec2e97ed27256d8d941b2](https://github.com/thuml/Time-Series-Library/assets/51324033/272d09f4-4e2a-4915-bdcb-7aa776d07518)

**Comment by wuhaixu2016** [comment]
您好，我没有遇到过这个问题，使用现有代码也没有遇到，请检查版本配置
