### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable是什么问题？

### ISSUE THREAD

**Issue by ycglsy** [thuml/Time-Series-Library#124]
![image](https://github.com/thuml/Time-Series-Library/assets/84058281/343ab445-62fe-4d0a-a7e4-317f8c0fe94a)

**Comment by TMullerSG** [comment]
你好 请问你找到你问题的原因了么 我现在遇到了一样的问题

**Comment by Pupuliu** [comment]
同学你好，我也碰到了这个bug，这个bug解决了吗？怎么解决的
