### ISSUE TITLE
如何对时间序列模型的预测结果进行快速纠正？

### ISSUE THREAD

**Issue by thw1021** [thuml/Time-Series-Library#126]
您好！非常感谢您的分享，想借此提一个学习中遇到的问题，恳请您给予一些指导意见。

假设我基于过去1个月测量得到的风速数据训练了一个时间序列模型，并且利用这个模型预测了明天半个小时的风速（从0:00到0:30）。到了明天，开始启动测风设备，可以在每分钟都测得一组真实的风速数据，这样就可以知道模型预测值和实测值之间的偏差。假设已经获得了0：00到0：10分的真实风速，如何利用这10分钟的数据去校正之前训练好的模型，减小接下来20分钟（从0:10到0:30）的预测误差？（**假设没有时间基于新的实测数据去接着训练模型**）。

**Comment by wuhaixu2016** [comment]
您好，这个问题目前这个问题，此算法库尚未涉及。具体可以查看一些偏差订正算法

**Comment by thw1021** [comment]
您好，非常感谢您的回答。能麻烦您推荐一些具体的算法吗（论文或者代码等）？我初次接触这方面的工作，对此还很不了解。
