### ISSUE TITLE
关于其中Classification模型的困惑

### ISSUE THREAD

**Issue by IdealRealistD** [thuml/Time-Series-Library#13]
当 Exp 为 classification时，输入数据应该是[batch_size, seq_length, channel]吗?
为何在Exp 为 classification时，多出一个 x_mark_enc，该如何理解呢？
如果想要用 torch.ones() 来生成一个简单数据，测试其中的 classification 应当如何生成呢？
有点小困惑，请教下作者，不胜感激。

**Comment by wuhaixu2016** [comment]
您好，分类数据的时间序列很多长度是不相等的，所以需要在预处理阶段将他们全部padding为整个数据的最长序列的长度（在末尾填0），x_mark_enc就是记录的数据预处理过程中的padding的time point。

“如果想要用 torch.ones() 来生成一个简单数据，测试其中的 classification 应当如何生成呢？”
这个是指更换数据集吗？如果更换数据集的话，需要重新写dataloader。但是如果只是想针对某个模型测一下torch.ones()会被分成哪个类别，那么可以将x_mark_enc全部设置为1，直接进行一次forward即可。
