### ISSUE TITLE
Message error : TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by Med-Rokaimi** [thuml/Time-Series-Library#131]
Thank you for this amazing work. Please, I try to run this lib from Google Colab. I use the code in run.py in a google colab notebook. 

Args in experiment:
{'dropout': 0.05, 'num_workers': 10, 'gpu': 0, 'lradj': 'type1', 'devices': '0', 'use_gpu': True, 'use_multi_gpu': False, 'freq': 'd', 'checkpoints': './checkpoints/', 'bucket_size': 4, 'n_hashes': 4, 'task_name': 'short_term_forecast', 'is_training': 1, 'root_path': '/content/drive/MyDrive/UNIVR/Notebooks/Autoformer/dataset/', 'data_path': 'oil.csv', 'seq_len': 25, 'label_len': 7, 'pred_len': 1, 'e_layers': 2, 'd_layers': 1, 'n_heads': 8, 'factor': 1, 'enc_in': 4, 'dec_in': 4, 'c_out': 1, 'd_model': 512, 'des': 'Exp', 'itr': 1, 'd_ff': 2048, 'moving_avg': 45, 'patience': 4, 'learning_rate': 0.0001, 'batch_size': 1, 'embed': 'timeF', 'activation': 'gelu', 'use_amp': False, 'loss': 'mse', 'train_epochs': 1, 'model': 'Autoformer', 'data': 'oil', 'features': 'MS', 'target': 'Price'}
Use GPU: cuda:0

>>>>>>>start training : short_term_forecast_None_Autoformer_oil_ftMS_sl25_ll7_pl1_dm512_nh8_el2_dl1_df2048_fc1_ebtimeF_dtNone_Exp_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 2038
val 259

I got this error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-6-e27d994aaf9d>](https://localhost:8080/#) in <cell line: 179>()
    201         exp = Exp(args)  # set experiments
    202         print('>>>>>>>start training : {}>>>>>>>>>>>>>>>>>>>>>>>>>>'.format(setting))
--> 203         exp.train(setting)
    204 
    205         print('>>>>>>>testing : {}<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'.format(setting))

[/content/drive/MyDrive/UNIVR/Notebooks/TS-Lib/exp/exp_short_term_forecasting.py](https://localhost:8080/#) in train(self, setting)
     93 
     94                 batch_y_mark = batch_y_mark[:, -self.args.pred_len:, f_dim:].to(self.device)
---> 95                 loss_value = criterion(batch_x, self.args.frequency_map, outputs, batch_y, batch_y_mark)
     96                 loss_sharpness = mse((outputs[:, 1:, :] - outputs[:, :-1, :]), (batch_y[:, 1:, :] - batch_y[:, :-1, :]))
     97                 loss = loss_value  # + loss_sharpness * 1e-5

TypeError: 'NoneType' object is not callable

MY DATASET
![image](https://github.com/thuml/Time-Series-Library/assets/69142062/2ddff3f1-c956-40c0-97fc-2e8ef97aea36)

**Comment by Med-Rokaimi** [comment]
That was because setting the parameters. It is fixed after changing decoder/encoder inputs

**Comment by Pupuliu** [comment]
Hello, I have also encountered the same bug. Can you tell me how to solve this bug？

**Comment by Med-Rokaimi** [comment]
> That was because setting the parameters. It is fixed after changing decoder/encoder inputs

 It is fixed by changing decoder/encoder values in the parameter's settings (args)
