### ISSUE TITLE
Inverse the normalization of the results in preds and trues npy

### ISSUE THREAD

**Issue by Med-Rokaimi** [thuml/Time-Series-Library#132]
Thank you so much for the open source and for your powerful support. 
Sorry for repeating this issue because I'm still not able to get the data of preds.npy and trues.npy denormlized. 
It is not supposed that adding this line will cause to inverse the normalization ?
`

parser.add_argument('--inverse', action='store_true', help='inverse output data', default=True)
`

**Comment by HuntZhaozq** [comment]
@GuoKaku Hello, the below codes will occur errors:  found array with dim 3. None expected <= 2.
outputs has dim 3. But inverse_transform requires dim 2 input. Please help to solve it.
       outputs = test_data.inverse_transform(outputs)
       batch_y = test_data.inverse_transform(batch_y)

**Comment by HuntZhaozq** [comment]
> Sorry for bugs and now we've fixed it. Feel free to contact us if any further problems are raised.

Hello, the below codes will occur errors: found array with dim 3. None expected <= 2.
outputs has dim 3. But inverse_transform requires dim 2 input. Please help to solve it.
outputs = test_data.inverse_transform(outputs)
batch_y = test_data.inverse_transform(batch_y)

**Comment by bigdata2013lee** [comment]
> > Sorry for bugs and now we've fixed it. Feel free to contact us if any further problems are raised.
> 
> Hello, the below codes will occur errors: found array with dim 3. None expected <= 2. outputs has dim 3. But inverse_transform requires dim 2 input. Please help to solve it. outputs = test_data.inverse_transform(outputs) batch_y = test_data.inverse_transform(batch_y)

i meet the same plm.

**Comment by bigdata2013lee** [comment]
> @GuoKaku Hello, the below codes will occur errors: found array with dim 3. None expected <= 2. outputs has dim 3. But inverse_transform requires dim 2 input. Please help to solve it. outputs = test_data.inverse_transform(outputs) batch_y = test_data.inverse_transform(batch_y)

by the way, i wonder to know why do we need to perform data normalization in the dataloader if it has already been done during forward propagation?

**Comment by bigdata2013lee** [comment]
> > Sorry for bugs and now we've fixed it. Feel free to contact us if any further problems are raised.
> 
> Hello, the below codes will occur errors: found array with dim 3. None expected <= 2. outputs has dim 3. But inverse_transform requires dim 2 input. Please help to solve it. outputs = test_data.inverse_transform(outputs) batch_y = test_data.inverse_transform(batch_y)

i fix it by this code:  return data * self.scaler.scale_[-1] + self.scaler.mean_[-1],  you should make sure the last column is your prediction col

**Comment by pohlchri** [comment]
Hello, thanks for your work. I am currently facing the same issue. Can you please provide the context around your fix? Current line of code: outputs = test_data.inverse_transform(outputs) batch_y = test_data.inverse_transform(batch_y) Your fix: return data * self.scaler.scale_[-1] + self.scaler.mean_[-1]. Where did you put this line of code? Thank you very much!

**Comment by Giv0126** [comment]
> Sorry for bugs and now we've fixed it. Feel free to contact us if any further problems are raised.很抱歉出现错误，现在我们已经修复了它。如果提出任何其他问题，请随时与我们联系。

您好，我想请问一下，我在做插补类任务的时候，最后结果好像还是无法反归一化，请问这个是什么问题呢？我用的模型是TimesNet，麻烦您看到可以帮我解答一下，万分感谢，最后祝生活愉快！
