### ISSUE TITLE
TimeNet的predict_linear

### ISSUE THREAD

**Issue by zhizhuaa** [thuml/Time-Series-Library#133]
您好！请问model中的self.predict_linear = nn.Linear(self.seq_len, self.pred_len + self.seq_len)的作用是什么？不是很理解为什么要把输入序列的长度变成self.pred_len + self.seq_len

**Comment by wuhaixu2016** [comment]
您好，感谢关注！
一个直观的作用是将模型输出长度与最终结果对齐。更多讨论请见：https://github.com/thuml/Time-Series-Library/issues/38
