### ISSUE TITLE
Questions about PatchTST model channel-independent encoder

### ISSUE THREAD

**Issue by seraveea** [thuml/Time-Series-Library#134]
In the original PatchTST paper they use channel-independent attention layer, but in your implementation of PatchTST I didn't see this part and it seems that regular attention layers used as encoders. Does the implentation in this repo could have the same performance as the channel-independent PatchTST? Or you have this channel-independent ops and I miss it? Thank you

**Comment by wuhaixu2016** [comment]
Hi, thanks for your detail review.
We have already included the channel-ind design in PatchTST. You may find that in patch embedding, here: https://github.com/thuml/Time-Series-Library/blob/main/layers/Embed.py#L170
