### ISSUE TITLE
experiment results

### ISSUE THREAD

**Issue by CSyyn** [thuml/Time-Series-Library#14]
I try to reproduce the exp results on M4 datasets, but I get pretty bad performance, it's far away from the performance in the paper .I just simply run the short-term forecasting scripts for M4 datasets, so I want to ask there is something wrong in your scripts or how can I get the right results

**Comment by htg17** [comment]
Which subset and which model did you get bad performance? We have just tested our model from our Github repository, and the result is:
![1](https://user-images.githubusercontent.com/53956164/221468362-4c4f12fe-0a6b-42e8-92ba-03c1fbd5289a.png)

Can you paste your running log for detailed analysis?

**Comment by CSyyn** [comment]
I run the Informer model on the M4 dataset by your scripts, here is the results. I run the scripts twice ,and get the same performance. Although I know the Informer model may be worse than TimesNet, the results are so ridiculous
![微信图片_20230227160504](https://user-images.githubusercontent.com/63851708/221507592-868b1590-4cac-4a79-8a01-96ea9b338dab.png)

**Comment by htg17** [comment]
M4 dataset include various patterns of time series. Some sub-dataset have large mean and variance, so it might be difficult for some models to learn the representation.

In our latest published version, we use nomalization methods proposed by [Non-stationary Transformer](https://openreview.net/pdf?id=ucNDIDRNjjv) to improve these baselines, including Informer, Pyraformer and Reformer.
