### ISSUE TITLE
Should we use lowercase flag values `train` or `test` in `exp_classfication`?

### ISSUE THREAD

**Issue by rdyan0053** [thuml/Time-Series-Library#140]
https://github.com/thuml/Time-Series-Library/blob/58751808f5198e97eea67a69760c4887eef6d562/exp/exp_classification.py#L22C1-L23C61

**Comment by wuhaixu2016** [comment]
Hi, it is right to use the uppercase flag values.

This is because that the data filename is "xxx_TEST.ts" and "xxx_TRAIN.ts" and we use the flag to describe the filename: https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L654
