### ISSUE TITLE
For

### ISSUE THREAD

**Issue by zhizhuaa** [thuml/Time-Series-Library#142]

**Comment by wuhaixu2016** [comment]
Sorry, I don't know what you mean. Would you please express your issue with more detail?

**Comment by zhizhuaa** [comment]
您好，我有两个问题想请教一下您。
1、该模型单步预测的时候效果没有一层输出通道数为64的RNN层/CNN层加上一个线性层的好是什么原因呢？
2、将conv中的两个Inception_Block_V1都换成ConvNeXt的Block，效果变差了，是我替换的方法不对吗？是需要将conv换成ConvNeXt神经网络（包括下采样和ConvNeXt的Block 1:1:3:1的堆叠）可是这样H W会因为下采样减小从而报错。
