### ISSUE TITLE
Improve predictive performance for other tasks

### ISSUE THREAD

**Issue by zhoulian-sudo** [thuml/Time-Series-Library#145]
Hello author, thank you for sharing the code. I have a question for you. Do you think the TimesNet module may serve as an intermediate module in vehicle (pedestrian) trajectory prediction tasks to improve prediction performance?

**Comment by wuhaixu2016** [comment]
Hi, we have not evaluated TimesNet performance in trajectory prediction.  So I cannot give a confident result to this question.

But I think it is a promising topic.  If you have any progress, please kindly inform us.
