### ISSUE TITLE
Error variable def in data_provider/data_loader.py

### ISSUE THREAD

**Issue by linpingta** [thuml/Time-Series-Library#148]
It seems no pattern defined in function "load_all", which will generate an error:

```
        if len(input_paths) == 0:
            raise Exception("No .ts files found using pattern: '{}'".format(pattern))
```

I guess from code it seems that pattern should be defined as "ts" and also used for path filter.

Please correct me if wrong

**Comment by GuoKaku** [comment]
Thank you for your correction! We've fixed it.
