### ISSUE TITLE
timesnet的 timesblock输出为0

### ISSUE THREAD

**Issue by linestao** [thuml/Time-Series-Library#15]
您好，我在使用timesnet在心电信号上的时候，遇到了一个问题：
心电信号经过一层timesblock输出后的为0，导致在第二层timesblock上无法正确进行傅里叶变化求周期值。
请问您在处理类似数据集的时候，有没有遇到类似的状况？

**Comment by wuhaixu2016** [comment]
您好，可以给一个心电信号的case吗？一般来说深度网络不太可能输出全是0的值，可以尝试一下增大输入历史观测的长度

**Comment by linestao** [comment]
感谢您的回复
刚才定位到了BUG的位置。
               enc_out = self.layer_norm(self.model[i](enc_out))
在nn.LayerNorm（）上
初步判断是 数据经过了LN 在GPU上会变成0
输入的数据格式为【batchsize*7680*1】（7680=60S*128HZ）
剩下的问题我会进一步寻找。
