### ISSUE TITLE
Very big request

### ISSUE THREAD

**Issue by TDL77** [thuml/Time-Series-Library#150]
Thank you for your work. I have a very big request to you, could you make a jupiter notebook how to run any Time Series Library (TSlib) model. I want to test on my own data, but I'm still learning. 
Thank you very much.

**Comment by wuhaixu2016** [comment]
Hi, thanks a lot for your suggestion. We will add this to out todo list.

**Comment by GuoKaku** [comment]
Hi, we've uploaded the times-series-lab tutorial, using TimesNet as an example. We'll be happy if you find it useful and we're looking forward to your feedback!

**Comment by TDL77** [comment]
Forgive me for my ignorance. I created a laptop in the collab and downloaded all the data. If you have time, you can show how to train the model.
I’m now very interested in testing the model in a laptop using my data, and I’ll definitely figure out how everything works under the hood of the model a little later.
Thanks a lot. I really hope that you can help me.

https://colab.research.google.com/drive/1U3GR9vBEBoLIsweHPLElW4CtkHicE72k?usp=sharing
