### ISSUE TITLE
pytorch新版本与新基线

### ISSUE THREAD

**Issue by longlive1234** [thuml/Time-Series-Library#151]
您好，一直很关注您团队的工作，您的代码是基于pytorch1.7.1运行的，因为版本的原因，想请问一下在新的pytorch1.11，1.12或者2.0.1版本上您和团队有没有测试并发布相关系列的基线呢？

**Comment by zh-i9** [comment]
同问，烦请作者更新一下版本。

**Comment by itdevwu** [comment]
根据我的经验，用户自行更换新的pytorch版本不会导致兼容性问题。

According to my personal experience, update of PyTorch by user shall cause no compatibility issues.

**Comment by ArberChang** [comment]
版本冲突有点多呀，模型跑不起来

**Comment by mayii2001** [comment]
自己部署的时候1.7.1报错缺少RAdom，需要升级1.12.1，似乎实际上已经在用高版本

**Comment by wuhaixu2016** [comment]
您好，pytorch1.7.1只是为了保障一些使用fft模型的效果可以复现，如果只是为了跑通代码进行实验，不需要1.7.1，同时使用更高版本的pytorch并不会让模型效果下降太多。
