### ISSUE TITLE
Questions about ablation experiments in research papers

### ISSUE THREAD

**Issue by fengqsam** [thuml/Time-Series-Library#152]
大神你好，你的论文写得很好，模型设计新颖，时间序列任务上适用面广
在看论文中消融实验时有一个问题想请教下您
在您进行对于异常检测中使用了几种不同CV方法进行了对比，但在提供的源码中没有找到除inception外的CV模型，这部分和timesNet的实现是在哪里可以参考吗？

![1690604242467](https://github.com/thuml/Time-Series-Library/assets/17719434/56a3a2e4-cc8a-4b69-8c3e-8af7190f65ca)

**Comment by wuhaixu2016** [comment]
您好，感谢关注，这些cv的block都有非常成熟的开源代码，可以从他们的官方仓库中找到。

**Comment by HuntZhaozq** [comment]
可是替换一下block出现维度不对，请问如何操作呀
