### ISSUE TITLE
EOF Error in exp_classification.py

### ISSUE THREAD

**Issue by saqibejaz** [thuml/Time-Series-Library#155]
I wonder why I get **EOFError: Ran out of input error** at _for i, (batch_x, label, padding_mask) in enumerate(train_loader)_ line in the train() function of exp_classificaton.py file. I am running EthanolConcentration experiment.

**Comment by DMLL-001** [comment]
I also encountered the same problem

**Comment by DMLL-001** [comment]
resolution method ： import dill as pickle

**Comment by saqibejaz** [comment]
> resolution method ： import dill as pickle

It didn't work. Still getting the same "EOFError: Ran out of input" error.

**Comment by xueyagaga** [comment]
> 

`import dill as pickle` does solve this problem.
However, you should change ` import pickle` to `import dill as pickle` at line 15 of the `Lib\multiprocessing\reduction.py` file.
I guess there is a strange library conflict.

**Comment by DMLL-001** [comment]
把 源代码库中的这一行import给注释掉



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月22日(星期二) 晚上6:03
收件人: ***@***.***&gt;; 
抄送: "Orange ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [thuml/Time-Series-Library] EOF Error in exp_classification.py (Issue #155)





   
import dill as pickle does solve this problem.
 However, you should change  import pickle to import dill as pickle at line 15 of the Lib\multiprocessing\reduction.py file.
 I guess there is a strange library conflict.

**Comment by xueyagaga** [comment]
> 

It still doesn't seem to solve the problem, the program is stuck here, does not continue to run and does not report errors, I wonder if there is a way to disable multiprocessing.
![image](https://github.com/thuml/Time-Series-Library/assets/64541307/0b9295c6-20c7-4020-b3e8-5774c6f1ab78)

**Comment by saqibejaz** [comment]
I set the "--num_workers" to 0 to stop multiprocessing. The code runs fine after that.

Sent from Yahoo Mail on Android 
 
  On Thu, Aug 24, 2023 at 9:19 PM, ***@***.***> wrote:   




It still doesn't seem to solve the problem, the program is stuck here, does not continue to run and does not report errors, I wonder if there is a way to disable multiprocessing.

**Comment by GuoKaku** [comment]
Sorry for your trouble but we meet that weird problem here. Could you pls provider some further information?

**Comment by rkdlight** [comment]
Hi! I have the same problem with it. What information can I provide to solve this problem?

**Comment by saqibejaz** [comment]
Hi,

As I mentioned previously, I set num_workers=0 and it solved my problem. Mind that I was using windows operating system.

Saqib.
    On Wednesday, October 18, 2023 at 10:57:44 PM GMT+8, rkdlight ***@***.***> wrote:  
 
 


Hi! I have the same problem with it. What information can I provide to solve this problem?

**Comment by wuhaixu2016** [comment]
Hi, thanks for the answer from @saqibejaz . Setting num_workers as 0 is useful for windows users.
