### ISSUE TITLE
关于所需预测的变量：过去信息无法使用的问题

### ISSUE THREAD

**Issue by Yuanen-Pang** [thuml/Time-Series-Library#156]
非常感谢您在Autoformer中的详细解答以及新架构的贡献，有以下问题想向您请教：
（1）某序列特征记为（F1-F10），要求是用F1-F9预测F10，Autoformer、TimesNet这两种结构都过分专注对预测变量的过去信息提取，无法使用该变量的情况下（比如ETT数据集中预测的OT，如果不允许使用该变量，怎么办呢），又如何考虑？
（2）论文中说预测变量有周期内与周期间相关性，我理解的应该是特指F10对F10的相关性，那么F1-F9在切片过程跟F10的操作是一样的，难道是认为F10与他们之间也存在周期内和周期间相关性吗？这个不太能理解
（3）对于时间序列中周期很长的某个分量（比如与月有关，一个月包含几千个点），96个点只占这一个周期的一小部分，属于周期的相关性是否就提取不到了呢？

**Comment by wuhaixu2016** [comment]
您好，感谢关注
（1）如果不使用过去观测，这个问题就不是自回归问题，而是回归问题，从结构上Autoformer、TimesNet都可以使用，但是需要效果等待验证
（2）您提的用F1-F9预测F10，不属于目前所有时序预测模型的适用范畴，所以可以进行尝试，但是效果有待验证。不过因为这些模型大多都是深度模型（DLinear除外），所以对于您提到的回归问题，应该也有一定的帮助。
（3）针对周期性特别长的情况，需要针对性的增长input_length，但是这也需要一定的平衡，因为越多的输入数据可能带来更多的噪音。
