### ISSUE TITLE
关于异常检测

### ISSUE THREAD

**Issue by wecandoforit** [thuml/Time-Series-Library#158]
非常感谢作者的代码！作为一名初学者，想用您的模型进行有关振动信号的异常检测分类问题，但是在使用过程中发现效果并不是很好，因为我调整了网络层次之后，效果依旧和之前一样，基本属于这种：Precision: 0.2971, Recall: 0.3333, F1 Score: 0.3142还请大佬有空看看谢谢

**Comment by wuhaixu2016** [comment]
您好，感谢关注，
针对您的新数据，我觉得首先要调整好input_length这个超参数，其次需要根据您的任务（逐点判断？还是逐序列判断？）进行TimesNet中的2D backbone调整，具体效果其实会强相关于您这个任务的难度，需要针对性判断。
