### ISSUE TITLE
关于data_loader.py中border1s和border2s作用的问题

### ISSUE THREAD

**Issue by zhuyulong94** [thuml/Time-Series-Library#159]
这两个list作用是什么，代码中border1s = [0, 12 * 30 * 24 * 4 - self.seq_len, 12 * 30 * 24 * 4 + 4 * 30 * 24 * 4 - self.seq_len]
 ，border2s = [12 * 30 * 24 * 4, 12 * 30 * 24 * 4 + 4 * 30 * 24 * 4, 12 * 30 * 24 * 4 + 8 * 30 * 24 * 4]。使用默认数据集ETHh1训练时，再load数据时，val数据获取的是空数据导致报错。对比论文猜测应该是划分数据集，论文中说使用滑动窗口模式进行获取。这里有两个疑惑：1.border1s 计算方法和作用，2.如何实现滑动窗口获取数据集。

**Comment by wuhaixu2016** [comment]
您好，这个是按照比例划分训练集、验证集、测试集
