### ISSUE TITLE
TimesNet about classification job

### ISSUE THREAD

**Issue by Bsdnbo** [thuml/Time-Series-Library#16]
What's the "pred_len" meaning in TimesBlock ? Why inputs of TimesBlock are padded to length of "seq_len + pred_len"？( not seq_len)

**Comment by wuhaixu2016** [comment]
Hi, we have unified all the five tasks in one code base. Pred_len is for the forecasting task, which means the length of predicted future. In the classification problem,  pred_len is set as 0 (line 25 of https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_classification.py).
