### ISSUE TITLE
Inception_Block_V1中是不是没有用到最大池化max pooling

### ISSUE THREAD

**Issue by Tang4109** [thuml/Time-Series-Library#160]
老师，您好，我看了Inception_Block_V1模块的代码，发现没有用到inception中的最大池化操作，不知道您这边是怎么考虑的

**Comment by wuhaixu2016** [comment]
您好，这个池化操作会造成2D tensor的尺度变化，而TimesNet的输入和输出序列长度保持不变，所以并没有采用池化操作。
