### ISSUE TITLE
torch version too low

### ISSUE THREAD

**Issue by cs-fisha** [thuml/Time-Series-Library#162]
Why the author uses the version of torch1.7 ?? Since RTX 3090 can only support the version of pytorch at least torch 1.8.

**Comment by wuhaixu2016** [comment]
Hi, we conduct all the experiments in RTX 3090 with torch 1.7.
You can install this version of pytorch to match your cuda version with the following scripts:
pip install torch==1.8.1+cuxxx -f https://download.pytorch.org/whl/torch_stable.html
