### ISSUE TITLE
Could you explain label length, sequence length?

### ISSUE THREAD

**Issue by gabriead** [thuml/Time-Series-Library#164]
Hi Time-Series-Library Team,
I see that in your script you are using three different lenghts for the data. Could you please explain the difference between label and sequence length? Why are these parameters not set in the short_term_forecast?

**Comment by wuhaixu2016** [comment]
Hi,
(1) About sequence and label length
They are both for Transformers. Label length is the partial past observation that concat to the future placeholder as the decoder prompt. Sequence length the full past observation.
(2) Why not in short-term forecast.
Here, we limited the short-term forecast as the M4 benchmark, whose hyperparameters a fixed as https://github.com/thuml/Time-Series-Library/blob/main/data_provider/m4.py#L103
