### ISSUE TITLE
如何预测生成新的变量？

### ISSUE THREAD

**Issue by HuntZhaozq** [thuml/Time-Series-Library#165]
作者您好！我刚刚接触时序，有一些问题想请教下，还请不吝赐教，谢谢！
1. 请问TimesNet可以生成新的数据吗？时序数据有多个特征，但是想预测生成新的一列特征，应该如何修改代码？
2. 请问时间序列预测任务中，如果预测数据没有groundtruth，应该如何操作，有类似的文章吗？

**Comment by wuhaixu2016** [comment]
您好，感谢关注
（1）我理解您所说的“生成新的数据”是指回归出另外一个变量的变化，如果这样的话，您仅需要使用MS设置，multiple-variate-to-single-variate即可。
（2）如果您指的是自回归任务，没有ground truth的话，也可以通过将时间序列前后分开，分别作为输入和预测，来定义“自监督”任务；如果您指的是回归任务，如果没有ground truth，那么这个模型是不可训练的，也就无法完成；如果您指的是模型部署做预测，这个只需要改一下模型的test代码即可。
另外，我们之前一篇用于时间序列预训练的论文，您可能感兴趣：https://arxiv.org/pdf/2302.00861.pdf
