### ISSUE TITLE
如果已知未来的其他变量该如何预测OT列呢？

### ISSUE THREAD

**Issue by Et6an** [thuml/Time-Series-Library#167]
比如说要预测8月19日的这24个时间点的数据，如果19日的未来其他变量是已知的情况下，能否利用TimeNet进行预测呢？就是不仅仅使用历史的数据预测未来。
![屏幕截图 2023-08-22 093411](https://github.com/thuml/Time-Series-Library/assets/112670349/f68582f1-3969-48c7-bda7-9b645f66f74f)

**Comment by wuhaixu2016** [comment]
您好，在timesnet的最底层有一个未来长度的对齐操作：https://github.com/thuml/Time-Series-Library/blob/main/models/TimesNet.py#L113
您可以将未来的其他变量在这一步embedding进去

**Comment by Et6an** [comment]
十分感谢！
