### ISSUE TITLE
如何预测未在batch_x内出现的单变量

### ISSUE THREAD

**Issue by HuntZhaozq** [thuml/Time-Series-Library#168]
假设输入中的序列中只有V1,V2,V3，输入不包含OT，预测下一步的OT
比如输入油门、加速度的时间序列，输出预测的当前时速(OT)
请问如何实现？我使用MS参数后依然会把OT作为输入。

翻看记录，您提到的基于目前的代码来写的话，可以在exp文件中遮住OT对应的列。
这个具体如何实现呀？直接在训练和测试的batch_x里将OT列遮住吗？怎么遮住？
这样的话，TimesNet如何拟合出未曾出现过的OT？

**Comment by Et6an** [comment]
是不是就是做成回归预测啊

**Comment by HuntZhaozq** [comment]
遮住OT的话，没有gt，怎么回归噢 @Et6an

**Comment by wuhaixu2016** [comment]
您好，确实是一个回归任务，相当于用其他要素估计出新的变量。但是您提到的没有gt比较令人费解，如果真的gt完全没有的话，就是无监督学习了，这个任务是不可做的。

**Comment by Ekanees** [comment]
是不是可以搞成分类任务，将ot分成很多类？
