### ISSUE TITLE
关于Dataset_ETT_hour类的scale参数设置

### ISSUE THREAD

**Issue by rdyan0053** [thuml/Time-Series-Library#171]
在Dataset_ETT_hour中使用了StandardScaler对数据的各个特征进行了处理，我也观察到该类中有inverse_transform函数，对数据进行恢复，但是项目本身并没有这样使用。
我想在测试test的时候使用该函数，请问是否可行？

**Comment by wuhaixu2016** [comment]
您好，目前学术论文中大家使用的benchmark均没有进行inverse_transform，为了公平比较，不需要使用inverse_transform。但是如果您需要部署一个预测模型，则需要使用inverse_transform函数
