### ISSUE TITLE
some confusing contexts, seems like param 'TRAIN' or 'TEST' will leads to no branch, and vali_loader shares the same 'TEST' with test_loader

### ISSUE THREAD

**Issue by Choujim** [thuml/Time-Series-Library#173]
https://github.com/thuml/Time-Series-Library/blob/3caf8881de7c205687c0b9517a90d7d8de0ca56e/exp/exp_classification.py#L80

**Comment by wuhaixu2016** [comment]
Hi, we follow the convention setting in this area, where the classification task does not have the val set.
