### ISSUE TITLE
关于exp_anomaly_detection文件，test方法中的adjustment函数

### ISSUE THREAD

**Issue by fengqsam** [thuml/Time-Series-Library#177]
想请问exp_anomaly_detection的test方法中，  gt, pred = adjustment(gt, pred)，这一句作用是什么呢，为什么要根据真实值修改预测值，这样会影响最后评价结果，作者这边的考虑是怎么样的呢？

**Comment by wuhaixu2016** [comment]
您好，具体解释请见这个issue：https://github.com/thuml/Anomaly-Transformer/issues/14
