### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'frequency_map'，

### ISSUE THREAD

**Issue by goodlucky111** [thuml/Time-Series-Library#178]
当我用自己的数据集做短期预测时报错，说命名空间没有frequency_map，但run.py里面并没有frequency_map这个参数啊

**Comment by wuhaixu2016** [comment]
您好，这个算法库的短期预测只针对M4数据集，如果你想做短期预测的话，可以使用long-term-forecasting setting，然后将输入和输出长度设置成你的需要。注意需要重写一下Data_custom函数。
