### ISSUE TITLE
预测的时间序列有缺失值处理问题

### ISSUE THREAD

**Issue by lizhuoq** [thuml/Time-Series-Library#179]
输入的时间序列没有缺失值，如果要预测的时间序列内有缺失值的情况，可以在构建dataset的时候在缺失位置padding一个值，然后在计算loss的时候对缺失位置进行mask计算loss，这样处理可行吗？希望收到您的回复，谢谢。

**Comment by wuhaixu2016** [comment]
您好，可以这样的，我们这个算法库中实现的imputation任务也都是这样做的。
