### ISSUE TITLE
[Dataset] How to feed my own dataset

### ISSUE THREAD

**Issue by mokeeqian** [thuml/Time-Series-Library#18]
Hi, nice job!
I am confused that how to feed **my own data** into the models, such as TimesNet,  should I write the dataloader?

Is there any possiablity that the Library could handle the origin pandas DataFrame?

**Comment by wuhaixu2016** [comment]
Hi, you may find Dataset_Custom helpful (line 196 in https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py). And Dataset_Custom is only for long-term forecasting. For other tasks, maybe it is hard to express them all in DataFrame.

But we will try to make the adding new dataset more convenient soon.

**Comment by mokeeqian** [comment]
> Hi, you may find Dataset_Custom helpful (line 196 in https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py). And Dataset_Custom is only for long-term forecasting. For other tasks, maybe it is hard to express them all in DataFrame.
> 
> But we will try to make the adding new dataset more convenient soon.

okay, thank you!
I will have a try.
