### ISSUE TITLE
关于TimesNet分类使用自制数据集

### ISSUE THREAD

**Issue by 1400432574** [thuml/Time-Series-Library#181]
感谢作者的开源。在\Time-Series-Library-main\data_provider\data_loader.py 639行的注释中提到  root_path：包含所有单个csv文件的目录 ，但是实际代码中的功能是读取的ts格式的文件加载数据集。 我的自制数据集是csv文件，应该如何加载数据集？

**Comment by wuhaixu2016** [comment]
Hi, you need to rewrite the dataloader.
