### ISSUE TITLE
测试出现数据集泄露？

### ISSUE THREAD

**Issue by hhr114** [thuml/Time-Series-Library#184]
注意到在此代码框架下，做时序预测任务时，对一些测试集（如ETTh1）的标准化处理涉及读入整个测试集后做统一处理，从时序数据的角度，如果要预测2016-07-01 03:00:00时刻的结果，是不可能看到2016-07-01 04:00:00的特征的，所以不能用2016-07-01 04:00:00的信息对2016-07-01 03:00:00的特征进行标准化。
而这几乎是采用该代码框架的模型的通用做法，这一做法是否有测试集泄露之嫌？
相关代码所在行的链接 [StandardScaler()#L65](https://github.com/thuml/Time-Series-Library/blob/beb2cb0842b30d17ea4de8862f1529e53d9b5bbb/data_provider/data_loader.py#L65)

**Comment by qinmoelei** [comment]
他们好像都是用训练集的数据做normalization的 应该没啥大问题

**Comment by hhr114** [comment]
看我上面的链接，这情形应该是在用整体测试集来fit标准化的参数啊

**Comment by qinmoelei** [comment]
> 看我上面的链接，这情形应该是在用整体测试集来fit标准化的参数啊

`self.scaler.fit(train_data.values)` 这证明scaler使用train data的mean和std做的 然后只不过是这个scaler是作用到所有的数据集（`data = self.scaler.transform(df_data.values)`），但是valid和test都在train data的未来 所以没泄露这样？

**Comment by hhr114** [comment]
确实，这么一看应该没问题，谢谢~
