### ISSUE TITLE
long-term forecasting 和 short-term forecasting 的区别

### ISSUE THREAD

**Issue by hhr114** [thuml/Time-Series-Library#185]
对于TimesNet，请问long-term forecasting 和 short-term forecasting 的实现区别是什么？对于自制的数据集，请问怎么判断应该调用long-term forecasting 还是 short-term forecasting 呢？

**Comment by wuhaixu2016** [comment]
您好，单从模型结构角度上讲两者没有区别，改动的只有模型output长度这一个超参数。在这个算法库中，我们讲M4作为short-term预测的典型案例（因为这个数据集在业界非常受重视）。所以如果你想使用自己的数据集，可以直接用long-term forecasting setting，把预测长度设置为你需要的数值即可。
