### ISSUE TITLE
关于预测结果不准确的问题

### ISSUE THREAD

**Issue by lsl0000** [thuml/Time-Series-Library#186]
您好，我将12个维度的流量数据分别用Timesformer进行预测，由于数据只有2000个样本，所以选择的参数是 --seq_len 20，--pred_len 1. --d_model 512 --d_ff1024 .但12个维度有2个明显不准确。随后我将不准确的两个用户删去后输入10维的数据，结果有3个维度不准确。这些不同维度的流量数据是同一个模拟器生成的，流量规律是相似的，请问为什么会出现这么大的误差呢，我使用FEDformer和Crossformer时也遇到了相同的问题，无论如何调整d_model 和d_ff都无法解决。请问我该如何改善这个问题，感激不尽！

![结果3](https://github.com/thuml/Time-Series-Library/assets/73702238/87cd31a5-c525-401c-9115-7c2e0ef5569e)
![结果4](https://github.com/thuml/Time-Series-Library/assets/73702238/820abcdc-47e1-4380-a524-88e86b71c562)

**Comment by lsl0000** [comment]
是的，12维度每次训练都是有两个维度不准确。如果删去2个不准确的维度，10个维度的数据还是会有2个维度不准确；如果用6个维度进行训练的话，会有3个维度不准确。
我昨晚对数据进行了相关性的分析，发现2个不准确的维度与其他维度都无相关性，其他维度之间都有较强的相关性。
所以我想请问一下，进行multivariate predict multivariate的预测时，Timesnet会考虑不同维度之间的相关性吗，相关性弱的维度会被视为噪声，从而预测结果不准确吗？

**Comment by lsl0000** [comment]
> 您好，您可以尝试增大数据量或增大数据长度试试。还有请问，是每次训练都是有两个维度不准确吗？

是的，12维度每次训练都是有两个维度不准确。如果删去2个不准确的维度，10个维度的数据还是会有2个维度不准确；如果用6个维度进行训练的话，会有3个维度不准确。
我昨晚对数据进行了相关性的分析，发现2个不准确的维度与其他维度都无相关性，其他维度之间都有较强的相关性。
所以我想请问一下，进行multivariate predict multivariate的预测时，Timesnet会考虑不同维度之间的相关性吗，相关性弱的维度会被视为噪声，从而预测结果不准确吗？

**Comment by HuntZhaozq** [comment]
您好，请问20个时刻预测1个时刻点的话，你的图是怎么画出来的呀

**Comment by lsl0000** [comment]
> 您好，请问20个时刻预测1个时刻点的话，你的图是怎么画出来的呀
result里面有两个预测值和真实值的.npy
shape是（测试集长度，1，维度），一个维度画一张图

**Comment by HuntZhaozq** [comment]
欸，我看你的设置是历史20个时刻预测未来1个时刻，这个图是怎么做出350个预测值的？所以测试集是一共有370个点？测试的时候用前20个预测未来1个，窗口不断往前滑动，最后得到这350个pred吗？

**Comment by lsl0000** [comment]
> 欸，我看你的设置是历史20个时刻预测未来1个时刻，这个图是怎么做出350个预测值的？所以测试集是一共有370个点？测试的时候用前20个预测未来1个，窗口不断往前滑动，最后得到这350个pred吗？

测试集就350个，你打印一下result文件夹里面的结果就知道了
