### ISSUE TITLE
关于FiLM和MICN无法运行的问题

### ISSUE THREAD

**Issue by lsl0000** [thuml/Time-Series-Library#187]
您好，我使用我自己的数据在运行long_term_forcast模型时，FiLM和MICN无法运行（其他模型都可以正常运行）报错如下：
请问是这两个模型的框架和其他模型不一样吗，我需要修改哪些地方呢，望指教，感激不尽！
![错误图1](https://github.com/thuml/Time-Series-Library/assets/73702238/c5e96839-e645-406c-9c9e-3b5687ff81aa)
![错误图2](https://github.com/thuml/Time-Series-Library/assets/73702238/1f79bf5d-e8dc-4af9-af86-610e79d3f84d)

**Comment by GuoKaku** [comment]
你好！这里先回答你的第二个疑问（关于MICN）。如果你查看MICN model的代码，在line 166处进行了decoder的embedding。这里的embedding的初始化向量seasonal_init_dec的长度应为seq_len+pred_len（见line 164-165）。而x_mark_dec的长度由数据的dataloader决定（你可以看看自己的dataloader），是label_len+pred_len.而这两个向量的维度应当相同，所以要求seq_len==label_len，你可以通过在你的bash脚本中设置，然后应当就没有问题了

**Comment by GuoKaku** [comment]
关于FiLM的问题，非常抱歉，我这边可能需要更多的信息。但从已有的error信息来看应当是某处的input没有正确初始化/输入，它的size是0，以致在SpectralConv1d模块的forward中，在compl_mul1d函数处报错。具体的您可以跟踪一下报错处输入的shape或查看一下是否正确输入。比如可以从FiLM.py line 148的x_in_c开始检查。
