### ISSUE TITLE
Problem regarding the implementation for basic self attention

### ISSUE THREAD

**Issue by qinmoelei** [thuml/Time-Series-Library#188]
By combining [`Transformer.py`](https://github.com/thuml/Time-Series-Library/blob/beb2cb0842b30d17ea4de8862f1529e53d9b5bbb/models/Transformer.py#L26), [`Transformer_EncDec.py`](https://github.com/thuml/Time-Series-Library/blob/beb2cb0842b30d17ea4de8862f1529e53d9b5bbb/layers/Transformer_EncDec.py#L40) and  [`SelfAttention_Family.py`](https://github.com/thuml/Time-Series-Library/blob/beb2cb0842b30d17ea4de8862f1529e53d9b5bbb/layers/SelfAttention_Family.py#L20). I believe in the basic self-attention implementation, during the encoder, the attention takes QKV where Q=K=V as demonstrated [here](https://github.com/thuml/Time-Series-Library/blob/beb2cb0842b30d17ea4de8862f1529e53d9b5bbb/layers/Transformer_EncDec.py#L40), where x,x,x are all identical. I think it is better to add a linear projection in the [attention part](https://github.com/thuml/Time-Series-Library/blob/beb2cb0842b30d17ea4de8862f1529e53d9b5bbb/layers/SelfAttention_Family.py#L20) instead to make a difference among QKV before directly calculating the attention score.

**Comment by GuoKaku** [comment]
You're right, but the implementation of the linear projection is in [class AttentionLayer](https://github.com/thuml/Time-Series-Library/blob/beb2cb0842b30d17ea4de8862f1529e53d9b5bbb/layers/SelfAttention_Family.py#L179) , so that QKV differs

**Comment by qinmoelei** [comment]
Thank you. Sorry for the troubling.
