### ISSUE TITLE
args.freq question

### ISSUE THREAD

**Issue by cenggokhan** [thuml/Time-Series-Library#189]
Hello, I have a multivariate time series data about a machine running everyday except for Sundays between hours 08:00 AM to 08:00 PM with interval 15 minutes. I am confused about selecting the best args.freq for this dataset for TimesNet.
How should I select value for args.freq?

**Comment by wuhaixu2016** [comment]
Hi, you can set `args.freq` as `t` for minutely temporal embedding.
