### ISSUE TITLE
No module named 'reformer_pytorch'

### ISSUE THREAD

**Issue by kyungeun-lee** [thuml/Time-Series-Library#19]
I failed to run the code because there is no module named 'reformer_pytorch'.
I found there is "from reformer_pytorch import LSHSelfAttention" in SelfAttention_Family.py
and there is no file related to reformer_pytorch.
Could you give me a solution?

**Comment by wuhaixu2016** [comment]
Hi, please see line 6 of https://github.com/thuml/Time-Series-Library/blob/main/requirements.txt
You can obtain this by pip install reformer_pytorch==1.4.4

**Comment by kyungeun-lee** [comment]
Thanks for your kind reply!
