### ISSUE TITLE
TimesNet 时间序列分类复现结果与论文结果差异

### ISSUE THREAD

**Issue by zfbz** [thuml/Time-Series-Library#190]
<html>
<body>
<!DOCTYPE html><p cid="n0" mdtype="paragraph" class="md-end-block md-p md-focus" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">大佬你好！首先感谢 TimesNet 这篇出色的工作！我在 2080 服务器上复现 TimesNet </span><span md-inline="strong" class="md-pair-s " style="box-sizing: border-box;"><strong style="box-sizing: border-box;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">分类</span></strong></span><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">的结果，跑的是代码库提供的 scripts。但是跑出来的结果和论文中的所有出入，有些结果出入比较大（如 EC、HB、SRSCP1 的结果），想问为什么会这样，期待回复，谢谢！</span></p><figure class="md-table-fig" cid="n4" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">

数据集 | 复现结果 | 论文结果 | 差值（%）
-- | -- | -- | --
EC | 0.281 | 0.357 | -7.6
FD | 0.682 | 0.686 | -0.4
HW | 0.324 | 0.321 | +0.3
HB | 0.756 | 0.78 | -2.4
JV | 0.973 | 0.984 | -1.1
P-SF | 0.896 | 0.896 | 0
SRSCP1 | 0.877 | 0.918 | -4.1
SRSCP2 | 0.561 | 0.572 | -1.1
SAD | 0.99 | 0.99 | 0
UWGL | 0.869 | 0.853 | +1.6

</figure>
</body>
</html>

**Comment by qinmoelei** [comment]
这玩意儿不太能复现还挺常见的 按道理来讲应该是他们给个docker跑 这样比较容易复现
用GPU跑会因为硬件不太一样导致结果不太一样的

**Comment by wuhaixu2016** [comment]
您好，感谢关注，我觉得可以检查一下环境的配置
（1）我们使用的pytorch版本是1.7.1，如果更高版本的配置，pytorch中FFT受到了比较大的改动，所以可能会造成结果不一致
（2）时序分类任务中有几个数据集的数据量很小，比如EthanolConcentration、SelfRegulationSCP1&2，只有几百条数据，所以任务本身具有比较大的随机性，环境的改变可能会让波动放大，我们会尽快更新一版我们自己训练好的模型，用于大家测试

**Comment by sheeep996** [comment]
感觉不会发出来训练好的了，嚯嚯嚯
