### ISSUE TITLE
TSMixer: Lightweight MLP-Mixer Model for Multivariate Time Series Forecasting

### ISSUE THREAD

**Issue by alifa98** [thuml/Time-Series-Library#194]
Hello,

There is a paper which can be added to the library.

https://arxiv.org/abs/2306.09364v3

**Comment by wuhaixu2016** [comment]
Hi, thanks for your recommendation. 
We will add this to our todo list. But we have to point out that there are extensive papers in this area, it may take a while to find out the papers that we are interested in.

**Comment by alifa98** [comment]
Great, I can add it too.
Iwill send a pull request when I finish it, but it may take a while.

Thanks,
Ali
