### ISSUE TITLE
Confusion about padding in the classification task 

### ISSUE THREAD

**Issue by rdyan0053** [thuml/Time-Series-Library#195]
Hi,
For the classification task, the code `output = output * x_mark_enc.unsqueeze(-1)` is to padding the time series data?（对于分类任务，代码“output = output * x_mark_enc.unsqueeze(-1)”是为了填充时间序列数据？）

**Comment by wuhaixu2016** [comment]
您好，这是因为分类任务的序列长度不一致，在预处理阶段，我们将所有的序列都padding到了最大序列长度。所以在结尾使用*mask来保留数据真实的长度。
