### ISSUE TITLE
how to add future covariants to timesnet?

### ISSUE THREAD

**Issue by TMullerSG** [thuml/Time-Series-Library#196]
x_dec, x_mark_dec are not used in the forecast method of Timesnet.py, then how to add future covariants to timesnet?

**Comment by wuhaixu2016** [comment]
Hi, firstly you need to rewrite the dataloader.py. Then you can add the embeded covariants to this line: https://github.com/thuml/Time-Series-Library/blob/main/models/TimesNet.py#L112, where a special integration method is expected.
