### ISSUE TITLE
Inverse of the results in preds and trues

### ISSUE THREAD

**Issue by pohlchri** [thuml/Time-Series-Library#198]
Thank you very much for all of your work. I am currently trying to inverse the results to get the original data scale. However, using the inverse argument results in the following error for long-term-forecasting. "Found array with dim 3. None expected <= 2." Do you have any idea how to fix it? I am aware of https://github.com/thuml/Time-Series-Library/issues/132 this issue. Thank you very much.

**Comment by GuoKaku** [comment]
Hi, sorry for the trouble and we've fixed the bug. You can pull and try again.

**Comment by pohlchri** [comment]
Thank you very much for fixing it this quickly!!!
