### ISSUE TITLE
too many open files 

### ISSUE THREAD

**Issue by ramankhurana** [thuml/Time-Series-Library#200]
Hi Great Project and nice and clean code. 

I tried to run on the DLinear Model with 10 epochs and after 3 epochs it shows too many open files and programs ends. 

Is is known what might be causing this? 

Thanks

**Comment by GuoKaku** [comment]
Could your pls tell me which dataset you're running on and give some error info? And do you have similar problem when running other model on the same dataset? Right now I can't exactly tell why this failure occurs since I haven't found the same error here.

**Comment by ramankhurana** [comment]
Hello, I had used DLinear and this is the only model I tested for this dataset. But I can check for others and confirm if I see same error or not. 

Thanks for your reply. I shall confirm in a day/two.

**Comment by wuhaixu2016** [comment]
It seems this problem has been solved. Thanks again for your interest and discussion.
