### ISSUE TITLE
请问layers是什么库呢？该如何导入

### ISSUE THREAD

**Issue by civilengineeringdoghelpme** [thuml/Time-Series-Library#201]
from layers.Embed import DataEmbedding
from layers.Conv_Blocks import Inception_Block_V1   
报错显示没有layers

**Comment by civilengineeringdoghelpme** [comment]
已找到，非常感谢！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月27日 21:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [thuml/Time-Series-Library] 请问layers是什么库呢？该如何导入 (Issue #201) |

你好，layers是一个本地文件，在Time-Series-Library目录下，请确认一下

**Comment by retaimebien** [comment]
你可以正常运行语句吗
