### ISSUE TITLE
About LSTM on your paper 

### ISSUE THREAD

**Issue by fengqsam** [thuml/Time-Series-Library#203]
你好，想请问您LSTF的长期预测对比模型中的LSTM是sequence to sequence的模型吗？相关的baseline可以在哪里找到？

**Comment by fengqsam** [comment]
你好，想请问您LSTF的长期预测对比模型中的LSTM是sequence to sequence的模型吗？相关的baseline可以在哪里找到？

**Comment by wuhaixu2016** [comment]
您好，我们使用的是pytroch官方提供的LSTM
