### ISSUE TITLE
时序预测应用问题咨询？

### ISSUE THREAD

**Issue by lovechang1986** [thuml/Time-Series-Library#205]
您好，我想咨询一个问题，有一个时间序列，是以日为单位，但并不是每年365天都有，只有每年的5-9月有数据，类似这样的我该如何处理才能应用到您的这个开源项目中呢？

另外想了解下，是可否用于多变量（包含与单变量相关的其他变量）预测单变量时序？

**Comment by wuhaixu2016** [comment]
您好，
（1）如果数据量太少的话，可以先尝试传统方法，比如GDBT。
（2）具体可以参考‘MS’这个setting
