### ISSUE TITLE
关于TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Pupuliu** [thuml/Time-Series-Library#206]
在Exp_Long_Term_Forecast中：
                    else:
                        outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
                    
                    f_dim = -1 if self.args.features == 'MS' else 0
                    outputs = outputs[:, -self.args.pred_len:, f_dim:]
报错：Traceback (most recent call last):
  File "C:\Users\msi\PycharmProjects\Time-Series-Library-main\run.py", line 147, in <module>
    exp.train(setting)
  File "C:\Users\msi\PycharmProjects\Time-Series-Library-main\exp\exp_long_term_forecasting.py", line 138, in train
    outputs = outputs[:, -self.args.pred_len:, f_dim:]
TypeError: 'NoneType' object is not subscriptable
得到的outputs是None，进行的是单变量预测，参数--features S --data custom--seq_len 6 --label_len 1
  --pred_len 1
  --e_layers 2
  --d_layers 1
  --factor 3
  --enc_in 1
  --dec_in 1
  --c_out 1
  --d_model 16
  --d_ff 32

**Comment by wuhaixu2016** [comment]
您好，我不清楚您使用的数据集以及训练的模型。如果output是None的话，可以检查一下data loader

**Comment by Chuan112233** [comment]
可能是 task-name没有选择好 加了逗号啥的
