### ISSUE TITLE
Transformer structure

### ISSUE THREAD

**Issue by Aaronhuang-778** [thuml/Time-Series-Library#208]
Hi, author

I noticed that the decoder and generation structure of the Transformer is the same as the Informer

And I find Transformer with this decoder gains better performance

**Comment by wuhaixu2016** [comment]
Hi, applying Transformer to time series forecasting starts from Informer (correct me if I am wrong). I think the decoder-style in Informer has been a convention in this area. Thus, we follows Informer for vanilla Transformer.
