### ISSUE TITLE
Attention heads support hardcoded to size 8 in FEDformer

### ISSUE THREAD

**Issue by khairulislam** [thuml/Time-Series-Library#209]
Hi, 
In the `FourierCrossAttention` and also in `FourierBlock` the weights are initialized like the following
> self.weights1 = nn.Parameter(self.scale * torch.rand(8, in_channels // 8, out_channels // 8, len(self.index), dtype=torch.float))

This throws an error for any head size except 8.

**Comment by wuhaixu2016** [comment]
Hi, thanks for your great suggestion. We have resolved this problem in the latest commit: https://github.com/thuml/Time-Series-Library/commit/0a99aa0f4d4c2271f56432f957e3f64a5f5d2ca5
