### ISSUE TITLE
experiment results

### ISSUE THREAD

**Issue by oubahe** [thuml/Time-Series-Library#21]
楼主，我这边使用CUDA 11.4和pytorch1.11.0+cu115，按照script配置得到的测试结果略优于FEDformer，差于DLinear，无法匹配paper中的测试结果，请问是运行环境和torch版本的原因吗？

**Comment by wuhaixu2016** [comment]
您好，可以使用pytorch 1.7.1. 具体请见https://github.com/thuml/Time-Series-Library/issues/12
