### ISSUE TITLE
inverse_transform修改后仍然存在问题

### ISSUE THREAD

**Issue by JieDengsc** [thuml/Time-Series-Library#213]
你好，我这边按照你对inverse_transform的修复进行了修改，但是发现仍然报错，显示的是scaler本身是一个batch_size*enc_in维度的输入才行，所以想请问你这部分如何处理呢？

output operand with shape (64,1) doesn't match the broadcast shape (64,16)

**Comment by JieDengsc** [comment]
更新：按照每个feat_id分别选择对应的mean_、scale_进行inverse_transform

**Comment by XQFXueQiFan** [comment]
> 更新：按照每个feat_id分别选择对应的mean_、scale_进行inverse_transform

可以具体讲讲吗？我也遇到了同样的问题

**Comment by JieDengsc** [comment]
> > 更新：按照每个feat_id分别选择对应的mean_、scale_进行inverse_transform
> 
> 可以具体讲讲吗？我也遇到了同样的问题

我是将data_loader中的__getitem__的feat_id保存下来，就能知道每个序列对应的feat_id是多少。 随后在test()中，读取归一化的权重scaler，能够得到每个feat_id下的mean、std，分别针对每个pred进行反归一化即可
