### ISSUE TITLE
How is the model performance evaluated?

### ISSUE THREAD

**Issue by jerrywn121** [thuml/Time-Series-Library#214]
I see that you provide rankings for different models in the leaderboard. Would you provide the methods you use (metrics and datasets?) to evaluate their performance?

As far as I know, many comparisons made between models in the literature (autoformer, patchtst ...) train all models using the same hyperparameters without using any model-specific parameters, nor do they tune hyperparameters for each model, which may lead to potentially wrong conclusions regarding model performances. I wonder if you take this (separately tune individual model's hyperparameters) into account while evaluating different models?

**Comment by wuhaixu2016** [comment]
Hi, as we stated in the README.md, the leaderboard is from our paper TimesNet (https://openreview.net/pdf?id=ju_Uqw384Oq) and iTransformer (https://arxiv.org/abs/2310.06625). You can find the full results from these papers.

To ensure a fair comparison, we fix the forecasting setting (especially input length and predict length) for each benchmark. 

It is notable that different models will present different hyperparameter sensitivity. To eliminate this bias, we conduct a comprehensive hyperparameter search for each model. Thus, you can take the results as the comparison between upper bounds of different models.
