### ISSUE TITLE
Why use CorrAttention in iTransformer?

### ISSUE THREAD

**Issue by somaonishi** [thuml/Time-Series-Library#215]
Thank you very much for the quick implementation.
Looking at the [original paper](https://arxiv.org/abs/2310.06625) and the [author implementation](https://github.com/lucidrains/iTransformer) on iTransformer, I believe you are using Vanila-Attention (named FullAttention in your code).
Why do you use CorrAttention in your implementation?
Best regards

PS
The author's implementation does not normalize the input (`Normalization from Non-stationary Transformer`), why does your implementation do it?

**Comment by ZDandsomSP** [comment]
Thank you for your comment. CorrAttention is a early component of our method, and we have verified its consistency with Self Attention through experiments. We have verified its consistency with Self Attention through experiments soon.
Additionally, it may be necessary to clarify that we are the official implementation of this model. As for `Normalization from Non-stationary Transformer`, we have used it as a basic method for model development in long-term research, and we have equivalently used it in the main table experiment of our paper (as mentioned in our paper)
<img width="825" alt="comment" src="https://github.com/thuml/Time-Series-Library/assets/88132465/85885003-8034-41c2-af89-662eb9186306">

Thank you again for your comment!
