### ISSUE TITLE
How do you draw the nice radar graph in the paper iTransformer?

### ISSUE THREAD

**Issue by lartpang** [thuml/Time-Series-Library#220]
@wuhaixu2016 

![1697723565953](https://github.com/thuml/Time-Series-Library/assets/26847524/e8505675-d2d6-4ab4-9128-944dc303458e)

I'm very curious about this because this radar chart does look good!

**Comment by wuhaixu2016** [comment]
Hi, we just use the [Matplotlib](https://matplotlib.org/).
