### ISSUE TITLE
imputation 任务中标准化和 mask 的顺序问题

### ISSUE THREAD

**Issue by zfbz** [thuml/Time-Series-Library#221]
非常感谢时序代码库！
我看见代码里关于时序插补任务的做法，是在进入 model 前生成 random mask，mask 掉的位置补 0。
但是在 mask 之前，数据已经做了特征标准化，这是否有影响？是否算数据泄露？
是不是应该先 mask 后再做标准化？
还是从统计角度解释，这些数据特征都是服从一定分布的，所以不太影响？
期待回复，感谢！

**Comment by wuhaixu2016** [comment]
您好，感谢关注和宝贵建议，您提到的z-score normalization从原理上确实应该在mask之后再做，不过正如您所说，因为数据特征服从统一分布，所以在mask前后计算出来的mean和std非常接近，不会对最终结果有影响。
