### ISSUE TITLE
关于long-term 任务中的M Feature

### ISSUE THREAD

**Issue by lqf0624** [thuml/Time-Series-Library#222]
你好！关于脚本中的Features，有三种模式，M，MS和S。根据注释，M Feature的意思是用多变量预测多变量，比如weather任务是一个M Feature的，但是weather.csv中只有一项OT，可否解释一下，这其中的多变量预测多变量体现在哪？

**Comment by wuhaixu2016** [comment]
您好，请见超参数c_out的设置，如果是M，enc_in=c_out
