### ISSUE TITLE
关于分类任务的疑问

### ISSUE THREAD

**Issue by soulZhaoL** [thuml/Time-Series-Library#230]
你好，我在接触timesNet后有几个疑问，烦请解答
       我在尝试使用TimesNet做自定义数据集的分类任务。我一直使用的是csv文件做回归任务，第一次接触分类。我发现scripts里关于分类任务的数据集都是ts文件，我应该如何使用我自己的csv文件去做分类？请给出一些指点，感谢！

**Comment by wuhaixu2016** [comment]
您好，具体可以参考Data_Custom重新编写dataloader：https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L196

**Comment by kirathes** [comment]
> 你好，我在接触timesNet后有几个疑问，烦请解答 我在尝试使用TimesNet做自定义数据集的分类任务。我一直使用的是csv文件做回归任务，第一次接触分类。我发现scripts里关于分类任务的数据集都是ts文件，我应该如何使用我自己的csv文件去做分类？请给出一些指点，感谢！

您好，请问您实现csv文件转换为ts文件了吗?如果实现了，不知您是否愿意分享代码呢?非常感谢😉

**Comment by xiyangyang99** [comment]
> > 你好，我在接触timesNet后有几个疑问，烦请解答 我在尝试使用TimesNet做自定义数据集的分类任务。我一直使用的是csv文件做回归任务，第一次接触分类。我发现scripts里关于分类任务的数据集都是ts文件，我应该如何使用我自己的csv文件去做分类？请给出一些指点，感谢！
> 
> 您好，请问您实现csv文件转换为ts文件了吗?如果实现了，不知您是否愿意分享代码呢?非常感谢😉

我这点有csv转ts的。
