### ISSUE TITLE
Long-term Forecasting with TiDE: Time-series Dense Encoder

### ISSUE THREAD

**Issue by willxxy** [thuml/Time-Series-Library#237]
Do you have any plans to implement this paper ["Long-term Forecasting with
TiDE: Time-series Dense Encoder"](https://arxiv.org/pdf/2304.08424.pdf). There seems to be an implementation [here](https://github.com/lich99/TiDE) but I would love to see it integrated into this library!

**Comment by wuhaixu2016** [comment]
Hi, we have added this model: https://github.com/thuml/Time-Series-Library/blob/main/models/TiDE.py
