### ISSUE TITLE
在 exp_long_term_forecasting.py 中的 test 方法中，参数 label_len 是不是在预测过程中没有起到作用？

### ISSUE THREAD

**Issue by KK-wang** [thuml/Time-Series-Library#246]
作者你好，我最近在使用 TimesNet 做时序预测，在学习源码的时候，遇到一个问题。

我的执行命令所携带的参数如下：

```bash
--task_name
long_term_forecast
--is_training
0
--root_path
./dataset/Huawei/
--data_path
work-day.csv
--model_id
Huawei-work
--model
TimesNet
--data
custom
--features
S
--seq_len
100
--label_len
48
--pred_len
10
--e_layers
2
--d_layers
1
--factor
3
--enc_in
1
--dec_in
1
--c_out
1
--d_model
32
--d_ff
32
--top_k
5
--des
Exp
--itr
1
--target
value
--freq
t
--use_multi_gpu
```
按照代码流程，其会执行到 exp_long_term_forecasting.py 的 test() 方法，test() 方法中用于预测的代码为 outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)，它最终由 TimesNet.py 中的 forecast() 方法执行，我看该方法中的后两个参数没有被用到，也就是说 test() 方法中的 dec_inp 和 batch_y_mark 没有被用到，这二者的由来和 label_len 相关，这是否意味着在调用exp_long_term_forecasting.py 中的 test 方法时，参数 label_len 在预测过程中没有起到作用？即 label_len 不会影响到预测结果，而是 seq_len 能够影响到预测结果。

烦请作者解答，不胜感激。

**Comment by wuhaixu2016** [comment]
您好，label len确实没有用到，这个参数只在Transformer的系列模型中被用到。

**Comment by KK-wang** [comment]
> 您好，label len确实没有用到，这个参数只在Transformer的系列模型中被用到。

好的，我了解了，在 TimesNet 中没有被用到，那请问在 ITransformer 和 PatchTST 中有用到吗？

**Comment by Songyihu** [comment]
> > 您好，label len确实没有用到，这个参数只在Transformer的系列模型中被用到。
> 
> 好的，我了解了，在 TimesNet 中没有被用到，那请问在 ITransformer 和 PatchTST 中有用到吗？

应该是只有在用到decoder的Transformer模型中才会被用到，例如informer
