### ISSUE TITLE
超参数问题

### ISSUE THREAD

**Issue by qiu69** [thuml/Time-Series-Library#247]
![image](https://github.com/thuml/Time-Series-Library/assets/82441982/2f77b621-7dd9-48d0-b032-7b54bff908e2)

![image](https://github.com/thuml/Time-Series-Library/assets/82441982/2a4dca57-6a61-4010-85db-b5ac277f2f17)

请问每一个sh脚本里面的超参数结合run.py里面的超参数，是不是就是你们认为的（或者你们测试过程中发现的）某个算法在某个数据集上面性能表现最好的超参数组合？

**Comment by wuhaixu2016** [comment]
您好，对于不同的论文，我们会做适当的超参数搜索以达到官方论文报的结果，但是不一定是最优参数。
