### ISSUE TITLE
关于reshape

### ISSUE THREAD

**Issue by hljuniversity** [thuml/Time-Series-Library#25]
您好，作者，感谢您的TimesNet网络，看了您的论文，我想问一下。对于一个T×C 的时间序列，在进行reshape时，是将C整体来进行reshape，还是将C分开，分别对 C1、C2...Cn 进行reshape？（比如脑电信号这种横轴为时间点，纵轴是不同通道的时间序列）

**Comment by wuhaixu2016** [comment]
您好，可以看一下代码，是整体来reshape的。这是因为当使用value embedding将原始数据映射至特征空间之后，特征的各个channel是等价的，所以也就没有区分不同的变量。
