### ISSUE TITLE
Adding Contributors section to the readme.md 

### ISSUE THREAD

**Issue by mohitd404** [thuml/Time-Series-Library#250]
Why Contributors section:- A "Contributors" section in a repo gives credit to and acknowledges 
the people who have helped with the project, fosters a sense of community, and helps others
 know who to contact for questions or issues related to the project.

**Issue type**
- [✅] Docs

Expected output :- 
![3](https://github.com/thuml/Time-Series-Library/assets/146939900/db110b18-0680-4e87-a2a9-1e5651559477)

@wuhaixu2016  kindly assign this issue to me ! I would love to work on it ! Thank you !

**Comment by wuhaixu2016** [comment]
Hi, thanks for your effort. I have merged your pull request.
