### ISSUE TITLE
.ts数据集问题

### ISSUE THREAD

**Issue by jianlaigeng** [thuml/Time-Series-Library#252]
您好作者大大，想问一下您那有时间序列分类中.csv的数据集吗？我想看一下您这个数据集是什么样的，但是这个.ts的数据集看不了

**Comment by wuhaixu2016** [comment]
您好，具体的数据集文件地址从论文中找到，都已经给了对应的引用。

**Comment by jianlaigeng** [comment]
> 您好，具体的数据集文件地址从论文中找到，都已经给了对应的引用。

好的谢谢您的回复
