### ISSUE TITLE
Koopa的预测效果

### ISSUE THREAD

**Issue by hhr114** [thuml/Time-Series-Library#255]
Koopa在Long-term Forecasting任务上的表现能否上榜？README没有更新排名，是说明Koopa的表现不如TimesNet和iTransformer吗？这和Koopa原论文中的结果不相符？

**Comment by wuhaixu2016** [comment]
您好，请仔细阅读readme.md，koopa模型我们没有进行大规模测试，所以咱们没有加入榜单进行比较

**Comment by CSyyn** [comment]
我测试了Koopa模型，结果与iTransformer的实验结果不相上下，指标都挺好的
