### ISSUE TITLE
backward prediction issue

### ISSUE THREAD

**Issue by gauridargar** [thuml/Time-Series-Library#256]
![Screenshot from 2023-10-30 13-13-26](https://github.com/thuml/Time-Series-Library/assets/74265612/9109fe73-7b28-456f-9e8f-fb543540c0d1)
I tried to run the iTransformer model o my custom dataset which contains hourly footfall count of three months i got multiple graphs like these which are predicting in backward time how to resolve it ? and how to take the trained model to predict for future unseen data

**Comment by wuhaixu2016** [comment]
Hi, you need a predict function. You may find this helpful: https://github.com/thuml/Autoformer/blob/main/exp/exp_main.py#L242.
