### ISSUE TITLE
是否能够将谷歌的与Transformer模型对比的TSMixer: An all-MLP architecture for time series forecasting 模型纳入本库中呢？

### ISSUE THREAD

**Issue by weituo2002** [thuml/Time-Series-Library#260]
谷歌的新模型TSMixer: An all-MLP architecture for time series forecasting在DLinear模型的基础上进一步用于和Transformer时间序列预测的基线进行比较，能否将该模型纳入到本库这个统一的框架中方便进行一些性能对比呢？

**Comment by zzrsheep** [comment]
这个应该还没开源

**Comment by wuhaixu2016** [comment]
您好，感谢建议，我们在ICLR2024最新接收的论文中对比了TSMixer，如果您想看到效果对比的话，可以参考：https://openreview.net/forum?id=7oLshfEIC2

未来我们也会把更多的线性模型加入算法库中。
