### ISSUE TITLE
fft function no attribute "rfft" and "rfftfreq"

### ISSUE THREAD

**Issue by Conliq** [thuml/Time-Series-Library#262]
When I read ETSformer_EncDec.py, it says function no attribute "rfftfreq", I can't run ETSformer this time.
When I read TimesNet.py, it says function no attribute "rfft", but I can run TimesNet.

I found the following instructions on the official website: 
As mentioned, PyTorch 1.8 offers the torch.fft module, which makes it easy to use the Fast Fourier Transform (FFT) on accelerators and with support for autograd. We encourage you to try it out!
(from https://pytorch.org/blog/the-torch.fft-module-accelerated-fast-fourier-transforms-with-autograd-in-pyTorch/)

So I wante to ask which version of pytorch to use?

**Comment by wuhaixu2016** [comment]
Our repo is built on the torch 1.7.1.
Thanks for your advice.  We are going to upgrade our library.
