### ISSUE TITLE
大神们效果咋样，为啥我的效果都不咋地，难道是我 pytorch 版本2.1.0导致的

### ISSUE THREAD

**Issue by Vector-Cross** [thuml/Time-Series-Library#263]
一定要装 torch==1.7.0吗，我默认的baseline跑的都是这样的效果，有没大佬成功了的呀
![image](https://github.com/thuml/Time-Series-Library/assets/36829977/1851edc6-b9e0-4b57-a89f-fd50b2902982)

**Comment by Gczmy** [comment]
最好描述一下你所用的模型、数据集和任务（task, feature）
我用的torch==2.1.0，效果还可以

**Comment by wuhaixu2016** [comment]
您好，官方版本为pytorch 1.7.1
