### ISSUE TITLE
Support Temporal Fusion Transformer

### ISSUE THREAD

**Issue by blackvvine** [thuml/Time-Series-Library#265]
Hi, thank you for all the great work in this library. Are there any plans to support [Temporal Fusion Transformers](https://www.sciencedirect.com/science/article/pii/S0169207021000637)? (Lim et al, 2021)

**Comment by petartushev** [comment]
On another note, does anyone know how TFT compares performance wise to the models on the leaderboard?

**Comment by wuhaixu2016** [comment]
Hi, we have included TFT. Please see: https://github.com/thuml/Time-Series-Library/blob/main/models/TemporalFusionTransformer.py
