### ISSUE TITLE
寻找周期的问题

### ISSUE THREAD

**Issue by jianlaigeng** [thuml/Time-Series-Library#268]
period = x.shape[1] // top_list   作者大大我想问一下为什么，时间序列的长度除以频率的索引值等于周期呢

**Comment by weituo2002** [comment]
@jianlaigeng 请问一下可以在哪个模型用什么方法得到频率啊

**Comment by wuhaixu2016** [comment]
您好，FFT结束之后得到一个张量，张量的第i个数值表示频率为i的周期函数的振幅，所以我们用fft结果的数值来筛选振幅最大的频率，以索引值去确定具体周期是多少。

**Comment by jianlaigeng** [comment]
> 您好，FFT结束之后得到一个张量，张量的第i个数值表示频率为i的周期函数的振幅，所以我们用fft结果的数值来筛选振幅最大的频率，以索引值去确定具体周期是多少。
感谢您的回答，但是在下愚钝还是没理解为什么时间序列的长度除以最大振幅所对应的频率的索引值就是近似周期的长度，这是有什么基础知识的原理吗？

**Comment by jianlaigeng** [comment]
> @jianlaigeng请问一下可以在哪个型号用什么方法得到频率啊
没明白您说的这个型号是什么意思，作者是通过傅里叶变换得到的频率
