### ISSUE TITLE
Why test_loader use batchsize=1

### ISSUE THREAD

**Issue by NEUCMD** [thuml/Time-Series-Library#269]
`  if flag == 'test':
        shuffle_flag = False
        drop_last = True
        if args.task_name == 'anomaly_detection' or args.task_name == 'classification':
            batch_size = args.batch_size
        else:
            batch_size = 1  # bsz=1 for evaluation
        freq = args.freq`
I am wonder this setting

**Comment by wuhaixu2016** [comment]
Hi, this design is to mimc the online serving scenario.
If you have a online model, you can use this configuration. But if you propose a normal forecasting model, you can just increase this number.
