### ISSUE TITLE
长时预测时，预测结果与真实值相比有偏移的现象

### ISSUE THREAD

**Issue by Gczmy** [thuml/Time-Series-Library#270]
你好，我在进行长时预测（long_term_forecast）时，发现预测结果与真实值相比有偏移的现象。

我的数据是月度数据，目的是使用过去3个月的值去预测未来1个月值，即1_month_ahead，然后重新划分训练集，使用过去3个月的值去预测未来2个月的值，但是我仍只预测一个值，即跳过了未来一个月的值。在这种方案下，我设置最大预测6个月，训练6次，得到6次结果。(代码中`seq_len=3`, `label_len=0`, `pred_len=1`且固定，每次预测重新引入新参数`pred_time_ahead`并以此重新划分训练集)

在使用TimesNet，iTransformer，PatchTST等包含在库中的算法时，总是会出现结果偏移的现象而且偏移的距离随着预测时间的增加而变大（预测1个月时是1，预测6个月则偏差为6），但是我使用LSTM则没有这种现象，请问能提供任何可行的思路吗？

如下图是TimesNet在预测6个月时的结果对比：
![image](https://github.com/thuml/Time-Series-Library/assets/20588674/24a5c866-4305-4f48-81c8-25a346381e36)
下图是LSTM在预测6个月时的结果对比：
![output5](https://github.com/thuml/Time-Series-Library/assets/20588674/3f47c168-2e09-4bbe-aa7b-bc6da5763048)

**Comment by wuhaixu2016** [comment]
您好，感谢使用，我没有懂你的使用方法。但是我觉得这种偏移现象的出现需要仔细检查一下temporal embedding。

**Comment by Gczmy** [comment]
> 你好这个问题解决了吗？我也出现明显偏移的情况：
> 用自己的数据尝试训练了itransformer 完成了Long-termForecasting任务，features为MS类型，数据间隔为每15分钟，freq设置为“t”，但是我在plot 项目result文件夹中的预测结果时，图像发生了偏移。详细如下，翻了历史的issue也对temporal embedding进行了调整发现仍然有这种问题。辛苦您能给我指点下问题，非常感谢。
> 
> plt.plot(trues[:,0,-1].reshape(-1)[-50:], label='GroundTruth')
> plt.plot(preds[:,0,-1].reshape(-1)[-50:], label='Prediction')
> ![image](https://github.com/thuml/Time-Series-Library/assets/13030876/cf2b28e7-5f4b-4fd9-a84b-ee9263c14ccc)
> 
> 
> 如果对preds中结果进行人工偏移发现拟合的还不错，不知道问题出在哪里？
> plt.plot(trues[:,0,-1].reshape(-1)[-50:], label='GroundTruth')
> plt.plot(preds[:,0,-1].reshape(-1)[-49:], label='Prediction')
> ![image](https://github.com/thuml/Time-Series-Library/assets/13030876/e5e7bbd3-34e3-41d0-9845-b4b2acaff2e4)
> 
> 
> > 你好，我在进行长时预测（long_term_forecast）时，发现预测结果与真实值相比有偏移的现象。
> > 
> > 我的数据是月度数据，目的是使用过去3个月的值去预测未来1个月值，即1_month_ahead，然后重新划分训练集，使用过去3个月的值去预测未来2个月的值，但是我仍只预测一个值，即跳过了未来一个月的值。在这种方案下，我设置最大预测6个月，训练6次，得到6次结果。(代码中`seq_len=3`, `label_len=0`, `pred_len=1`且固定，每次预测重新引入新参数`pred_time_ahead`并以此重新划分训练集)
> > 
> > 在使用TimesNet，iTransformer，PatchTST等包含在库中的算法时，总是会出现结果偏移的现象而且偏移的距离随着预测时间的增加而变大（预测1个月时是1，预测6个月则偏差为6），但是我使用LSTM则没有这种现象，请问能提供任何可行的思路吗？
> > 
> > 如下图是TimesNet在预测6个月时的结果对比： ![image](https://private-user-images.githubusercontent.com/20588674/281870148-24a5c866-4305-4f48-81c8-25a346381e36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NzI2MjgsIm5iZiI6MTcwODU3MjMyOCwicGF0aCI6Ii8yMDU4ODY3NC8yODE4NzAxNDgtMjRhNWM4NjYtNDMwNS00ZjQ4LTgxYzgtMjVhMzQ2MzgxZTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDAzMjUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZDI1ODI2NDBjNjcxYzY0MWRkODgzYzkyMmZmOWQ4N2U5Nzk3ZjUyZjJlNzgwOTA5MDg1ODkwZjM3YjBmZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tmvZcOxM1od-61SMULzW431shmp5Bc4dwnajq4WHfYU) 下图是LSTM在预测6个月时的结果对比： ![output5](https://private-user-images.githubusercontent.com/20588674/281870447-3f47c168-2e09-4bbe-aa7b-bc6da5763048.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NzI2MjgsIm5iZiI6MTcwODU3MjMyOCwicGF0aCI6Ii8yMDU4ODY3NC8yODE4NzA0NDctM2Y0N2MxNjgtMmUwOS00YmJlLWFhN2ItYmM2ZGE1NzYzMDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDAzMjUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNGVlM2UwNmIxMGIzNDIyNTAxZGVhMzE2ZTc5NGY1MGE3MTVhMWU3YjU4MzM0MzZiMjQwNjI5YjM2Njg5NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fAuGK2G7M3qZfmRHukbKRlzgp5ipCtipXIGBC4CgOzc)
> 
> 

试一下把模型代码forward函数里的NSformer的encoder和decoder注释掉有没有改善。作者在这个库里为大多数模型都添加了这个操作增强对非平稳序列的预测能力，但是对我的方法会有影响，我去掉之后偏移现象就好多了。
