### ISSUE TITLE
Error related to conv_kernel in MiCN ILI_script 

### ISSUE THREAD

**Issue by FarahSaeed** [thuml/Time-Series-Library#271]
Hi,

Thanks for the code and library. Regarding the ILI_Script, when running MiCN using this script [ILI_script](https://github.com/thuml/Time-Series-Library/tree/main/scripts/long_term_forecast/ILI_script)
/MICN.sh. 

It shows that the --conv_kernel 18 12 is unrecognized argument. Should I erase this argument from file. 

Thanks a lot.

**Comment by wuhaixu2016** [comment]
Hi, sorry for this bug. We have deleted this line in the latest commit.
