### ISSUE TITLE
FEDformer中的MOEDecomp分解模块没有使用？

### ISSUE THREAD

**Issue by liujian123223** [thuml/Time-Series-Library#272]
好像FEDformer.py文件中的init函数部分使用的是autoformer中的分解函数，没有使用论文提出的MOEDecomp模块？不知道我是否弄错了，希望指点一下

**Comment by wuhaixu2016** [comment]
您好，感谢指出，从效果上开，简单的分解函数和MOEDecomp差别不大，所以没有实现这个block。

**Comment by liujian123223** [comment]
谢谢，我是看到论文中提到了这个模块的优势，因此提了一下，感谢您的回复



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月11日(周六) 中午12:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [thuml/Time-Series-Library] FEDformer中的MOEDecomp分解模块没有使用？ (Issue #272)




 
您好，感谢指出，从效果上开，简单的分解函数和MOEDecomp差别不大，所以没有实现这个block。
