### ISSUE TITLE
TimesNet 论文中报告的结果具体是怎么计算的

### ISSUE THREAD

**Issue by zfbz** [thuml/Time-Series-Library#273]
您好，我想知道 TimesNet 论文中报告的结果具体是怎么得来的。
1. 我只关注 **分类** 这个任务，我试了不同种子跑，结果差挺多的。我看到其他 issue 中回复是 **5 个种子的平均结果**（吴大佬还说是标准做法），但是 TimesNet 这篇论文中附录 A 说的是**所有实验重复了 3 次**，如何重复 3 次？论文上展示的是平均结果吗？所以想知道到底是怎么样得到的，标准做法到底是怎么样的？
2. 分类任务我认为一般都是要多个种子去跑然后取平均的，但是此类论文上一般很少有说明他们的实验结果有没有重复做然后平均，而且为什么不去展示出 acc 的 std？于是我自己也做了实验不同种子跑 10 个结果，std 也蛮大的，以 % 为单位，得到 **std 为 1.2 %** 左右。然后看到 TimesNet 论文中的 **表17** 表名写“The standard deviation is within 0.1%.”，不是很能理解是什么的 standard deviation (std)？某个模型的、某个数据集的？整个表的结果都在这个 std 范围内（我觉得不太可能呀）？

十分期待作者的回复！Thanks♪(･ω･)ﾉ

**Comment by wuhaixu2016** [comment]
您好，感谢关注
（1）标准做法是n个随机种子，一般来说3-5个都是可以的，在TimesNet的论文中我们是用不同的随机种子跑了三次实验，论文给出的是平均值。
（2）论文表17的standard deviation指的是TimesNet在10个子数据集上的平均准确率的标准差。
