### ISSUE TITLE
M4 training scripts are not repoducible

### ISSUE THREAD

**Issue by eepishin** [thuml/Time-Series-Library#274]
@dataclass()
class M4Dataset:
    ids: np.ndarray
    groups: np.ndarray
    frequencies: np.ndarray
    horizons: np.ndarray
    values: np.ndarray

    @staticmethod
    def load(training: bool = True, dataset_file: str = '../dataset/m4') -> 'M4Dataset':
        """
        Load cached dataset.

        :param training: Load training part if training is True, test part otherwise.
        """
        info_file = os.path.join(dataset_file, 'M4-info.csv')
        train_cache_file = os.path.join(dataset_file, 'training.npz')
        test_cache_file = os.path.join(dataset_file, 'test.npz')
        m4_info = pd.read_csv(info_file)
        return M4Dataset(ids=m4_info.M4id.values,
                         groups=m4_info.SP.values,
                         frequencies=m4_info.Frequency.values,
                         horizons=m4_info.Horizon.values,
                         values=np.load(
                             train_cache_file if training else test_cache_file,
                             allow_pickle=True))

executing load method of M4Dataset poduces the following error: FileNotFoundError: [Errno 2] No such file or directory: './dataset/m4/raining.npz'

**Comment by wuhaixu2016** [comment]
Hi, we have not come across this problem. 
According to the log, you need to download the m4 dataset and place it under the right path.
