### ISSUE TITLE
Datasets and VRAM

### ISSUE THREAD

**Issue by ptsialis** [thuml/Time-Series-Library#278]
Dear authors of Tsinghua University. Thank you for your outstanding contributions, especially with regard to Time Series. I find this time series library incredibly helpful and useful. But I have a few questions, one is why do you only use about 6-8 data sets in your papers? When reading through Timesnet, iTransformer and Autoformer I noticed that you only use a few data sets. Wouldn't it be better to use more data sets to generalize the model, especially for Transformer models? Or is it because you are limited by computing power? 
Another question would be how much VRAM did you have available for training and how much would you recommend to use? I am planning to fine tune a model for imputation for my master thesis.

Kind regards,
Petros Tsialis

**Comment by wuhaixu2016** [comment]
Hi, actually these 6-8 datasets are conventional in this area. The well-acknowledged papers, Autoformer and Informer, all experiment on these datasets. In TimesNet, we extend the downstream tasks into imputation, classification and anomaly detection, where 10 more benchmarks are employed.

Usually, one single GPU or even CPU are enough for the forecasting tasks. But for the high-level analysis tasks, such as classification and detection, you will need a last one 3090 RTX GPU.
