### ISSUE TITLE
关于Scripts中各模型的运行脚本文件

### ISSUE THREAD

**Issue by Diroooomy** [thuml/Time-Series-Library#279]
在脚本文件中包含了各个模型对各个数据集的运行命令
请问这些命令中所携带的超参是当前模型对应数据集上的最佳超参吗，或者说论文里表格所得到的数据是由这些命令得来的吗

**Comment by wuhaixu2016** [comment]
您好，我们自己的工作是论文中的实验脚本。但是别人的工作是经过超参数搜索过的，目标为尽可能复现相关工作。

**Comment by Diroooomy** [comment]
thanks for reply😊

**Comment by Diroooomy** [comment]
thanks for reply😊
