### ISSUE TITLE
Multivariate Predict Multivariate(M) vs Multivariate Predict Univariate (MS)

### ISSUE THREAD

**Issue by Sanjeev97** [thuml/Time-Series-Library#28]
I only changed M into MS in --features and ran it. It runs but not sure if it is the correct way. Do we also have to change --dec_in and --c_out to 1? Can you give an example on how to run the Autoformer for MS setting? Also, please provide an explanation to these settings.

**Comment by wuhaixu2016** [comment]
Hi, you can just change M to MS and don't need to change the c_out.
Please see line 65 of https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_long_term_forecasting.py
