### ISSUE TITLE
Is  .ts file in dataset be aeon ts format?  how to convert to .ts from .csv file ?

### ISSUE THREAD

**Issue by david-95** [thuml/Time-Series-Library#280]
数据文件 .ts 是 用到aeon ts 格式么？ 有没有现成的工具能把 .csv 转化为 .ts ?

**Comment by wuhaixu2016** [comment]
您好，.ts是sktime中默认的数据格式，您可以在这里找到说明https://www.sktime.net/en/stable/examples/data/loading_data.html
