### ISSUE TITLE
About the metrics of iTransformer in long-term forecasting task.

### ISSUE THREAD

**Issue by Diroooomy** [thuml/Time-Series-Library#284]
![image](https://github.com/thuml/Time-Series-Library/assets/46437227/0a2ad43f-ba0e-4eb9-a93e-f6f84d6518d0)
对于iTransformer的长期序列预测结果，表格中的ETT数据集代表的是library中的哪一个？
结合脚本文件来看是不是只代表了ETTh2

**Comment by hughxx** [comment]
看其他模型的实验结果是取的ETTh2
