### ISSUE TITLE
模型部署

### ISSUE THREAD

**Issue by HuntZhaozq** [thuml/Time-Series-Library#288]
作者您好，TimesNet等模型在公开数据集上的性能很好，我有几个问题想请教下：
1.在实际应用中，如何将类似的模型进行部署，基于历史数据训练一个模型，就能根据前面时刻，不断地来预测后面时刻的趋势吗？
2.模型如何进行实时的更新？且数据量越大，模型重新训练的时间会很长，请问有什么方法吗？
3.您关于冬奥会天气预报的工作，我看是一次性的预测（只预测了一次），如何进行连续的预测且保证准确度呢？

**Comment by wuhaixu2016** [comment]
您好，感谢关注。
（1）实际应用中，需要首先根据过去数据训练模型，然后不断接收新数据作为模型输入，从而预测未来。
（2）您说的实时更新，属于online learning的范畴，即通过源源不断的数据更新模型。但是这是一个独立的方向，我们这个算法库暂时不支持这个功能。
（3）冬奥会的工作是训练模型之后，不断根据新的数据多次预测未来，具体可以参考算法库中模型evaluation的部分，即以滑动窗口的形式接收新信息来预测未来。
