### ISSUE TITLE
Cannot Reproduce iTransformer performance on the ETT dataset

### ISSUE THREAD

**Issue by Neehan** [thuml/Time-Series-Library#290]
Here's the colab notebook: https://colab.research.google.com/drive/1FVMeGa_Cpfgb75aoZRXsbHsJmsTzYWZN#scrollTo=kYfgCwTvnSv2&uniqifier=1

The predicted performance is way off from what is reported on the paper.

**Comment by ZDandsomSP** [comment]
Hello, there may be two possible reasons for the phenomenon you mentioned:
Firstly, the torch version of tslib is different from the version of iTransformer, which may lead to random changes in the training process. Secondly, tslib does not provide parameter adjusted iTransformer training scripts. You can try to replicate the results of the article in the [official iTransformer repository](https://github.com/thuml/iTransformer).
Thank you again for your feedback!
