### ISSUE TITLE
iTransformer中的PEMS03数据集应该如何使用

### ISSUE THREAD

**Issue by hughxx** [thuml/Time-Series-Library#291]
您好，请教一下iTransformer中的PEMS03数据集应该如何使用，我从所引用的原始文献即SCINet仓库中下载到的数据格式为.npz，但似乎无法直接拿来使用，应该如何正确使用

**Comment by wuhaixu2016** [comment]
您好，请见他的官方代码：https://github.com/thuml/iTransformer/tree/main/scripts/multivariate_forecast/Pems
