### ISSUE TITLE
Comparison with results from original M4 participants?

### ISSUE THREAD

**Issue by cbergmeir** [thuml/Time-Series-Library#293]
You state on your leaderboard that TimesNet is the best for "short-term forecasting", which I take means the best on the M4 dataset? Your TimesNet paper reports an OWA of 0.851 for your method and of 0.855 for NBEATS.

The M4 was won by a method with an OWA of 0.821, see Table 4 in:

Makridakis, S., Spiliotis, E., & Assimakopoulos, V. (2020). The M4 Competition: 100,000 time series and 61 forecasting methods. International Journal of Forecasting, 36(1), 54-74.

Also, NBEATS reported in their original paper OWAs way better, namely 0.795, see:

https://arxiv.org/pdf/1905.10437.pdf

I'm wondering where these differences come from? Are you using a subset of the M4 only, for example?

**Comment by cbergmeir** [comment]
What about the original participants in the M4 then?

**Comment by wuhaixu2016** [comment]
Note that different from competition, for research, a fair comparison is essential. Without fair comparison, we cannot obtain any scientific conclusions.

If you try to apply TimesNet to M6 or other competitions, you can also employ the ensemble strategy to TimesNet like N-BEATS. But for us and this repo, as we stated in the README.md, this repo is to provide a clean code base for researchers. We still insist the single-model comparison configuration.
