### ISSUE TITLE
Can we have implementation demos for some basic DL models, such as MLP, LSTM, GRU?

### ISSUE THREAD

**Issue by jianzuo** [thuml/Time-Series-Library#296]
Hi,
Recently I am starting to use this library to implement prediction models on my own dataset.
I have encounted difficulties in adapting to the framework to some basic models like MLP.

Can we have some basic demos for these models? This might be helpful for beginners to better
understand and use the library. 
Thank you very much!

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interest.
We built this repo to organize and benchmark advanced deep models. You can obtain the code of LSTM and GRU from PyTorch official code. 

As for MLP model, you may find Dlinear helpful. Dlinear is just a simple MLP model but utilizes the decomposition in Autoformer. Here is the code (https://github.com/thuml/Time-Series-Library/blob/main/models/DLinear.py).
