### ISSUE TITLE
'FileNotFoundError': 运行short-term预测的Nonstationary_Transformer_M4.sh报错

### ISSUE THREAD

**Issue by kirathes** [thuml/Time-Series-Library#297]
我已经成功运行_'scripts\short_term_forecast'_文件夹下的其他sh文件，例如Autoformer_M4.sh，TimesNet_M4.sh， Transformer_M4.sh等，但是完全同样的设置下运行Nonstationary_Transformer_M4.sh却报错**'FileNotFoundError'**
具体报错内容如下：
![image](https://github.com/thuml/Time-Series-Library/assets/39157848/c8e67c13-9727-475c-add4-25594c334748)

![image](https://github.com/thuml/Time-Series-Library/assets/39157848/1033e8b6-ca0f-4a7e-8404-e72e49b1e4dd)

感谢您的回复与解答😀

**Comment by wuhaixu2016** [comment]
您好，感谢关注。
我们在运行时没有出现这个报错，看信息应该是需要您新建一下checkpoint文件夹，或者检查模型是否被成功存储下来。
