### ISSUE TITLE
数据集获取

### ISSUE THREAD

**Issue by 1915982017** [thuml/Time-Series-Library#3]
打扰一下，由于作者的数据集在外网，我没有vpn，因此，无法获得，哪位大佬可以提供一下数据集，谢谢

**Comment by wuhaixu2016** [comment]
Please see the following links:
long-term forecast: https://cloud.tsinghua.edu.cn/d/e1ccfff39ad541908bae/
short-term forecast: https://github.com/ServiceNow/N-BEATS
Anomaly detection: https://cloud.tsinghua.edu.cn/d/9605612594f0423f891e/
Classification: https://www.timeseriesclassification.com/
