### ISSUE TITLE
关于时间序列分类

### ISSUE THREAD

**Issue by lovechang1986** [thuml/Time-Series-Library#301]
您好，非常感谢您优秀的开源工作。

这里我有个时间序列分类的问题想请教一下，如果我有1000个时间序列的样本，请问有办法实现这些样本的无监督分类，将1000个序列分为几类或者说计算不同时序直接的相似度？

**Comment by wuhaixu2016** [comment]
您好，这样的无监督分类也许可以通过对特征做聚类达到。例如首先通过TimesNet+SimMTM（https://arxiv.org/pdf/2302.00861.pdf）预训练提取序列特征，然后通过聚类获得可能的同类数据。
