### ISSUE TITLE
TimesNet的predict_linear

### ISSUE THREAD

**Issue by Zh-XY22** [thuml/Time-Series-Library#302]
作者你好，对于predict_linear，我想问一下:
1.将seq_len经过Linear得到seq_len+pred_len，代码中模型最后是截取后pred_len，是不是可以认为（seq_len+pred_len）是过去的时间+未来的时间?
2.如果是的话，那你们是否试过将最后结果截取前seq_len与输入计算一下loss，看前seq_len是否还是输入，如果不是的话那pred_len为什么是输出呢?
3.针对第二点我取前pred_len或中间随意取一段pred_len或复刻原操作取最后的pred_len长度作为预测，得到的loss几乎没区别
3.基于上述，是否可以认为（seq_len+pred_len）可以看做是内部维度d_model，那对内部维度做fft真的有意义吗？另外，这一步操作为什么论文中没有提到。

**Comment by Zh-XY22** [comment]
感谢回复，对于回复（2）（3）中”在训练时依然取末尾的pred-len作为输出，但是在测试时任意选取一段做测试，应该会得到不一样的结果。“是没有疑问的，那如果训练时扔取末尾的pred-len作为输出，测试时计算前seq_len和输入计算loss，是否能证明前seq_len不是真正意义上的输入，那后pred_len为什么可以当作输出呢？

**Comment by Et6an** [comment]
您好可以留个Email嘛？我也有这方面的疑问，想交流一下
