### ISSUE TITLE
The problem of reproduction of model results

### ISSUE THREAD

**Issue by Jackson906E** [thuml/Time-Series-Library#303]
I selected TimeNet and found that the result of ETTm2 dataset (prediction length=96) was (mse:0.124, mae:0.236) while the result in the paper was (mse:0.187, mae:0.267). I want to know why the result will be so much difference?  The random seed I use is also source code to give.

**Comment by wuhaixu2016** [comment]
Hi, according to your question, the reproduced results are better than our paper.

I think you may recheck the training process. If possible, would you please provide the training log?

**Comment by Jackson906E** [comment]
When I ran TimesNet on the ETTm1 dataset, the results were even worse than that in the paper. (Each metric is 0.1 higher than the results in the paper. e.g. for prediction length=96, (mse:0.460, mae:0.450), while the result in the paper (mse:0.338, mae:0.375) I was really confused by the results I reproduced. 
[TimesNet_ETTm1_96_96.log](https://github.com/thuml/Time-Series-Library/files/13650733/TimesNet_ETTm1_96_96.log)
I will appreciate for your clarification.

**Comment by Jackson906E** [comment]
Hi, Haixu

When I ran TimesNet on the ETTm1 dataset, the results were even worse than that in the paper. (Each metric is 0.1 higher than the results in the paper. e.g. for prediction length=96, (mse:0.460, mae:0.450), while the result in the paper (mse:0.338, mae:0.375) I was really confused by the results I reproduced.
TimesNet_ETTm1_96_96.log<https://github.com/thuml/Time-Series-Library/files/13650733/TimesNet_ETTm1_96_96.log>
I will appreciate for your clarification.

Best Regards

发件人: wuhaixu2016 ***@***.***>
日期: 星期二, 2023年12月12日 21:44
收件人: thuml/Time-Series-Library ***@***.***>
抄送: Xiang LI ***@***.***>, Author ***@***.***>
主题: Re: [thuml/Time-Series-Library] The problem of reproduction of model results (Issue #303)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hi, according to your question, the reproduced results are better than our paper.

I think you may recheck the training process. If possible, would you please provide the training log?

―

**Comment by wuhaixu2016** [comment]
Hi, Thanks for your detailed log.

I found that the printed dataset samples in your log are different from mine. Please make sure that you have used the latest version of TSlib and download the dataset from our provided Google Drive.

And here is my experiment log, which can produce the results well. 
[Uploading TimesNet_96_96.log…]()
