### ISSUE TITLE
进行long term forecasting，设置features参数为MS时，target参数无法正确选中目标数据列

### ISSUE THREAD

**Issue by yyqRua** [thuml/Time-Series-Library#305]
感谢各位前辈提供代码，但是我在学习和使用过程中似乎发现了一个问题。根据target参数的描述“target feature in S or MS task”，在进行MS task中，可以根据设定target参数来指定target feature。实际上，根据exp_long_term_forecasting.py中第126-128行：

```
f_dim = -1 if self.args.features == 'MS' else 0
outputs = outputs[:, -self.args.pred_len:, f_dim:]
batch_y = batch_y[:, -self.args.pred_len:, f_dim:].to(self.device)
```

在MS task中，模型只是将最后一列当作target feature，而不是target参数设定的那一列。
不知道是不是我的理解有误，求解答~

**Comment by CSyyn** [comment]
可以自己选定f_dim是哪一列的

**Comment by wuhaixu2016** [comment]
您好，在数据加载中会默认讲Target这一列放在最后，请见：https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L236
