### ISSUE TITLE
关于NSTransformer ECL scripts

### ISSUE THREAD

**Issue by CSyyn** [thuml/Time-Series-Library#306]
在Nonstationary Transformer 的ECL_scripts上设置了features为‘S’，其他模型为M
`python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_96_192 \
  --model $model_name \
  --data custom \
  --features S \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --itr 1 \
  --p_hidden_dims 256 256 \
  --p_hidden_layers 2 \
  --d_model 2048`

**Comment by wuhaixu2016** [comment]
收到，感谢指出，已经更新～
