### ISSUE TITLE
论文中其他SOTA方法的数据来源

### ISSUE THREAD

**Issue by Diroooomy** [thuml/Time-Series-Library#307]
请问Timesnet论文中的对比方法尤其是长时预测的方法，比如DLinear、ETSformer等方法的结果是使用的官方实现的跑出来的还是通过该时序算法库中的运行框架跑出来的

**Comment by wuhaixu2016** [comment]
您好，如果其他论文中的实验setting（输入输出长度）与timesnet一致，就会直接使用其官方论文中的效果，不然为了保证实验设置的公平对比，我们会将他官方开源的模型放在tslib中运行对比。
