### ISSUE TITLE
TimeSeries classification task

### ISSUE THREAD

**Issue by Songyihu** [thuml/Time-Series-Library#308]
Thank you for sharing your great work! I'm working on the timeSeries classification task. However, I didn't see "padding_mask" in the classification dataloader which shows in exp_classification.py. Could you give me some advice, Thanks a lot!

**Comment by wuhaixu2016** [comment]
Hi, you can find the relative code here: https://github.com/thuml/Time-Series-Library/blob/main/data_provider/uea.py#L39
