### ISSUE TITLE
关于开源代码和论文实验结果复现问题

### ISSUE THREAD

**Issue by luwanrong** [thuml/Time-Series-Library#310]
我用仓库给出的开源代码和脚本执行训练和测试，跑出的结果和论文中对比实验结果差距较大，还有人遇到这个问题吗？为什么？

**Comment by wuhaixu2016** [comment]
您好，具体是哪个脚本呢？需要注意pytorch的版本问题，我们实验的版本是torch==1.7.1

**Comment by luwanrong** [comment]
> 您好，具体是哪个脚本呢？需要注意pytorch的版本问题，我们实验的版本是torch==1.7.1

我的版本是1.13.1+cu117，我理解的不同版本的差异主要是兼容性问题，不应该对预测性能产生太大的影响啊，我用你们的requirements.txt配个环境试一下

**Comment by wuhaixu2016** [comment]
您好，pytorch.fft在1.8之后有了比较大的改版，请见：https://github.com/thuml/Time-Series-Library/issues/12

另外，为了保持公平的比较，我们将所有论文的input length设置为了96，这也可能会具体的某一个论文不一致（很多论文会搜索或者使用更长的输入）。
