### ISSUE TITLE
Koopa module - torch.linalg.lstsq call

### ISSUE THREAD

**Issue by ajikmr** [thuml/Time-Series-Library#311]
Hello.

Koopa module calls 'torch.linalg.lstsq' which is not there in torch 1.7.1 version. Please update requirements.txt to indicate correct torch version required. I am able to run the code after upgrading to latest torch i.e. 2.1 .

Thanks.

**Comment by WenWeiTHU** [comment]
Thanks for your concern, you can find the exact requirements version in this repository: https://github.com/thuml/Koopa.
