### ISSUE TITLE
Something wrong on short_term_forecast

### ISSUE THREAD

**Issue by xiaoxiaomiwang** [thuml/Time-Series-Library#313]
training_values = np.array(
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (48000,) + inhomogeneous part.

**Comment by Azusa-Yuan** [comment]
![图片](https://github.com/thuml/Time-Series-Library/assets/61765965/ad8ed0db-cc34-4de6-90fb-91246dce5aee)
![图片](https://github.com/thuml/Time-Series-Library/assets/61765965/3063a5c1-2b5a-409a-bdc6-c1b6278e5b2d)
I also meet this problem, but i don't how to solve.

**Comment by GGchen1997** [comment]
Same here.

**Comment by GGchen1997** [comment]
I remove "np.array()". It works.

**Comment by wuhaixu2016** [comment]
Hi, thanks for your question and answer from @GGchen1997 . 
This code works well for me. So if you come across some problems, please try to remove "np.array()" following the above answer.

**Comment by ICharlotteI** [comment]
I ran into the same problem, not only in the code snippet described above, but also in the evaluation phase
naive2_forecasts = np.array([v[~np.isnan(v)] for v in naive2_forecasts])
np.array([v[~np.isnan(v)] for v in values[groups == group_name]])
Have you encountered the same problem?

**Comment by ICharlotteI** [comment]
I ran into the same problem, not only in the code snippet described above, but also in the evaluation phase
naive2_forecasts = np.array([v[~np.isnan(v)] for v in naive2_forecasts])
np.array([v[~np.isnan(v)] for v in values[groups == group_name]])
Have you encountered the same problem?

**Comment by adkwoekrf** [comment]
> 我删除了“np.array（）”。它有效。

这个操作是有效的。
