### ISSUE TITLE
Insufficient GPU memory for the long term forecast task

### ISSUE THREAD

**Issue by jack4python** [thuml/Time-Series-Library#314]
My dataset is a univariate dataset with 652 timestamps, and the values for seq_len, label_len, pred_len, and batch_size are 30, 7, 7, and 8, respectively. 
    When running the model using the TimesNet model, an error message is displayed: 'OutOfMemoryError: CUDA out of memory. Tried to allocate 484.00 MiB (GPU 0; 15.90 GiB total capacity; 14.72 GiB already allocated; 29.75 MiB free; 14.91 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF.' 
   Is this error due to the insufficiency of 16GB of GPU memory for running TimesNet, or is there an issue with my settings?

**Comment by wuhaixu2016** [comment]
Hi, if you focus on the univariate forecasting, you can decrease the d_model and d_ff in TimesNet to 16 and 32 respectively. Since TimesNet is an TCN-based model, it does not require large channels like Transformer for representation learning.
