### ISSUE TITLE
无法复现结果，用了torch1.7.1也一样不行

### ISSUE THREAD

**Issue by yanghu819** [thuml/Time-Series-Library#317]
long_term_forecast_ETTh1_96_96_TimesNet_ETTh1_ftM_sl96_ll48_pl96_dm16_nh8_el2_dl1_df32_fc3_ebtimeF_dtTrue_Exp_0  
mse:0.3889973759651184, mae:0.41171911358833313
cuda版本11.7
差别很大，请教下可能的原因

**Comment by herkerser** [comment]
Hi, I encountered the exact same problem, did you solve the problem?
Would you please share some experience? It would be very helpful!
