### ISSUE TITLE
显存不足

### ISSUE THREAD

**Issue by showl0ing** [thuml/Time-Series-Library#32]
作者你好，在我替换自己的数据集后，发生了显存不足的问题。在文献中我看到你用的时24G的单张TITAN，而我的服务器时两张12G的TITAN，我想问一下你在实验过程中消耗的显存大概是多少呢？

**Comment by wuhaixu2016** [comment]
您好，ECL和Traffic的显存消耗会超过12GB，如果显存不足的话，您可以通过降低batch size的方式解决

**Comment by showl0ing** [comment]
您好，我是两张12G的，设置了use_multi_gpu 为Ture，已尝试减少batch_size至2，但是仍然会出现CUDA out of memory。但是其中一张卡并没有跑满，请问您有遇到过类似情况吗？
![image](https://user-images.githubusercontent.com/100761617/223077564-32245dce-0c20-4245-9a29-c51a9f931931.png)

**Comment by wuhaixu2016** [comment]
您好，可以描述一下具体跑的那个script吗？我们在跑实验过程中，没有遇到过这种情况

**Comment by showl0ing** [comment]
您好，使用TimesNet做长时预测，seq_len=192 , label_len=48,pred_len=96, batch_size=2 。换上了我自己的数据集，feature=192。在loss.backward()发生报错。接着，我使用了ETTm1和ETTh1进行尝试，使seq = 96 ，pred = 12, 结果仍然会出现显存不足的情况。

**Comment by wuhaixu2016** [comment]
可以按照我们给的scritp运行，不会出现这样的问题。
TimesNet和Transformer的区别在于，Transformer需要学习非常高维度的深度特征，才可以计算稳定的attention。所以您在运行时，可以将d_model和d_ff设置为32/64，不要使用默认值

**Comment by showl0ing** [comment]
> 可以按照我们给的scritp运行，不会出现这样的问题。 TimesNet和Transformer的区别在于，Transformer需要学习非常高维度的深度特征，才可以计算稳定的attention。所以您在运行时，可以将d_model和d_ff设置为32/64，不要使用默认值

谢谢！祝身体健康，科研顺利！
