### ISSUE TITLE
Non-overlapping sliding window for anomaly detection experiments

### ISSUE THREAD

**Issue by ZinebSN** [thuml/Time-Series-Library#320]
Thanks for your work!
Can you please confirm whether the step in anomaly detection datasets in the dataloader was set to 1 or 100 in your experiments? In the paper you mentioned that the datasets were processed using a non overlapping sliding window, however in the implementation it is set to 1, resulting in sequences with overlapping  timestamps?

**Comment by wuhaixu2016** [comment]
Hi, this code base is based on Anomaly Transformer, please see this code: https://github.com/thuml/Anomaly-Transformer/blob/main/data_factory/data_loader.py#L202

For SMD, the step is set as 100 and 1 for others. Sorry for this mistake.
