### ISSUE TITLE
How to feed my sensor dataset into the TimesNet model for classification task

### ISSUE THREAD

**Issue by huytran088** [thuml/Time-Series-Library#327]
Hello,

So now I am trying to feed my custom dataset into the TimesNet model for classification task. The data is currently looking like this:
![image](https://github.com/thuml/Time-Series-Library/assets/54724043/67b07841-d7cc-4b3c-b9fe-48b7c4c41a6d)

In my dataset, there are 10 files, which are time-series data. In the text file, each 7 rows is the data at one timestamp. Each timestamp separates each dimension by “,”. At each timestamp, the data could have up to 3 dimensions.  Since my data is one-dimensional, the data is stored in the following order:

For each timestamp, I have:

- Row 1:  x value (for rotation)
- Row 2: y value (for rotation)
- Row 3: z value (for rotation)
- Row 4: w value (for rotation)
- Row 5: x value (for translation)
- Row 6: y value (for translation)
- Row 7: z value (for translation)

And moving to the next timestamp, and repeat until the end of the segment.
I want to reshape the data, removing the delimiters, segmenting the data using the sliding window, and preparing the data for the TimesNet model.

So far, I am trying to follow the Dataset_Custom class in the data_loader.py file, but as far as I know, this is only for long-term forecasting, not for classification.

Can you provide some tips/advices on the steps of implementing this. Thank you.

**Comment by wuhaixu2016** [comment]
Hi, you indeed need to re-write a new dataloader. 
You can adopt the Dataset_Custom to load the time series data and write some new codes to load the label information.
