### ISSUE TITLE
为什么认为将所有的seq_len设置为96是一种公平的表现

### ISSUE THREAD

**Issue by ooooooover** [thuml/Time-Series-Library#328]
作者您好：
    在DLinear中有指出基于transformer的方法通常在seq_len=96时有着最好的表现，但对于PatchTST来说，论文中明确提到了更长的seq_len对于model是有益的，那么对于baseline的选择不应该选择表现最好的超参数吗，我对比了将seq_len设置为512的PatchTST实验结果，基本上PatchTST是优于seq_len=96以及seq_len=512的iTransformer的。
![QQ截图20240201172946](https://github.com/thuml/Time-Series-Library/assets/106066982/972c40e7-42f8-4d9f-b456-f0e577eb4ed8)

    期待您的回复。

**Comment by wuhaixu2016** [comment]
您好，我觉得公平的实验有以下两类：
（1）所有模型都统一超参数，这样可以避免调参过程中的数据窥探（Data Snooping），比如iTransformer，TimesNet，Autoformer都是这样的设置
（2）所有模型的超参数都在一个较大范围内用验证集进行超参数搜索，这样可以测试模型的效果上限。

详细效果对比可以见我们在ICLR2024的另外一篇工作：https://openreview.net/forum?id=7oLshfEIC2，这个论文完整报了所有模型在上述两个setting下的结果。我个人其实也建议大家在后续工作中可以同时测这两个setting下的模型对比，这样可以更加充分检验模型效果。
