### ISSUE TITLE
数据集是否可以不用date列

### ISSUE THREAD

**Issue by ZHE0725** [thuml/Time-Series-Library#33]
您好！我的数据集中不包含date列，是否可以在此情况下进行正常训练？大致应该在哪里修改代码？

**Comment by wuhaixu2016** [comment]
可以的，你需要做这些工作
（1）去掉dataloader.py中对于date列的信息提取
（2）将x_mark_enc，x_mark_dec设置为None
（3）改变embedding方式，去掉temporal_embeding

**Comment by ZHE0725** [comment]
> 



> 可以的，你需要做这些工作 （1）去掉dataloader.py中对于date列的信息提取 （2）将x_mark_enc，x_mark_dec设置为None （3）改变embedding方式，去掉temporal_embeding

您好，我狂试了一晚上，还是有一些问题，data_loader.py的__getitem__方法的返回值seq_x_mark与seq_y_mark该怎么处理呢，显示不可以设为None，与之对应的exp_long_term_forecasting.py中的train方法内的batch_x_mark和batch_y_mark也无法处理，求指教

**Comment by wuhaixu2016** [comment]
那你也可以直接设置成ones，然后不使用它即可
