### ISSUE TITLE
Clarifications on exp_anomaly_detections.py

### ISSUE THREAD

**Issue by LeSimo** [thuml/Time-Series-Library#332]
Hi, thank you for your work!
I'm working on anomaly detection tasks and I have 2 quetions that I'd like to present to you:

1) In exp_anomaly_detection the threshold is calculated as shown
`combined_energy = np.concatenate([train_energy, test_energy], axis=0)`
`threshold = np.percentile(combined_energy, 100 - self.args.anomaly_ratio)`
 From a theoretical point of view, do you consider as anomalous an event with an error above the 99th percentile? And if so, what should the calculated train and test energies represent?

2) How should I go about bringing back from the calculated predictions to a unique prediction for the single input event, given that the size of the seq_len at 100 creates 100 predictions for the same event, expanding the size of the final output result?

**Comment by wuhaixu2016** [comment]
Hi, thanks for your questions.
(1)Yes. This means a time point is considered abnormal when the error value is above the 99th percentile. To find out the error value distribution, we calculate the train energies (errors) and adopt the 99th percentile value in the train set to label test set energies. Please see: https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_anomaly_detection.py#L177

(2) You can ensemble the error value of 100 predictions and check if the mean value larger or smaller than the pre-calculated threshold.
