### ISSUE TITLE
An inquiry about TimesNet

### ISSUE THREAD

**Issue by hope-redemption** [thuml/Time-Series-Library#334]
In the FFT_for_Period function, when encountering top k frequencies that are not integers, constructing a 2D tensor involving pi x fi,
how to handle non-integer frequencies? Thanks.

**Comment by wuhaixu2016** [comment]
Hi, you can pad the reshaped tensor with zeros. Please see https://github.com/thuml/Time-Series-Library/blob/main/models/TimesNet.py#L47
