### ISSUE TITLE
Weather数据集结果无法复现

### ISSUE THREAD

**Issue by Gczmy** [thuml/Time-Series-Library#335]
尝试使用PatchTST和FreTS复现在Weather数据集上的结果，但是跑出来的mse和mae非常大，如下图所示。

![image](https://github.com/thuml/Time-Series-Library/assets/20588674/eb621cac-aaa4-4c54-8eef-467129ddccd0)

其中PatchTST的脚本是使用库中提供的，FreTS的脚本在此基础上仅修改了模型名字，暂未测试其他模型。
Weather数据集从README文件中给出的GoogleDrive链接处下载。
同时测试了FreTS跑Traffic数据集，结果与论文一致，怀疑是Weather数据集问题。

**Comment by wuhaixu2016** [comment]
你好，PatchTST的差别应该是输入长度的问题，在他原始论文中，输入长度被设置为了336。在我们的算法库中为了和其他工作保持一致，我们将其设置为了96。
