### ISSUE TITLE
problem with running classification problem about TimesNet

### ISSUE THREAD

**Issue by hope-redemption** [thuml/Time-Series-Library#336]
When I tried to run the code for the classification problem using JapaneseVowels, it showed the following error, does anyone can help me?
![problem](https://github.com/thuml/Time-Series-Library/assets/75553933/8431edb7-3e60-4e5d-ba86-a4b5d215d0c9)

**Comment by hope-redemption** [comment]
I try to use Vscode in Windows to run the code.

**Comment by hope-redemption** [comment]
I discovered that to execute the code on Windows, it's necessary to set **num_workers** in **DataLoader** to **0** without using **args.num_workers = 0**. I'm curious if this adjustment will affect the outcome. Thank you.

**Comment by selinnyilmaz** [comment]
Did you solve this issue since I'm getting the same problem right now?

**Comment by awalece04ku** [comment]
I got the same problem. Please help

**Comment by wuhaixu2016** [comment]
Hi, for Windows, you can just set args.num_workers = 0. This setting only affects the data loader, and will not affect the final performance.
