### ISSUE TITLE
预测结果和真实值发生偏移问题

### ISSUE THREAD

**Issue by kavinwow100** [thuml/Time-Series-Library#339]
用自己的数据尝试训练了itransformer 完成了Long-termForecasting任务，features为MS类型，数据间隔为每15分钟，freq设置为“t”，但是我在plot 项目result文件夹中的预测结果时，图像发生了偏移。详细如下，翻了历史的issue也对temporal embedding进行了调整发现仍然有这种问题。辛苦您能给我指点下问题，非常感谢。

plt.plot(trues[:,0,-1].reshape(-1)[-50:], label='GroundTruth')
plt.plot(preds[:,0,-1].reshape(-1)[-50:], label='Prediction')
![image](https://github.com/thuml/Time-Series-Library/assets/13030876/cf2b28e7-5f4b-4fd9-a84b-ee9263c14ccc)

如果对preds中结果进行人工偏移发现拟合的还不错，不知道问题出在哪里？
plt.plot(trues[:,0,-1].reshape(-1)[-50:], label='GroundTruth')
plt.plot(preds[:,0,-1].reshape(-1)[-49:], label='Prediction')
![image](https://github.com/thuml/Time-Series-Library/assets/13030876/e5e7bbd3-34e3-41d0-9845-b4b2acaff2e4)

**Comment by lss-1138** [comment]
说明目前单点预测最好的结果，就是copy上一个点，无解

**Comment by LY-must-win** [comment]
跟LSTM单步预测结果有点像

**Comment by xiaolin96** [comment]
你把数据用一个最简单的lstm跑一下应该也是这种，最近和老师争议的也是这个问题，老师说我直接copy上一个点来预测，你的方法都没我的好，还提出什么新方法。。。如果找到解决方案，烦请告知，mark一下

**Comment by ztxtech** [comment]
时间序列预测有$k$迟滞性，这也是研究方向，如果延迟消失，自然预测的好。如果直接偏移，等价于构建$\hat{y_i} = Net(y_i)$$,而你需要预测的时间点$i$,你是获取不到的，不能拿预测值预测预测值。

**Comment by ztxtech** [comment]
朴素预测是一种方法，逻辑上确实误差很低，但用的是上一个时间点的数值。

**Comment by xiaolin96** [comment]
lstm 单点预测，每一步同样要用上一个时间点的数值啊

**Comment by ztxtech** [comment]
> lstm 单点预测，每一步同样要用上一个时间点的数值啊

是啊，但如果把预测的平移，就相当于已经知道了下一个时间点的数值嘛。本来构建的是 \hat{y}_i+1 = Net(y_i)，平移后相当于是\hat{y}_i+1 = Net(y_i+1)

**Comment by rayoluo** [comment]
> 用自己的数据尝试训练了itransformer 完成了Long-termForecasting任务，features为MS类型，数据间隔为每15分钟，freq设置为“t”，但是我在plot 项目result文件夹中的预测结果时，图像发生了偏移。详细如下，翻了历史的issue也对temporal embedding进行了调整发现仍然有这种问题。辛苦您能给我指点下问题，非常感谢。
> 
> plt.plot(trues[:,0,-1].reshape(-1)[-50:], label='GroundTruth') plt.plot(preds[:,0,-1].reshape(-1)[-50:], label='Prediction') ![image](https://private-user-images.githubusercontent.com/13030876/306847137-cf2b28e7-5f4b-4fd9-a84b-ee9263c14ccc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDEzNDAsIm5iZiI6MTcxODcwMTA0MCwicGF0aCI6Ii8xMzAzMDg3Ni8zMDY4NDcxMzctY2YyYjI4ZTctNWY0Yi00ZmQ5LWE4NGItZWU5MjYzYzE0Y2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA4NTcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMTc1NWY0OTY0OTljMDFhY2JlYTZhMjc0NzQ1YTMyMDkwNDQ5MjE2MTBkYzA1YWIxMjc4MTRiOTQ4N2FmNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BgyK7JEFAMhdilVTG_gtyO4oyuW0Bk22ObyEAam_5Qs)
> 
> 如果对preds中结果进行人工偏移发现拟合的还不错，不知道问题出在哪里？ plt.plot(trues[:,0,-1].reshape(-1)[-50:], label='GroundTruth') plt.plot(preds[:,0,-1].reshape(-1)[-49:], label='Prediction') ![image](https://private-user-images.githubusercontent.com/13030876/306847195-e5e7bbd3-34e3-41d0-9845-b4b2acaff2e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDEzNDAsIm5iZiI6MTcxODcwMTA0MCwicGF0aCI6Ii8xMzAzMDg3Ni8zMDY4NDcxOTUtZTVlN2JiZDMtMzRlMy00MWQwLTk4NDUtYjRiMmFjYWZmMmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA4NTcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMWZiMmE1Y2E2NTE2NzE1MTJiMTc2MzdiN2IwN2M2YjIyOTVlYjk2YmE4NThkMGQ3ZDg1MjUyZjk4OTY5MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mu_D6_fvdGeU8GUcjmWYqBtpE4XuOwSar29p_eKYuq0)

请问这个问题解决了吗？

**Comment by chenshaui** [comment]
方便问一下你的pred_len是多少吗

**Comment by wuhaixu2016** [comment]
您好，我详细看完了大家的讨论，这个问题我之前没有关注过，也并不知道解答。我在之前做视频预测的时候也出现过类似的现象。
所以我觉得这可能是预测任务的一个根本问题，如果大家有答案之后可以麻烦邮件我。因为这个与算法库实现关联不大，所以我关闭了这个issue，感谢大家讨论。
