### ISSUE TITLE
Transform raw data

### ISSUE THREAD

**Issue by hljuniversity** [thuml/Time-Series-Library#34]
作者您好，论文中提到了转换原始数据，这个地方我没明白怎么转换的，您能说一下吗？

**Comment by luoxia-wen** [comment]
我看代码里好像是进行了token嵌入和position嵌入，从N（变量个数）嵌入到d_model（设定）维，具体代码可以看embed.py那个文件，但是我也不知道这个嵌入是否是必要的，然后对模型有什么具体的作用，提了issue了

**Comment by wuhaixu2016** [comment]
如果您指的是表9 Transform raw data：请参考https://github.com/thuml/Time-Series-Library/issues/35
如果您指的是数据预处理，请参考https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py 的line8
