### ISSUE TITLE
Add PatchTSMixer to the leaderboard/library

### ISSUE THREAD

**Issue by ajati** [thuml/Time-Series-Library#341]
`PatchTSMixer` is a recently published state-of-the-art model for long-term forecasting. 
Paper: https://arxiv.org/pdf/2306.09364.pdf
Code: https://github.com/huggingface/transformers/tree/v4.38.1/src/transformers/models/patchtsmixer
Blog: https://huggingface.co/blog/patchtsmixer

**Comment by wuhaixu2016** [comment]
Hi, we have newly added two linear models: TimeMixer and TSMixer. Would you please propose a pull request for this model?
