### ISSUE TITLE
多变量预测多变量能否指定多列预测目标

### ISSUE THREAD

**Issue by AcrazyQ** [thuml/Time-Series-Library#342]
我想要使用M，例如10列特征预测其中2列要怎么选择target呢

**Comment by wuhaixu2016** [comment]
您好，如果您使用的是M的话，默认是所有的变量都是target。
所以您需要更改一下代码，在计算loss的时候选择其中两列，具体对应这几行：https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_long_term_forecasting.py#L126-L128

**Comment by AcrazyQ** [comment]
感谢！
