### ISSUE TITLE
关于不同CV模块的实验代码

### ISSUE THREAD

**Issue by XingYuan1013** [thuml/Time-Series-Library#345]
作者您好，目前只看到了InceptionBlock的代码，请问能否开源一下论文实验中提用到的其他CV Block(ResNet、ConvNext等)的代码？因为是初学者，想替换一些其他的CV Block，但是不太会写。

**Comment by wuhaixu2016** [comment]
您好，其他CV模块可以直接从他们的论文官网找到。
