### ISSUE TITLE
Proposal: Adding SegRNN Code to the Library

### ISSUE THREAD

**Issue by lss-1138** [thuml/Time-Series-Library#346]
Hi, thank you for your efforts in contributing to the advancement of the community, and I have been following your work for quite some time. I noticed that your repository **does _not_ include any baseline methods based on _RNNs_**, which is understandable given that traditional RNNs struggle to model very long sequences.

To address this, we have introduced **_SegRNN_** (repository link: https://github.com/lss-1138/SegRNN), which significantly improves the performance of RNN methods in long time series prediction tasks and currently stands as the _state-of-the-art RNN-based method_. It demonstrates outstanding performance regardless of the length of the look-back length, whether it be longer (720) or shorter (96).

The performance of SegRNN on the Weather dataset with a **look-back length of 720**：
![image](https://github.com/thuml/Time-Series-Library/assets/57395990/2319f70a-8885-4b6b-8cd2-6ff238178776)

The performance of SegRNN on the Weather dataset with a **look-back length of 96**：
![image](https://github.com/thuml/Time-Series-Library/assets/57395990/6025cdd8-0a61-4d08-a6a7-62df78f4f0f2)

**We would greatly appreciate it if you could consider incorporating _SegRNN_ into your repository.** Once again, thank you for your efforts.

**Comment by wuhaixu2016** [comment]
Hi, many thanks for your recommendation. 
Due to the time limitation, we recently mainly focus on fixing bug. Would you please kindly propose a pull request?

**Comment by lss-1138** [comment]
Ok. We have proposed a pull request. Thank you for your efforts. @wuhaixu2016
