### ISSUE TITLE
转换数据（嵌入）后提取周期

### ISSUE THREAD

**Issue by luoxia-wen** [thuml/Time-Series-Library#35]
先对原始时间序列 $T \times C$ 进行嵌入到 $T \times d_{model}$，然后进行提取周期等后续操作；
有没有做过不进行嵌入直接进行周期提取的实验呢，**嵌入对于模型是否是必要的和有效的呢？**

**Comment by wuhaixu2016** [comment]
您好，请参考论文附录中的表9，Transformer raw data对应着直接对原始数据进行提取周期操作，再通过提取的周期进行reshape；Transformer raw data的效果始终差于先嵌入，再提周期的效果。

要注意，如果从始至终都不进行嵌入的话，甚至不会有深度特征，都不可以被称为深度模型了。

**Comment by luoxia-wen** [comment]
谢谢
