### ISSUE TITLE
关于imputation的mask_rate的问题

### ISSUE THREAD

**Issue by lizhuoq** [thuml/Time-Series-Library#350]
我注意到在你们的imputation脚本中设置了0.125，0.25，0.375，0.5四个mask_rate，我在想可不可在训练的时候在每个batch从0-0.5之间随机采样一个mask_rate，然后在每个batch中按照对应采样的mask_rate进行mask然后训练，想请问您这样可行吗？希望能得到您的回复。谢谢！

**Comment by wuhaixu2016** [comment]
您好这样可以的，可以更好的模拟真实情形下不同的缺失情况。不过这样就需要所有的模型在统一的benchmark下进行比较了。

**Comment by lizhuoq** [comment]
@wuhaixu2016 谢谢你的回复，这对我很有帮助！

**Comment by Wutianmei666** [comment]
您好，我想请问下您是否复现了模型呢？如果您复现过模型的话，请问效果和论文给出的数据差距大吗

**Comment by lizhuoq** [comment]
@Wutianmei666 你好，我没有在基准数据集上测试，而是直接应用在实际场景数据上，我们比较了DLinear、LSTM、PatchTST、TimesNet和iTransformer，TimesNet的结果最好

**Comment by Wutianmei666** [comment]
> @Wutianmei666 你好，我没有在基准数据集上测试，而是直接应用在实际场景数据上，我们比较了DLinear、LSTM、PatchTST、TimesNet和iTransformer，TimesNet的结果最好

好的，感谢您的解答
