### ISSUE TITLE
时序序列表征学习

### ISSUE THREAD

**Issue by Wodsk** [thuml/Time-Series-Library#351]
您好，我阅读了您关于TimesNet的文章，感觉idea十分新颖，并且发现其在多种下游任务上取得了很棒的成就。因此我在想是否能运用该架构进行时序序列表征学习的相关任务，即通过网络架构自动学习出时序序列的特征并进行聚类可视化操作，希望您能给我一点启发，非常感谢！

**Comment by wuhaixu2016** [comment]
您好，timesnet作为一个基础主干网络是可以的，但是还需要配合对应的预训练任务，您可以参考我们在今年NeurIPS的时序预训练的工作：https://arxiv.org/pdf/2302.00861.pdf
