### ISSUE TITLE
batch size

### ISSUE THREAD

**Issue by ownnaruto** [thuml/Time-Series-Library#352]
注意到scripts 中有些模型指定了 batch size 的大小，请问这么做的原因是什么呢？另外论文中对比的结果是否控制了batch size大小相同呢？

**Comment by wuhaixu2016** [comment]
您好，在我们的论文TimesNet中，所有的baseline和我们自己的方法都用了相同的batch size。

但是最近一年我们发现，很多时序预测的工作都会搜索超参数（这些工作或多或少存在一些不公平比较），比如learn rate、batch size、input length、d_model等等，为了复现这些新论文的效果，我们提供在TSlib中的script是进行搜索过的。

但是如果您想用TSlib进行实验，我其实建议您跑两个setting（1）所有模型统一参数（2）所有模型都搜索超参数；
具体setting可以参考我们在今年ICLR2024上的工作TimeMixer，我们在这个论文中给出了上述两种实验setting的结果，用于充分比较模型的效果优劣：https://openreview.net/forum?id=7oLshfEIC2
