### ISSUE TITLE
ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is

### ISSUE THREAD

**Issue by fiksdano** [thuml/Time-Series-Library#36]
作者你好，我有几个问题想向你请教一下

> 首先是我标题显示的错误，这个错误是我运行TimesNet_ETTh1.sh这个文件出现的，如下图所示，同时系统会自动打开vs code软件，但一直停留在那个画面

> 第二个问题我的torch版本是1.11.1+cu113,但安装要求里面的软件包都没有问题，有一些版本过高不知是否有影响。我按照文档里面的要求运行了TimesNet_ETTh1.sh，这个操作是在我并没有添加任何数据的情况下，我下载了作者你给的数据集，但不是很清楚要放在哪一个路径里面，还是程序会自动检索文件所在位置？所以请教一下你我如果要测试自己的数据集，应该放在哪个文件里面呢？

>最后我说一下我运行这个代码的思路，如果有哪里不对请作者指正一下，真的很想让代码跑起来。前面的准备工作都已经做完，环境配置好了并且数据集已经下载好了之后，我将他放在同一个文件夹里面，如下图是我放文件的路径，完成之后我就运行了timenet文件，但是结果并不如愿，出现了开头的错误。希望作者可以给一下帮助，期待你的回复。
![微信图片_20230307115419](https://user-images.githubusercontent.com/127064182/223316678-126680c1-2ad9-45f0-99ac-07b158e67d07.png)

![微信图片_20230307112905](https://user-images.githubusercontent.com/127064182/223314641-c752b456-d919-4d05-8a3b-8e1ad171e06c.png)

**Comment by htg17** [comment]
1.关于路径的问题，不能在dataloader文件里改，这个是默认值，会被正常的输入覆盖掉；应该在对应的script（.sh文件）里改--root_path。
2.关于运行的问题。你好像是直接输入了个文件名，而没有运行；应当是先进入目录（这里应该是Code这一个文件夹），然后再bash或者sh对应的scrip文件。

**Comment by fiksdano** [comment]
![微信图片_20230307164651](https://user-images.githubusercontent.com/127064182/223370524-38a6841f-e1d3-4d2d-9849-fab4a1760259.jpg)
我更换了一台电脑进行运行，运行出来的效果如上图所示，请问这种是什么情况？同时运行之后的效果指标是在哪里去查看？

**Comment by htg17** [comment]
这个错误是因为本地无法进行多线程，可以将scripts内num_worker设置为0；另外如果使用本地CUDA运行可以将script第一行设置为export CUDA_VISIBLE_DEVICES=0。

运行指标会正常打印，如果是本地运行的话可能会比较慢
