### ISSUE TITLE
TimesNet

### ISSUE THREAD

**Issue by morestart** [thuml/Time-Series-Library#360]
![image](https://github.com/thuml/Time-Series-Library/assets/35556811/1da98c7c-4892-48dd-9f79-5186363608bc)
enc_out的维度是b,t,c其中c定义了512，
```python
enc_out = self.predict_linear(enc_out.permute(0, 2, 1)).permute(
        0, 2, 1)  # align temporal dimension [B,pred_len+seq_len,C]
```
接着进入了一个线性层，但是输入维度却是Bx(pred_len+seq_len)，不是Bx512这里是不是有问题

**Comment by wuhaixu2016** [comment]
您好，这里这个线性层的目的是对齐时间维度，比如enc_out的大小是（B，seq_len，c），但是我们需要的预测结果时间长度是pred_len+seq_len，仅仅使用特征提取器是无法完成时间维度上的长度对齐的，因此使用seq_len维度上的线性层，从而实现长度的变换。具体请见：https://github.com/thuml/Time-Series-Library/blob/main/models/TimesNet.py#L90-L91
