### ISSUE TITLE
hyperparameter

### ISSUE THREAD

**Issue by chengsaf** [thuml/Time-Series-Library#361]
Hello author, I am very interested in your work in the TimesNet paper. Could you please suggest a medium-sized hyperparameter search space to explore the upper limit of model application? Much appreciated.

**Comment by wuhaixu2016** [comment]
Hi, thanks a lot for your intereset. For application, I think the key parameters contain the input length (seq_len), channel number (d_model) and kernel size (top_k).
The seq_len should be set as the value that at least contains 2 periods. The d_model should be set according to the real variate number. And top_k can be selected from {3,5,7}.
