### ISSUE TITLE
About Data Leakage in FFT_for_Period

### ISSUE THREAD

**Issue by herkerser** [thuml/Time-Series-Library#362]
Thank you for your work.
```

def FFT_for_Period(x, k=2):
    # [B, T, C]
    xf = torch.fft.rfft(x, dim=1)

    # find period by amplitudes
    frequency_list = abs(xf).mean(0).mean(-1)
    frequency_list[0] = 0
    _, top_list = torch.topk(frequency_list, k)
    top_list = top_list.detach().cpu().numpy()
    period = x.shape[1] // top_list
    return period, abs(xf).mean(-1)[:, top_list]
```
In this function, for every batch, the input x includes the data to be predicted.
This means that when calculating the period, the information of the testing data are utilized, which leads to data leakage.
Did I made a mistake?

**Comment by wuhaixu2016** [comment]
Hi, x does not include the "data to be predicted". Please see: https://github.com/thuml/Time-Series-Library/blob/main/models/TimesNet.py#L113-L114 the future part is generated by past information at beginning
