### ISSUE TITLE
关于维度重构问题

### ISSUE THREAD

**Issue by ZHE0725** [thuml/Time-Series-Library#365]
请问为什么使用频率的最大索引值进行维度重构，而不是频率振幅数据？应该如何理解这一步操作，请求解答，感谢！

**Comment by wuhaixu2016** [comment]
您好，这里的重构主要是为了找出最显著的周期，所以我们选取了振幅数值靠前的频率，具体请见torch.fft的用法：https://pytorch.org/docs/stable/generated/torch.fft.rfft.html#torch.fft.rfft
