### ISSUE TITLE
运行TimesNet_ETTh1.sh时报错ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by tx-frozen** [thuml/Time-Series-Library#37]
您好，我根据您提供的requirement.txt配置好了环境，想使用您的代码跑ETTh1数据集上长期时序预测的实验。我先将您的数据集放在自己建立的dataset下面解压，解压出来多了一层all_datasets的文件夹，因此我修该了TimesNet_ETTh1.sh中root_path的属性，但是当我按照提示bash ./scripts/long_term_forecast/ETT_script/TimesNet_ETTh1.sh运行TimesNet_ETTh1.sh时出现报错提示：
Traceback (most recent call last) :
    File "run.py", line 4, in <module>
        fron exp.exp_long_tern_forecasting import Exp_Long_Tern_Forecast
ValueError: source code string cannot contain null bytes
请问这个问题如何解决呢

**Comment by fiksdano** [comment]
> 您好，我根据您提供的requirement.txt配置好了环境，想使用您的代码跑ETTh1数据集上长期时序预测的实验。我先将您的数据集放在自己建立的dataset下面解压，解压出来多了一层all_datasets的文件夹，因此我修该了TimesNet_ETTh1.sh中root_path的属性，但是当我按照提示bash ./scripts/long_term_forecast/ETT_script/TimesNet_ETTh1.sh运行TimesNet_ETTh1.sh时出现报错提示： Traceback (most recent call last) : File "run.py", line 4, in fron exp.exp_long_tern_forecasting import Exp_Long_Tern_Forecast ValueError: source code string cannot contain null bytes 请问这个问题如何解决呢

你好，我想请问一下你除了改变TimesNet_ETTh1.sh中的数据集路径外，是否还有更改其他操作？同时当年运行TimesNet_ETTh1.sh文件时会出现Passthrough is not supported, GL is disabled, ANGLE is？

**Comment by tx-frozen** [comment]
您好，对于下载的数据集压缩包，我放在了自己新建的dataset文件夹中，解压缩后生成了all_datasets文件夹，其中包含了所有数据集，我根据新数据集的位置修改了TimesNet_ETTh1.sh中root_path属性，除此之外没有进行任何其他操作，然后运行了TimesNet_ETTh1.sh并报了上述错误。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月7日(星期二) 下午3:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [thuml/Time-Series-Library] 运行TimesNet_ETTh1.sh时报错ValueError: source code string cannot contain null bytes (Issue #37)





  
您好，我根据您提供的requirement.txt配置好了环境，想使用您的代码跑ETTh1数据集上长期时序预测的实验。我先将您的数据集放在自己建立的dataset下面解压，解压出来多了一层all_datasets的文件夹，因此我修该了TimesNet_ETTh1.sh中root_path的属性，但是当我按照提示bash ./scripts/long_term_forecast/ETT_script/TimesNet_ETTh1.sh运行TimesNet_ETTh1.sh时出现报错提示： Traceback (most recent call last) : File "run.py", line 4, in fron exp.exp_long_tern_forecasting import Exp_Long_Tern_Forecast ValueError: source code string cannot contain null bytes 请问这个问题如何解决呢
  
你好，我想请问一下你除了改变TimesNet_ETTh1.sh中的数据集路径外，是否还有更改其他操作？同时当年运行TimesNet_ETTh1.sh文件时会出现Passthrough is not supported, GL is disabled, ANGLE is？

**Comment by htg17** [comment]
这个报错应该与路径无关，而与编码有关。您可以尝试用utf-8重新打开我们的代码

**Comment by fiksdano** [comment]
> 您好，对于下载的数据集压缩包，我放在了自己新建的dataset文件夹中，解压缩后生成了all_datasets文件夹，其中包含了所有数据集，我根据新数据集的位置修改了TimesNet_ETTh1.sh中root_path属性，除此之外没有进行任何其他操作，然后运行了TimesNet_ETTh1.sh并报了上述错误。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年3月7日(星期二) 下午3:22 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [thuml/Time-Series-Library] 运行TimesNet_ETTh1.sh时报错ValueError: source code string cannot contain null bytes (Issue #37) 您好，我根据您提供的requirement.txt配置好了环境，想使用您的代码跑ETTh1数据集上长期时序预测的实验。我先将您的数据集放在自己建立的dataset下面解压，解压出来多了一层all_datasets的文件夹，因此我修该了TimesNet_ETTh1.sh中root_path的属性，但是当我按照提示bash ./scripts/long_term_forecast/ETT_script/TimesNet_ETTh1.sh运行TimesNet_ETTh1.sh时出现报错提示： Traceback (most recent call last) : File "run.py", line 4, in fron exp.exp_long_tern_forecasting import Exp_Long_Tern_Forecast ValueError: source code string cannot contain null bytes 请问这个问题如何解决呢 你好，我想请问一下你除了改变TimesNet_ETTh1.sh中的数据集路径外，是否还有更改其他操作？同时当年运行TimesNet_ETTh1.sh文件时会出现Passthrough is not supported, GL is disabled, ANGLE is？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好，我刚刚尝试了一下，建议你直接把文件夹名字路径改了，不用改代码里面的路径尝试一下

**Comment by tx-frozen** [comment]
您好，我对所有的代码都使用了UTF-8编码，但是仍出现这个问题，还有其他的结局方法吗

**Comment by htg17** [comment]
或许可以参考这个帖子的解决方案https://stackoverflow.com/questions/31233777/python-source-code-string-cannot-contain-null-bytes，在终端输入：
`sed -i 's/\x0//g' FILENAME
`

**Comment by tx-frozen** [comment]
十分感谢您的回复，这个问题似乎和编码格式无关，因为我将所有的文件都按照utf-8的形式编码后仍存在这个问题，我打算将环境重新配置后再进行尝试。
