### ISSUE TITLE
一些问题请教

### ISSUE THREAD

**Issue by ouyuan416** [thuml/Time-Series-Library#371]
1、seq_len、label_len、pred_len中，seq_len是输入的序列长度，pred_len是输出的预测长度对吗，label_len的含义是什么呀？
2、longterm和shortterm的界限怎么划分呀？
谢谢！

**Comment by wuhaixu2016** [comment]
您好
1. label_len专门针对Transformerm模型，表示输入decoder的过去序列长度
2.科学意义上的长期和短期一般需要根据领域去划分，在本算法库中，我们这里的短期只代表M4数据集，长期其实可以接受任何csv文件输入，完成各种预测长度的任务。
