### ISSUE TITLE
您好，我想请教一下在时间序列预测中的真实样本外预测问题！

### ISSUE THREAD

**Issue by Kivirrr** [thuml/Time-Series-Library#372]
现在是2024年4月1日，假设我有一个包含2014年4月到2024年4月的时间序列预测样本，我在这个样本上进行训练和测试后，怎么进一步推理出2024年4月到2034年4月的数据呢？或者从2024年4月到2025年4月也可以，感谢！

**Comment by wuhaixu2016** [comment]
您好，这个需要看你想要的时间间隔，如果是以天为单位的话，需要预测未来365天，只要训练一个预测未来365天的模型即可。如果训练的模型没法达到预测长度需求，或者预测长度远远超过单个模型的长度的话，就需要进行滚动预报，即依照上一个时刻预测出的结果持续进行预报，不过这样效果无法保证。
