### ISSUE TITLE
DataEmbedding_inverted中d_model这个超参数设置为多少？

### ISSUE THREAD

**Issue by huangzhaor** [thuml/Time-Series-Library#373]
ITRANSFORMER中倒置Embedding中嵌入维度在实验中设置为多少？似乎没有看到对于这个超参数的谈论。请问一下这个参数有一般性的定论吗？还是在不同实验都需要微调？在短期预测比如说M4数据集设置为多少呢？

**Comment by wuhaixu2016** [comment]
您好，iTransformer主要是针对多变量预测，M4是单变量数据集，所以不会有独特的优势。
一般来说，把d_model设置为128即可，如果想要优化效果，可以根据embedding序列的长度、数据集的复杂度以及变量个数进行调整。
