### ISSUE TITLE
TimesNet Batch输入问题

### ISSUE THREAD

**Issue by LeqiGu** [thuml/Time-Series-Library#375]
假设BTN为2，4，1
那么输入数据时是按照什么样的顺序？如果shuffle是false
第一次输入：[[[x0,x1,x2,x3]],[x4,x5,x6,x7]]
第二次输入：[[[x8,x9,x10,x11]],[x12,x13,x14,x15]]

是这样的输入逻辑吗

**Comment by wuhaixu2016** [comment]
您好，不是的，两个数据之间的shift是1，具体请见：https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L275-L277

**Comment by LeqiGu** [comment]
请问为什么shift要设置为1而不是我说的那种呢，有什么好处
