### ISSUE TITLE
How to raise a PR with loss function update?

### ISSUE THREAD

**Issue by HowardZJU** [thuml/Time-Series-Library#376]
Hi authors,

Recently I want to submit a PR which would add an **effective** regularization term for LSTF. It has been verified with extensive experiments in a preprint paper. Is it acceptable for TSLib if I update a new exp file that includes the regularization?

**Comment by wuhaixu2016** [comment]
Hi, thanks for your time and attention to our project.
Currently, we mainly focus on model architectures. What we want to do is to build a consistent experiment configuration for different TS models. 
So, to keep this repo simple and neat, we cannot merge the loss function update PR.
Many thanks for your time.
