### ISSUE TITLE
About TimesNet

### ISSUE THREAD

**Issue by annmusic** [thuml/Time-Series-Library#38]
In the forecasting task of TimesNet, a linear layer is used to align the temporal dimension before extracting the intraperiod and interperiod features using the TimesBlock module, the temporal dimension is guaranteed to be the seq_len+pred_len. If I remove this step and extract the intraperiod and periperiod features from the seq_len sequence directly, and then use a linear layer to output pred_len sequence,  the model performance will become very poor. I would like to ask how is this considered. How should this be explained？

**Comment by wuhaixu2016** [comment]
(a) If we apply the temporal linear at first, the task of TimesNet is to refine the prediction, which is to learn the temporal variation of both past and future.
(b) If we apply the temporal linear at the last layer, the task of TimesNet is to extract the feature of past observations. All the prediction process (mapping from past to future) relies on the simple temporal linear.

Thus, I think a reasonable way to use TimesNet for forecasting is (a), which can better evaluate the model capability in learning the temporal variation of both past and future.
