### ISSUE TITLE
短时序预测发生问题

### ISSUE THREAD

**Issue by badfish2019** [thuml/Time-Series-Library#381]
ValueError: setting an array element with a sequence.

命令如下bash ./scripts/short_term_forecast/TimesNet_M4

**Comment by shijunticc** [comment]
你用的是作者提供的处理好的m4数据吗？这个报错应该是数组处理错误

**Comment by badfish2019** [comment]
[Hourly-train.csv](https://github.com/thuml/Time-Series-Library/files/14943173/Hourly-train.csv)
用的这个数据，直接下载全部的

**Comment by M4xweii** [comment]
> [Hourly-train.csv](https://github.com/thuml/Time-Series-Library/files/14943173/Hourly-train.csv) 用的这个数据，直接下载全部的

你解决了吗，我也遇到了这个问题

**Comment by congwaz** [comment]
注意numpy版本不要高于requirement中的太多，1.22.4没有问题

**Comment by wuhaixu2016** [comment]
@congwaz 感谢解答
