### ISSUE TITLE
异常检测中test函数中为什么要用到adjustment函数？

### ISSUE THREAD

**Issue by silent780** [thuml/Time-Series-Library#383]
exp_anomaly_detection.py的186行。
gt, pred = adjustment(gt, pred)；
这行代码在pred生成以后，根据gt对pred调整，请问这个调整的作用是什么？

**Comment by wuhaixu2016** [comment]
这个相当于在做一个事件级的异常检测metric，更多讨论请见：https://github.com/thuml/Anomaly-Transformer/issues/14

**Comment by silent780** [comment]
谢谢！
