### ISSUE TITLE
在短期时序预测M4数据集上发生问题如下问题：1）在预测小时的m4数据集时发生错误，需要修改h=4到h=1才能运行，不知道这样操作是否正确？2）训练集的误差极大，收敛速度很满，且提早early_stopping，不知道是什么问题呢？

### ISSUE THREAD

**Issue by GBX-Engineer** [thuml/Time-Series-Library#384]
![微信截图_20240416173549](https://github.com/thuml/Time-Series-Library/assets/39286092/b639da77-bd34-438f-981a-f3bfcf12984e)
![微信截图_20240416173913](https://github.com/thuml/Time-Series-Library/assets/39286092/efc45337-4d23-4ac5-ad9a-9683e6fb3e6a)

**Comment by wuhaixu2016** [comment]
您是使用的自己的模型吗？也许需要进行一定的数据归一化处理https://github.com/thuml/Time-Series-Library/blob/main/models/TimesNet.py#L131-L139

**Comment by dawn0713** [comment]
我也遇到了相同的问题，因为会de-norm之后模型才输出结果，所以loss很大，请问M4数据集为什么不和其他数据集一样，在读取时做归一化呢？
