### ISSUE TITLE
env error:Could not build wheels for mamba_ssm, which is required to install pyproject.toml-based projects**

### ISSUE THREAD

**Issue by edwardhuanghz** [thuml/Time-Series-Library#386]
docker search anaconda3
docker pull continuumio/anaconda3
docker run -it -d --name tsldev  -p 6888:8888 -p 6822:22 -p 6006:6006 -e NVIDIA_DRIVER_CAPABILITIES=compute,utility -e NVIDIA_VISIBLE_DEVICES=all --gpus all -v D:\aidev:/aidev continuumio/anaconda3 /bin/bash
docker exec -it tsldev bash

conda create -n tsldev python=3.8
conda activate tsldev
# conda deactivate
# conda env remove --n tsldev

# 
pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple 

# 
pip install --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple einops

when install mamba_ssm
pip install --upgrade -i https://pypi.tuna.tsinghua.edu.cn/simple einops mamba_ssm
occur a error,see below
**ERROR: Could not build wheels for mamba_ssm, which is required to install pyproject.toml-based projects**

**Comment by listview998** [comment]
It seems that using mamba_ssm currently only supports Linux systems and cannot be used temporarily under Windows. First, you need to check if the system environment is Linux

**Comment by edwardhuanghz** [comment]
I run it on the docker of debian os in window 11

**Comment by 1637936665** [comment]
全局检索mamba，把mamba : mamba模型注释，把导入语句中的mamba删除即可

**Comment by Harryx2019** [comment]
torch版本升高就行

**Comment by Harryx2019** [comment]
pip3 install mamba_ssm 可以装上

**Comment by ztxtech** [comment]
You'd better create a new conda environment without docker and configure a correct mirror of PyPI. Maybe the official mirror of PyPI works.  Then you will know what the problem is.
```shell
# delete the tuna mirror
pip install -r requirements.txt
```

**Comment by wuhaixu2016** [comment]
Hi, many thanks for your discussion. mamba_ssm is not platform-friendly. Thus, we have removed the default usage of Mamba in the latest commit: https://github.com/thuml/Time-Series-Library/commit/2d734a17045419cde6bfe7fc0e7fe99d8ce8d940
If you have some problems about installing mamba_ssm, I think their official repo provides sufficient instructions: https://github.com/mamba-org/mamba
