### ISSUE TITLE
Dimension issue encountered during TimeMixer training  

### ISSUE THREAD

**Issue by listview998** [thuml/Time-Series-Library#388]
--task_name
long_term_forecast
--is_training
1
--root_path
./datasets/xx/
--data_path
data.csv
--model_id
xx_96_1
--model
TimeMixer
--data
custom
--features
M
--seq_len
96
--freq
d
--label_len
48
--pred_len
1
--e_layers
2
--d_layers
1
--factor
3
--enc_in
6
--dec_in
6
--c_out
6
--d_model
256
--d_ff
512
--des
'Exp'
--itr
1
--top_k
5
--train_epochs
100 

The following error was reported when starting training：

 File "D:\BaiduNetdiskDownload\time_serise\tangdi\word\Time-Series-Library-main\models\TimeMixer.py", line 382, in forward
    dec_out_list = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
  File "D:\BaiduNetdiskDownload\time_serise\tangdi\word\Time-Series-Library-main\models\TimeMixer.py", line 322, in forecast
    B, T, N = x.size()
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by kwuking** [comment]
hi, I noticed that your script is missing the parameters for down_sampling_window and down_sampling_layer. You need to choose appropriate parameters based on your input length for configuration.

**Comment by listview998** [comment]
I set the down_sampling_window and down_sampling_layer parameters to 96,1, but the result is still the same with the same error reported

**Comment by listview998** [comment]
> hi, I noticed that your script is missing the parameters for down_sampling_window and down_sampling_layer. You need to choose appropriate parameters based on your input length for configuration.

I set the down_sampling_window and down_sampling_layer parameters to 96,1, but the result is still the same with the same error reported

**Comment by chasethedeer** [comment]
hi, I have the same question, have you solved your problem?

**Comment by J-Collar** [comment]
> > hi, I noticed that your script is missing the parameters for down_sampling_window and down_sampling_layer. You need to choose appropriate parameters based on your input length for configuration.嗨，我注意到您的脚本缺少 down_sampling_window 和 down_sampling_layer 的参数。您需要根据输入长度选择合适的参数进行配置。
> 
> I set the down_sampling_window and down_sampling_layer parameters to 96,1, but the result is still the same with the same error reported我将 down_sampling_window 和 down_sampling_layer 参数设置为 96,1，但结果仍然相同，报告了相同的错误

Hello, have you solved this problem? How did you solve it? Thank you.
