### ISSUE TITLE
time series diagram

### ISSUE THREAD

**Issue by chengsaf** [thuml/Time-Series-Library#389]
![54690f64a544dbff6adbe755d551ac7f](https://github.com/thuml/Time-Series-Library/assets/144492982/1093b047-e51f-4473-8875-10643dbc47ff)
Excuse me, I am willing to know how did you draw this time series diagram from the TimesNet paper?

**Comment by wuhaixu2016** [comment]
We use power point. This figure is just for intuitive understanding.
