### ISSUE TITLE
Why TimsNet doesn't use series decomposition?

### ISSUE THREAD

**Issue by ddz16** [thuml/Time-Series-Library#39]
Great work! But I have a question why TimsNet doesn't use the series decomposition module in Autoformer and other Transformer-based models.

**Comment by ddz16** [comment]
Great work! But I have a question why TimsNet doesn't use the series decomposition module in Autoformer and other Transformer-based models.

**Comment by wuhaixu2016** [comment]
Hi, we have provided an ablation study in Table 9 of Appendix: https://arxiv.org/pdf/2210.02186.pdf
