### ISSUE TITLE
Multivariate regression missing from benchmark

### ISSUE THREAD

**Issue by erickmiller** [thuml/Time-Series-Library#393]
Long/Short Term Forecasting, Imputation, Classification and Anomaly Detection is a great set of task based categorical features to test for all the models. 

But *why* is **Multivariate Regression** missing from this "comprehensive benchmark"?

I would suggest, for the benchmark to be truly comprehensive, the regression task should be part of the benchmark, if this is to be used as a way of ranking and as a standard quality measure for all time series models in the future.

**Comment by wuhaixu2016** [comment]
Hi, many thanks for your suggestion. 
'Multivariate Regression' is important. But to our best knowledge, this task is not well-studies in recent papers of machine learning community.
Would you please kindly give us some related works or benchmarks?
