### ISSUE TITLE
Guidance on Setting Parameters for Univariate Time Series Prediction

### ISSUE THREAD

**Issue by ddwwbb2001** [thuml/Time-Series-Library#394]
Hello,

I am currently working on a project involving univariate time series prediction and I am interested in using TimesNet for my dataset. My dataset is structured similarly to the ETTh1 dataset in terms of length and partitioning.

I would like to ask for your advice on how to configure the model parameters for univariate time series forecasting using my dataset. If there are any specific settings or considerations that I should be aware of, please let me know.

Thank you for your time and assistance.

Best regards,

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interest.
According to my experience, the d_model and d_ff are vital to the final performance. Since you are trying univariate forecasting, you can set them as 16, 16 respectively.
