### ISSUE TITLE
请问同时考虑回归和时序该如何做？

### ISSUE THREAD

**Issue by YuboCoco** [thuml/Time-Series-Library#396]
Features A、B、C、D和Target‘ E强相关，通常建立回归模型就能对E进行预测，如何和时序预测结合起来呢？

**Comment by wuhaixu2016** [comment]
您好，这个也许可以尝试一下我们最新的工作TimeXer（https://arxiv.org/abs/2402.19072），关注斜变量预测问题，可以把E的历史观测设置为0作为placeholder
