### ISSUE TITLE
为什么训练时对预测结果进行逆变换会比不对预测结果进行逆变换的结果要更好。

### ISSUE THREAD

**Issue by chenyufeifei** [thuml/Time-Series-Library#398]
在训练时，对预测结果和真实结果进行逆变换后进行评估，相较于对预测结果和真实结果都不进行逆变换后，预测更加准确，mape的值更加小，画出来的图前者的曲线相较于后者的曲线更加一致，请问这是什么原因

**Comment by wuhaixu2016** [comment]
您好，可以具体讲一下如何做的“逆变换”吗？因为mape是尺度无关的，如果预测和真实使用同样的scale，得到的结果应该是一致的

**Comment by wuhaixu2016** [comment]
哦哦，这个可能涉及一些数值稳定性的问题。如果您是面向工程应用的话，确实需要逆变换。如果是面向学术论文的话，目前的benchmark主要都是经过归一化处理的。
