### ISSUE TITLE
About datasets

### ISSUE THREAD

**Issue by wuhaixu2016** [thuml/Time-Series-Library#4]
We have provided all the datasets in both Google Cloud and Tsinghua Cloud.
Google Cloud: https://drive.google.com/drive/folders/13Cg1KYOlzM5C7K8gK8NfC-F3EYxkM3D2
Tsinghua Cloud: https://cloud.tsinghua.edu.cn/f/84fbc752d0e94980a610/

**Comment by Ritikkhulbe** [comment]
@wuhaixu2016 what's the issue here?

**Comment by wuhaixu2016** [comment]
Someone have asked us how to download the data by email. We create this for clarification.

**Comment by alessandro-crescenzi** [comment]
I noticed that Electricity and Traffic available datasets in Google Drive are quite different from those you cited in the paper. Are they shifted in terms of date or modified in some way or they are completely different datasets?
