### ISSUE TITLE
The scripts for running DLinear, ETSformer, FEDformer, Informer and LightTS on ETTh2, ETTm1, ETTm2 are missing

### ISSUE THREAD

**Issue by xiao-he** [thuml/Time-Series-Library#40]
https://github.com/thuml/Time-Series-Library/tree/main/scripts/long_term_forecast/ETT_script

**Comment by xiao-he** [comment]
scripts for Exchange, ILI, Traffic, Weather are also missing

**Comment by wuhaixu2016** [comment]
Hi, these scripts are still under-tuning. 

We want to find the best hyperparameters for these methods. We will keep updating this repo.

**Comment by xiao-he** [comment]
It would be nice to also provide the scripts for hypter-parameters tunning.
