### ISSUE TITLE
在使用单变量天频时间序列数据进行预测时，应该如何学习节假日特征？

### ISSUE THREAD

**Issue by Alamoooooooo** [thuml/Time-Series-Library#402]
您好！
目前我在使用一个时间范围2020-2024年的**天频单变量时间序列**进行预测，预测目标是**未来1个月的每天的数值**。**此时间序列对节假日有明显规律**（包括双休日/节日）。
我使用了ITransformer和TimesNet，并适当造了一些有关节假日特征和时间特征（年/月/日/周等）。但实际预测结果并没有显示出model学习到了任何有关节日的信息T .T，甚至不如单变量只输入时间序列值。
此前我使用同一套特征在LGB中进行预测，模型对于节日非常敏感，效果较好。

请问您有针对天频单变量时间序列进行预测时，对节假日规律进行调优的经验可以分享吗？或讨论区有大佬愿意分享想法，也感激不尽><

**Comment by wuhaixu2016** [comment]
您好，这个问题我觉得可能取决于数据量，因为5年的数据只有1000多个时间点，所以对于timesnet/transformer这类模型来说，数据是不充足的。我觉得可以尝试使用我们最新的TimeMixer：https://github.com/thuml/Time-Series-Library/blob/main/models/TimeMixer.py。
