### ISSUE TITLE
请教一些数据集和batch相关问题

### ISSUE THREAD

**Issue by yuanshuaiLK** [thuml/Time-Series-Library#403]
你好，我准备使用Timesnet对心电数据进行时序预测，我发现源码里的训练数据好像是一条时序数据，但是我的心电数据集是几千条不同患者的数据，每条数据长度9000，在data_loader中设置的batch_size是对一条时序数据的吗？如果我想对我的不同数据组batch应该怎样修改？

**Comment by wuhaixu2016** [comment]
您好，对于这个数据可以首先随机一条患者的资料，然后再在9000个时间点中采样一段时间序列作为batch。
