### ISSUE TITLE
einops 0.4.0 cause the error: ImportError: cannot import name 'einsum' from 'einops'

### ISSUE THREAD

**Issue by ipe-zhangyz** [thuml/Time-Series-Library#405]
after setting up the environment by "pip install -r requirements.txt" and executing "bash ./scripts/long_term_forecast/ETT_script/TimesNet_ETTh1.sh", there is an error:
ImportError: cannot import name 'einsum' from 'einops' 
requirements.txt requires to install einops 0.4.0, while there is no module named einsum in that version of einops.
Update einops to 0.5.0 solves this problem.
Maybe the requirements.txt file need to be updated.

**Comment by tibeler** [comment]
BUT when i install einops=0.5.0, it cause mamba_ssm error ,there will be no mamba_ssm error

**Comment by stone-cloud** [comment]
I think so, 

> after setting up the environment by "pip install -r requirements.txt" and executing "bash ./scripts/long_term_forecast/ETT_script/TimesNet_ETTh1.sh", there is an error: ImportError: cannot import name 'einsum' from 'einops' requirements.txt requires to install einops 0.4.0, while there is no module named einsum in that version of einops. Update einops to 0.5.0 solves this problem. Maybe the requirements.txt file need to be updated.

**Comment by ipe-zhangyz** [comment]
according to the README, mamba_ssm need to be installed manually:
News (2024.04) Many thanks for the great work from https://github.com/thuml/Time-Series-Library/pull/378. The famous sequenctial model [Mamba](https://arxiv.org/abs/2312.00752) has been included in our library. See [this file](https://github.com/thuml/Time-Series-Library/blob/main/models/Mamba.py), where you need to install mamba_ssm with pip at first.

**Comment by wuhaixu2016** [comment]
@ipe-zhangyz Many thanks for your answer~

**Comment by woshiliyue** [comment]
Can you change to tagging without running the mamba module？

**Comment by Duykhongkhoc** [comment]
@ipe-zhangyz can you show me the way to install mamba_ssm manually. I tried by: pip install mamba-ssm. But built wheel fail by output: ModuleNotFoundError: No module named 'packaging'. Inspite I have install the packaging:
pip list
Package    Version
---------- -------
packaging  24.0
pip        24.0
setuptools 70.0.0

**Comment by ipe-zhangyz** [comment]
> @ipe-zhangyz can you show me the way to install mamba_ssm manually. I tried by: pip install mamba-ssm. But built wheel fail by output: ModuleNotFoundError: No module named 'packaging'. Inspite I have install the packaging: pip list Package Version
> 
> packaging 24.0 pip 24.0 setuptools 70.0.0

Sorry for the late reply. I didn't install mamba-ssm myself. I just learnt from the Readme of this repo that it need to be installed manually.

**Comment by liurambler** [comment]
> I think so,
> 
> > after setting up the environment by "pip install -r requirements.txt" and executing "bash ./scripts/long_term_forecast/ETT_script/TimesNet_ETTh1.sh", there is an error: ImportError: cannot import name 'einsum' from 'einops' requirements.txt requires to install einops 0.4.0, while there is no module named einsum in that version of einops. Update einops to 0.5.0 solves this problem. Maybe the requirements.txt file need to be updated.

quite useful
