### ISSUE TITLE
如何使用timesnet将多元时序变量预测为一个回归值

### ISSUE THREAD

**Issue by xiaoanshi** [thuml/Time-Series-Library#410]
您好，非常感谢您们的优秀工作，我们想基于timesnet做应用。
我们的输入有多个时间序列变量（时间戳对齐），输出预测一个回归值。
请问如何基于timesnet来做呢？需要哪些修改代码，增加哪些功能吗？

我们做修改时，您有什么推荐的参考代码和文献吗？

**Comment by kwuking** [comment]
听起来像是协变量预测的工作，可以参考[TimeXer: Empowering Transformers for Time Series Forecasting with Exogenous Variables](https://arxiv.org/abs/2402.19072)

**Comment by wuhaixu2016** [comment]
@kwuking 感谢解答，可以参考TimeXer的做法实现
