### ISSUE TITLE
Something wrong when I set the inverse as True

### ISSUE THREAD

**Issue by 534145232** [thuml/Time-Series-Library#413]
当我把Inverse改成True之后，报了这个错误，请问应该怎么办呢
我的输出维度是（64，6，1）
![image](https://github.com/thuml/Time-Series-Library/assets/30302418/e1f05550-12f5-4ad9-9bb5-0316610a97b7)

**Comment by Confusedfish** [comment]
I too have this problem. I am not sure if it because the results are batched (in your case a batch of 64?) so it can't use squeeze to get a single record to invert? Do we need to iterate over the batch of results somehow and call inverse_transform once per result?

**Comment by Chuan112233** [comment]
我运行itransformer时，把inverse也遇到了，就是想反标准化嘛，请问你解决这个问题了吗？

**Comment by wuhaixu2016** [comment]
Many thanks for pointing out this issue. We have fixed it in the latest commit: https://github.com/thuml/Time-Series-Library/commit/20eff0e8abc907c14857f4b4d1700d0f3a04ceb5

**Comment by Chuan112233** [comment]
您好，我是在您GitHub上开源代码time-seies-library跑的程序用itransformer跑的，用我的数据集跑的，为什么验证集的损失会低于训练集的呀？每10次迭代就早停退出了，只需要迭代这么少吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月14日(星期天) 中午12:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [thuml/Time-Series-Library] Something wrong when I set the inverse as True (Issue #413)














 
Many thanks for pointing out this issue. We have fixed it in the latest commit: 20eff0e
