### ISSUE TITLE
data_loader.py中的数据标准化问题

### ISSUE THREAD

**Issue by tjnkyqcy** [thuml/Time-Series-Library#414]
data_loader.py文件中：
 if self.scale:   
            train_data = df_data[border1s[0]:border2s[0]]
            self.scaler.fit(train_data.values)    
            data = self.scaler.transform(df_data.values)  
为什么只对训练数据train_data 计算标准化参数，而用这些参数对全体数据df_data进行了标准化？难道不是用全体数据计算fit然后对全体数据进行标准化么？

**Comment by ztxtech** [comment]
因为模型拟合的训练集。如果按照全体数据集标准化，标准化参数改变，模型拟合效果变差，因为不是拟合的不是一个函数。
