### ISSUE TITLE
数据处理脚本

### ISSUE THREAD

**Issue by sunxia2333** [thuml/Time-Series-Library#415]
hi，感谢作者的工作，能否提供你们对开源数据的处理脚本，例如对于SMD数据集，原始数据是machine-group-index.txt格式的数据，如何转化成你们代码接口中的.npy格式，对于新入时间序列分析的来说不是很明白，感谢！！

**Comment by ztxtech** [comment]
这种肯定得自己适配一个脚本读取txt，因为原始的数据集并没有统一的格式标准。npy是numpy的格式，直接save就好了。（我不是作者）
