### ISSUE TITLE
如何更改程序实现回归预测呢

### ISSUE THREAD

**Issue by xinzhichao** [thuml/Time-Series-Library#417]

**Comment by ztxtech** [comment]
回归预测怎么定义的

**Comment by ztxtech** [comment]
（我不是repo的作者）可以修改dataloader,把映射进行修改就行。但这种本身预测模式发生变化，未必效果会好。而且在部分模型参数敏感的条件下，得重新确定合适的参数。

**Comment by xinzhichao** [comment]
大哥，我能多请教一下：  --seq_len 96 \  --label_len 48 \ --pred_len 96 \，在这种时间预测模型中，这三个参数都具有什么意义吗，因为在我做回归预测的时候，data就是我输入的因变量（长度假设为50），label就是房价（长度为1），pred就是预测的一个房价（长度为1）。但是这里的label和pred数值是不一样的

**Comment by ztxtech** [comment]
这里肯定是得修改的呀。具体这个的意思你可以去参考run.py，作者对每个参数进行了解释的。

**Comment by wuhaixu2016** [comment]
@ztxtech 感谢解答，关于回归预测，也可以参考我们最近的工作TimeXer：https://arxiv.org/abs/2402.19072

**Comment by badfish2019** [comment]
请问有源码么

> @ztxtech 感谢解答，关于回归预测，也可以参考我们最近的工作TimeXer：https://arxiv.org/abs/2402.19072
