### ISSUE TITLE
Add MOMENT to the library

### ISSUE THREAD

**Issue by mononitogoswami** [thuml/Time-Series-Library#418]
Hi, 
Thanks for your excellent library! I am one of the co-authors of [MOMENT](https://arxiv.org/abs/2402.03885), a foundation model for time series data. I am one of the co-authors, and I would love to integrate it into the library if you all are interested. We already have an implementation [here](https://anonymous.4open.science/r/BETT-773F/README.md) and [here](https://github.com/moment-timeseries-foundation-model/moment).

**Comment by wuhaixu2016** [comment]
Hi Mononito, it is glad to see your message. I have read MOMENT, which is a wonderful work. There is no doubt that the developing trend for time series is large models. 

However, the pretrain-finetuning paradigm is kind of different from the pipeline of the current design of TSLib. Our team is still thinking about how to organize the recent large-time-series models in a simple and neat way. If we get some conclusions, we will reach you and be happy to include our work.

FYI: You may find the latest work of our lab interesting: https://github.com/thuml/Large-Time-Series-Model , which is also accepted by ICML 2024.
