### ISSUE TITLE
关于短序列预测

### ISSUE THREAD

**Issue by ZHE0725** [thuml/Time-Series-Library#42]
您好！我在TimesNet长期时间序列的预测上效果很好，请问我怎样在TimesNet模型上使用自己的数据集做短期的时间序列预测呢？
为此我具体需要怎样修改代码？

**Comment by wuhaixu2016** [comment]
您好，感谢关注

目前的TSlib中短序列预测是针对M4这个数据集来写的，如果您想使用自己的数据集，可以如下操作

（1）先按照ETTh1.csv的格式整理数据

（2）使用Dataset_Custom作为数据加载类（https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py）

（3）使用long-term-forecasting的exp文件（https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_long_term_forecasting.py）

（4）将seq_len、label_len、pred_len改为你需要的数值

**Comment by ZHE0725** [comment]
> 您好，感谢关注
> 
> 目前的TSlib中短序列预测是针对M4这个数据集来写的，如果您想使用自己的数据集，可以如下操作
> 
> （1）先按照ETTh1.csv的格式整理数据
> 
> （2）使用Dataset_Custom作为数据加载类（[https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py）](https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py%EF%BC%89)
> 
> （3）使用long-term-forecasting的exp文件（[https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_long_term_forecasting.py）](https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_long_term_forecasting.py%EF%BC%89)
> 
> （4）将seq_len、label_len、pred_len改为你需要的数值

我的问题的性质大致是短序列预测（数据在1小时内采集完毕），使用长序列预测的方法得到的结果是否科学正确呢？
