### ISSUE TITLE
dataloder的shuffle问题

### ISSUE THREAD

**Issue by LeqiGu** [thuml/Time-Series-Library#420]
作者你好  为什么data_factory.py中对trainloader的shuffle设置为True  但是我发现在运行TimesNet的长期预测任务的时候，每次数据输出的顺序都是相同的，似乎shuffle没有起作用  这是为什么？ 谢谢！

**Comment by wuhaixu2016** [comment]
您好，data loader的shuffle是指每次epoch内部数据的随机性。不同实验轮次之间的数据顺序应该是由程序的随机性决定的。
