### ISSUE TITLE
PatchTST. No self-supervised?

### ISSUE THREAD

**Issue by well0203** [thuml/Time-Series-Library#422]
Hi, again, many thanks for your work.
I wanted to ask whether you plan to add self-supervised setting to PatchTST? From paper authors received best results due to this setting.

**Comment by wuhaixu2016** [comment]
Hi, in this repo, we only focus on the deep model architecture. Thus, we do not have a plan to include the pre-training stage in our repo. But you may find some useful pre-training code here: https://github.com/thuml/SimMTM, which is based on vanilla Transformer.
