### ISSUE TITLE
difference between long_term_forecasting and short_term_forecasting in this library

### ISSUE THREAD

**Issue by ipe-zhangyz** [thuml/Time-Series-Library#423]
What is the essential difference between exp_long_term_forecasting.py and exp_short_term_forecasting.py? Seems that the exp_short_term_forecasting.py is only for adapting to the M4 dataset? Can I use **--task_name long_term_forecast** with a relative small pred_len to do short term forecast in this library?

**Comment by wuhaixu2016** [comment]
Yes, you are right. short_term_forecasting is only for M4. You can change the pred_len in long_term_forecast for the 'short-term' experiments.

**Comment by ipe-zhangyz** [comment]
Thanks ~
