### ISSUE TITLE
How does the model learn seasonal patterns?

### ISSUE THREAD

**Issue by ipe-zhangyz** [thuml/Time-Series-Library#428]
The default seq_len of ETTh1 dataset is 96， which equals to 4 days.  Every step the model takes a batch of 4-day-long time series as input and learns the patterns contained in them and makes some predictions of the future. I wonder how the model learns seasonal patterns, which is only obvious in a term much longer than 4 days.

**Comment by wuhaixu2016** [comment]
Hi, the seasonal pattern can be learned by absolute time embedding: https://github.com/thuml/Time-Series-Library/blob/main/utils/timefeatures.py 
But in practice, I am also doubt that the performance under limited inputs. Maybe long-input models should be explored more.
