### ISSUE TITLE
how to use own dataset?

### ISSUE THREAD

**Issue by fiksdano** [thuml/Time-Series-Library#43]
首先非常感谢作者的分享，这边有几个问题想请教一下你。
1、我想把ETTh数据集替换成我自己的数据集，我的数据集特征如下图，单变量预测单变量，请问我需要做哪些工作呢？
![微信图片_20230314160431](https://user-images.githubusercontent.com/127064182/224935070-f5d741e4-745e-4541-bfe8-123851c33669.png)
我试图尝试调整了一些参数，把TimesNet_ETTh1.sh，run.py,data_loader.py这三个文件中的feature从M改成了S，随后变直接把自己的数据集放进去，因此出现了以下的错误。
![微信图片_20230314161526](https://user-images.githubusercontent.com/127064182/224937693-1b146c8d-fdd8-45d4-8b27-9dd9a8e9b6e8.jpg)

**Comment by wuhaixu2016** [comment]
您好，您提供的excel中的表头写的是`data`，需要改为`date`

**Comment by Et6an** [comment]
您好，想问一下TimesNet如何做数据集以外的未来预测，运行源码的时候没有找到类似informer中的do_predict命令
