### ISSUE TITLE
异常检测的f1分数虚高太多

### ISSUE THREAD

**Issue by dayu-chen** [thuml/Time-Series-Library#430]
我没有改变原论文任何参数和代码，只是在最后测试的时候，没有对真实值和预测值使用原代码中的点调整函数，最后跑了十轮的f1-score只有百分之三十多，而用了点调整后f1-score就可以达到九十多。关于点调整策略，许多论文也指出它的使用会使得检测结果存在虚假值的现象。但是这三十多与九十多的结果值实在差距太大！这是不是说明原论文的异常检测效果实际没有那么好？

**Comment by wuhaixu2016** [comment]
这个的讨论可以见：https://github.com/thuml/Anomaly-Transformer/issues/14
一个朴素的理解是，您可以认为adjustment下模型不是point-wise的检测，而是event-wise的检测。

**Comment by dayu-chen** [comment]
> 这个的讨论可以见：[thuml/Anomaly-Transformer#14](https://github.com/thuml/Anomaly-Transformer/issues/14) 一个朴素的理解是，您可以认为adjustment下模型不是point-wise的检测，而是event-wise的检测。



> 这个的讨论可以见：[thuml/Anomaly-Transformer#14](https://github.com/thuml/Anomaly-Transformer/issues/14) 一个朴素的理解是，您可以认为调整下模型不是point-wise的检测，而是event-wise的检测。

明白了，感谢大佬的回复！
