### ISSUE TITLE
尊敬的作者您好，我在short_term_forecast预测使用M4数据时遇到了这些问题：

### ISSUE THREAD

**Issue by warmful-sun** [thuml/Time-Series-Library#432]
我使用的是其中一个数据集：
![QQ截图20240610163027](https://github.com/thuml/Time-Series-Library/assets/164287695/674b6e20-fc31-482a-a66c-2b636c2efb8b)
但是为什么在跑程序的时候数据集那么大呢，这与我使用的数据集数据严重不符，是哪里我理解错误了吗？
![QQ截图20240610163156](https://github.com/thuml/Time-Series-Library/assets/164287695/d6f5e4fe-6f8f-4427-958e-a75ab82c7b95)
请指点迷津，再次感谢！！

**Comment by wuhaixu2016** [comment]
您好，我没有理解您的问题，具体M4的训练请见：https://github.com/thuml/Time-Series-Library/blob/main/scripts/short_term_forecast/Autoformer_M4.sh，我们的数据集是从N-BEATS拿到的

**Comment by wuhaixu2016** [comment]
您好，我觉得您的问题可以通过使用默认脚本解决。请见上一个回答
