### ISSUE TITLE
About the details of datasets

### ISSUE THREAD

**Issue by deepcomp2023** [thuml/Time-Series-Library#435]
Hi,

I've downloaded the all_datasets.zip from cloud you mentioned in readme, while where can I get detailed information about the dataset? For example, the traffic.csv under traffic folder seems nor attached readme file neither ref link, but every line is composed from hundreds fields. 

Hope to get reply soon. Thanks a lot. 

David

**Comment by wuhaixu2016** [comment]
Hi, we include the dataset description in our previous paper: Autoformer

https://arxiv.org/pdf/2106.13008
