### ISSUE TITLE
TimeMixer代码运行报错

### ISSUE THREAD

**Issue by yyqRua** [thuml/Time-Series-Library#441]
用custom数据（输入15时间步长*10个变量，预测15时间步长*10个变量）运行TimeMixer模型时出现以下报错：
`Traceback (most recent call last):
  File "F:\tsp\methods\thmul_202406\run.py", line 189, in <module>
    exp.train(setting)
  File "F:\tsp\methods\thmul_202406\exp\exp_long_term_forecasting.py", line 136, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
  File "D:\anaconda\envs\thmul\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\tsp\methods\thmul_202406\models\TimeMixer.py", line 382, in forward
    dec_out_list = self.forecast(x_enc, x_mark_enc, x_dec, x_mark_dec)
  File "F:\tsp\methods\thmul_202406\models\TimeMixer.py", line 354, in forecast
    dec_out_list = self.future_multi_mixing(B, enc_out_list, x_list)
  File "F:\tsp\methods\thmul_202406\models\TimeMixer.py", line 368, in future_multi_mixing
    dec_out = dec_out.reshape(B, self.configs.c_out, self.pred_len).permute(0, 2, 1).contiguous()
RuntimeError: shape '[32, 1, 15]' is invalid for input of size 4800`

以下为运行参数配置：
`Args in experiment:
Basic Config
  Task Name:          long_term_forecast  Is Training:        1                   
  Model ID:           cfg5                Model:              TimeMixer           

Data Loader
  Data:               custom              Root Path:          ./dataset/yr/       
  Data Path:          df_zk.csv           Features:           MS                  
  Target:             chlorophyll         Freq:               d                   
  Checkpoints:        ./checkpoints/      

Forecasting Task
  Seq Len:            15                  Label Len:          0                   
  Pred Len:           15                  Seasonal Patterns:  Monthly             
  Inverse:            0                   

Model Parameters
  Top k:              5                   Num Kernels:        6                   
  Enc In:             10                  Dec In:             10                  
  C Out:              1                   d model:            32                  
  n heads:            8                   e layers:           2                   
  d layers:           1                   d FF:               32                  
  Moving Avg:         25                  Factor:             3                   
  Distil:             1                   Dropout:            0.1                 
  Embed:              timeF               Activation:         gelu                
  Output Attention:   0                   

Run Parameters
  Num Workers:        10                  Itr:                1                   
  Train Epochs:       10                  Batch Size:         32                  
  Patience:           3                   Learning Rate:      0.003               
  Des:                'Exp'               Loss:               MSE                 
  Lradj:              type1               Use Amp:            0                   

GPU
  Use GPU:            0                   GPU:                0                   
  Use Multi GPU:      0                   Devices:            0,1,2,3             

De-stationary Projector Params
  P Hidden Dims:      128, 128            P Hidden Layers:    2    `
debug了很久，感觉是TimeMixer.py中第327行导致维度出现了问题：
`x_mark = x_mark.repeat(N, 1, 1)`
请问各位大佬应该如何修改呢

**Comment by wuhaixu2016** [comment]
您好，我觉得是这个设置的问题`Features: MS`，可以替换为M看看

**Comment by intothesea** [comment]
确实有这个问题，然而我的数据集就需要是MS而不是M，多元预测单元，其他列是已知项
