### ISSUE TITLE
dataset - SWAT/MSL

### ISSUE THREAD

**Issue by tribeband** [thuml/Time-Series-Library#443]
in data_loader.py line 452, why the test data lable is used as the train data label?

if self.flag == "train":
            return np.float32(self.train[index:index + self.win_size]), np.float32(self.test_labels[0:self.win_size])
        elif (self.flag == 'val'):
            return np.float32(self.val[index:index + self.win_size]), np.float32(self.test_labels[0:self.win_size])

**Comment by wuhaixu2016** [comment]
The returned test labels will not be used in training. So, you can just ignore the return.
https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_anomaly_detection.py#L86C30-L108
