### ISSUE TITLE
请问能否进行多序列multiple series预测？

### ISSUE THREAD

**Issue by lyzltysgithub** [thuml/Time-Series-Library#444]
当我设置features为M时，似乎是多变量预测（Multivariate Series），而我想要进行多序列预测（Multiple Series）
举个例子，假如我有10个门店的鞋子销量，每条时间序列包含一些协变量(天气、温度、总货物销量等)，我能否进行多序列预测？
也就是说我的时间序列除了时间戳外，还有item_id，同时进行多时间序列预测？谢谢，期待您的回复

**Comment by lyzltysgithub** [comment]
多序列预测的话就不需要每一条序列都训练一个model，因为我大概有上万个item_id种类的时间序列，我想要实现多序列预测，也就是被称为"global model"，据我所知，BlockRNNModel
Temporal Convolutional Networks (TCNModel)
N-Beats (NBEATSModel)
TiDEModel均可以进行多序列预测

**Comment by wuhaixu2016** [comment]
您好，您的问题我理解为带有斜变量的多变量预测，您可以使用MS setting，但是更新 https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_long_term_forecasting.py#L139-L140

**Comment by Yewx0310** [comment]
我也有同样的问题请问您解决了么
