### ISSUE TITLE
运行Nonstationary_Transformer报维度错误

### ISSUE THREAD

**Issue by nizhenliang** [thuml/Time-Series-Library#449]
The size of tensor a (25) must match the size of tensor b (24) at non-singleton dimension 1

**Comment by WenWeiTHU** [comment]
Hello, thank you for your comment, but could you please provide some more detailed information, such as the name of the script you executed, relevant configurations, and error location?

**Comment by wuhaixu2016** [comment]
Hi, we have tried to run the default scripts of Non-stationary Transformer and there is no error. If you are using your own dataset, you should check the hyperparameters such as https://github.com/thuml/Time-Series-Library/blob/main/run.py#L66
