### ISSUE TITLE
TimesNet runs slowly as num_kernels grows

### ISSUE THREAD

**Issue by Songweiping** [thuml/Time-Series-Library#45]
Hi,

Great work and thanks for releasing so many benchmark models. 
On my own dataset, I find that the training speed is decent when the num_kernels is set to 1. However, as I increase the num_kernels to 6 (default number in Inception net), the training speed is extremly slow. FYI, I use torch 1.11 and NVIDIA A100 GPU. There are two questions:
1. Do you have any idea why inception net runs slowly by using 6 kernels? Does this happen in your tasks?
2. Can I just use 1 or 2 kernels in time series analysis? I didn't find the ablation study about num_kernels in your paper (maybe I miss them).

**Comment by wuhaixu2016** [comment]
Hi, thanks for your detailed experiments. We will run some ablation experiments and reply soon.

**Comment by tenmds** [comment]
https://github.com/thuml/Time-Series-Library/issues/45#issue-1624671051 
你好，我想问一下你的数据集是多大的，我的数据训练得非常慢，不知道是不是数据集太大了

**Comment by wuhaixu2016** [comment]
Hi, reducing kernel numbers is fine. You can also use small kernels.
