### ISSUE TITLE
TimeMixer Tensor Size Runtime Error

### ISSUE THREAD

**Issue by IanBluth** [thuml/Time-Series-Library#450]
Hello, thank you all for effort in updating and maintaining this repository. I have been comparing the performance of a few of your models on a custom dataset and have run into issues training the TimeMixer which was updated 4 days ago. The issue arises within forward function of the 'DataEmbedding_wo_pos' class where the value embedding and temporal embedding arrays are added together. The size of the tensors do not match in position 0 causing the following runtime error:

"RuntimeError: The size of tensor a (x) must match the size of tensor b (y) at non-singleton dimension 0"

I tried altering the code to resize tensor b to match tensor a but this created size incompatibilities further along. I'm hesitant to change much else because I've trained and evaluated a few of your other models without issues. If there is any more information I can provide to help resolve this please let me know.

**Comment by wuhaixu2016** [comment]
Hi, we have tried this script https://github.com/thuml/Time-Series-Library/blob/main/scripts/long_term_forecast/ETT_script/TimeMixer_ETTh1.sh
and no error occurs. Would you please detail the script that you experimented with?

**Comment by wuhaixu2016** [comment]
Hi, I think this problem is caused by the mismatched input length and temporal information of your task. You can try our default scripts.
