### ISSUE TITLE
Dataset_Custom scaler user different data on  self.scaler.fit and scaler transform

### ISSUE THREAD

**Issue by laowalter** [thuml/Time-Series-Library#452]
data_provider/data_loader.py : 263   
```
        if self.scale:
            train_data = df_data[border1s[0]:border2s[0]]
            self.scaler.fit(train_data.values)
            data = self.scaler.transform(df_data.values)
        else:
            data = df_data.values
```

self.scaler.fit and scaler transform use different data.

**Comment by wuhaixu2016** [comment]
Hi, this design means that we calculate the data statistics from training data and adopt them to transform the complete dataset, which can avoid the test data leakage.

**Comment by laowalter** [comment]
> Hi, this design means that we calculate the data statistics from training data and adopt them to transform the complete dataset, which can avoid the test data leakage.

Thanks.
