### ISSUE TITLE
Error reshaping prediction shape

### ISSUE THREAD

**Issue by MarigoldDrift** [thuml/Time-Series-Library#454]
I was running the long-term-forecasting script and came across this error.

        test 9820
        test shape: (307,) (307,)
        Traceback (most recent call last):
            File "run.py", line 194, in <module>
            exp.test(setting)
            File "/home/an/桌面/Projects/iTransformer/exp/exp_long_term_forecasting.py", line 247, in test
            preds = preds.reshape(-1, preds.shape[-2], preds.shape[-1])
        IndexError: tuple index out of range

I have not modified the code or the dataset. I tried running other forecasting scripts and encountered the same error. 
The pdf files generated show normal forecasting results.
Is there anything I can do to resolve this?

**Comment by WenWeiTHU** [comment]
It seems that the dataset is univariate. Can you provide the detailed script configurations and dataset descriptions to help us resolve this?

**Comment by wolfComing99** [comment]
drop_last = true

**Comment by MarigoldDrift** [comment]
I used the script
`bash ./scripts/long_term_forecast/ETT_script/TimesNet_ETTh1.sh`
The detailed script configurations are as follows:
    export CUDA_VISIBLE_DEVICES=0

    model_name=TimesNet

    python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/ETT-small/ \
    --data_path ETTh1.csv \
    --model_id ETTh1_96_96 \
    --model $model_name \
    --data ETTh1 \
    --features M \
    --seq_len 96 \
    --label_len 48 \
    --pred_len 96 \
    --e_layers 2 \
    --d_layers 1 \
    --factor 3 \
    --enc_in 7 \
    --dec_in 7 \
    --c_out 7 \
    --d_model 16 \
    --d_ff 32 \
    --des 'Exp' \
    --itr 1 \
    --top_k 5 \



    python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/ETT-small/ \
    --data_path ETTh1.csv \
    --model_id ETTh1_96_192 \
    --model $model_name \
    --data ETTh1 \
    --features M \
    --seq_len 96 \
    --label_len 48 \
    --pred_len 192 \
    --e_layers 2 \
    --d_layers 1 \
    --factor 3 \
    --enc_in 7 \
    --dec_in 7 \
    --c_out 7 \
    --d_model 16 \
    --d_ff 32 \
    --des 'Exp' \
    --itr 1 \
    --top_k 5


    python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/ETT-small/ \
    --data_path ETTh1.csv \
    --model_id ETTh1_96_336 \
    --model $model_name \
    --data ETTh1 \
    --features M \
    --seq_len 96 \
    --label_len 48 \
    --pred_len 336 \
    --e_layers 2 \
    --d_layers 1 \
    --factor 3 \
    --enc_in 7 \
    --dec_in 7 \
    --c_out 7 \
    --d_model 16 \
    --d_ff 32 \
    --des 'Exp' \
    --itr 1 \
    --top_k 5


    python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/ETT-small/ \
    --data_path ETTh1.csv \
    --model_id ETTh1_96_720 \
    --model $model_name \
    --data ETTh1 \
    --features M \
    --seq_len 96 \
    --label_len 48 \
    --pred_len 720 \
    --e_layers 2 \
    --d_layers 1 \
    --factor 3 \
    --enc_in 7 \
    --dec_in 7 \
    --c_out 7 \
    --d_model 16 \
    --d_ff 32 \
    --des 'Exp' \
    --itr 1 \
    --top_k 5
The only thing I changed is the first line by changing 
`export CUDA_VISIBLE_DEVICES=2`
to
`export CUDA_VISIBLE_DEVICES=0`

The dataset was downloaded from Google Drive, and the first few rows look like this
`    date,HUFL,HULL,MUFL,MULL,LUFL,LULL,OT
    2016-07-01 00:00:00,5.827000141143799,2.009000062942505,1.5989999771118164,0.4620000123977661,4.203000068664552,1.3400000333786009,30.5310001373291
    2016-07-01 01:00:00,5.692999839782715,2.075999975204468,1.4919999837875366,0.4259999990463257,4.142000198364259,1.371000051498413,27.78700065612793
    2016-07-01 02:00:00,5.1570000648498535,1.741000056266785,1.2790000438690186,0.35499998927116394,3.776999950408936,1.218000054359436,27.78700065612793
    2016-07-01 03:00:00,5.0900001525878915,1.9420000314712524,1.2790000438690186,0.3910000026226044,3.806999921798706,1.2790000438690186,25.04400062561035`

**Comment by wuhaixu2016** [comment]
Hi, we have fixed this problem in the latest commit: https://github.com/thuml/Time-Series-Library/pull/458
