### ISSUE TITLE
TimeXer是往因子挖掘上靠了吗

### ISSUE THREAD

**Issue by 666-will** [thuml/Time-Series-Library#455]
目前主要用条件因素来提升模型能力的时序模型不太常见。这一次是搞特征工程，下一步会不会就要上因子挖掘了来搞因果时序了呢，期待

**Comment by WenWeiTHU** [comment]
Thanks a lot for your interest in our work. We will be happy to see this work in the relevant applications.

**Comment by 666-will** [comment]
哥，都是中国人了就不必说英文了嘞

**Comment by 666-will** [comment]
> Thanks a lot for your interest in our work. We will be happy to see this work in the relevant applications.
哥，都是中国人了就不必说英文了嘞
