### ISSUE TITLE
How to calculate flops or params?

### ISSUE THREAD

**Issue by Et6an** [thuml/Time-Series-Library#456]
I tried using ptflops in Exp_long but failed.

**Comment by wuhaixu2016** [comment]
Hi, I usually use 
https://github.com/thuml/Transolver/blob/main/PDE-Solving-StandardBenchmark/exp_airfoil.py#L39 for params and https://github.com/MrYxJ/calculate-flops.pytorch for flops

**Comment by Et6an** [comment]
Thanks a lot！
