### ISSUE TITLE
'Namespace' object has no attribute 'frequency_map'

### ISSUE THREAD

**Issue by xcf11111** [thuml/Time-Series-Library#46]

**Comment by wuhaixu2016** [comment]
Hi, can you specify the running scripts or provide a snapshot for the program error.

**Comment by wuhaixu2016** [comment]
I think it may comes from the mismatched pytorch version. You can try pytorch 1.7.1

**Comment by gengshaoyang** [comment]
I also met this problem, and my pytorch version is 1.7.1.
![Uploading Snipaste_2023-04-12_09-08-26.jpg…]()

**Comment by gengshaoyang** [comment]
The cause of this problem is the mismatch between task_name and data

**Comment by lavender-ER** [comment]
> The cause of this problem is the mismatch between task_name and data
老哥，你好，请问在预测时，能对真实值进行异常处理或者去噪声吗？我看有的论文的数据貌似做了平滑操作，如果可以，大概可以处理到什么程度，（太过了就感觉失真了）

**Comment by xcf11111** [comment]
> I think it may comes from the mismatched pytorch version. You can try pytorch 1.7.1

thanks
