### ISSUE TITLE
有关MS问题的解释

### ISSUE THREAD

**Issue by TianlinZhang668** [thuml/Time-Series-Library#461]
针对MS预测，我是小白，不知道我理解的场景对不对。
给定 ABCD时刻 的每时刻4个变量 预测 ABCD 的一个OT值么，还是 预测后面 EFG 的OT值？     OT的预测只会参考4个变量么，不会参考之前预测的OT么？

万分感谢您能够解答！

**Comment by wang-lucy** [comment]
MS预测的输入是历史多变量数据，即ABCD时刻的（4个变量+OT）的数据信息，得到的输出是EFG时刻的OT预测值。
