### ISSUE TITLE
关于TIMEsnet异常检测SMD数据集的问题

### ISSUE THREAD

**Issue by Uncle-George-13** [thuml/Time-Series-Library#463]
我想问一下作者，SMD数据集应用在异常检测是把所有机器的数据都跑实验了嘛

**Comment by wuhaixu2016** [comment]
你好，SMD由这篇论文收集（https://netman.aiops.org/wp-content/uploads/2019/08/OmniAnomaly_camera-ready.pdf ），我们完整follow了这篇工作的数据集，所以我认为是包含所有机器的数据
