### ISSUE TITLE
关于 checkpoint

### ISSUE THREAD

**Issue by qq1029337471** [thuml/Time-Series-Library#464]
为什么每次用一个模型预测完换一个模型 这个文件就不会再生成 会报错

**Comment by wuhaixu2016** [comment]
您好，具体是如何运行的程序呢？可以提供一些更加详细的描述吗

**Comment by wuhaixu2016** [comment]
非常抱歉，这个issue我没有复现，因为较长时间没有得到问题的更新，所以我关掉了此issue

**Comment by qq1029337471** [comment]
你好 我已经解决了 谢谢你的回复
