### ISSUE TITLE
关于没有真实OT值的预测

### ISSUE THREAD

**Issue by kukimika** [thuml/Time-Series-Library#465]
作者您好，exp_long_term_forecasting中的test部分需要batch_x和batch_y预测，如果想要预测的时间段没有OT的真实值，test部分需要怎么修改呢，谢谢！

**Comment by wuhaixu2016** [comment]
我感觉您不是为了实验，而是为了模型部署。可以在dataloader中设置batch_y为None，然后不计算指标即可

**Comment by kukimika** [comment]
感谢！
