### ISSUE TITLE
imputation的mask问题

### ISSUE THREAD

**Issue by TianlinZhang668** [thuml/Time-Series-Library#467]
您好，我想问一下  在imputation的设置中mask_rate是随机mask的么，我可以设置每隔固定时间进行mask么。因为我的数据格式是 A空空空空空B空空空空空C。
此外，我如果inference的时候，我应该怎样输入呢，有什么指令么

万分感谢

**Comment by wuhaixu2016** [comment]
您好，您需要更新mask的生成方式：https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_imputation.py#L110
