### ISSUE TITLE
关于数据维度的问题

### ISSUE THREAD

**Issue by Uncle-George-13** [thuml/Time-Series-Library#468]
您好，我有一个问题是关于MSL数据维度的，我看到测试数据是行数: 73729的数据，那么在使用Timesnet进行测试时，为什么gt的长度会达到7363000

**Comment by wuhaixu2016** [comment]
您好，具体请见dataloader：https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L474-L476

数据维度的变化是因为我们使用长度为100的滑窗来获取数据
