### ISSUE TITLE
能否提供预测代码？

### ISSUE THREAD

**Issue by shunai** [thuml/Time-Series-Library#469]
能否提供预测代码？训练了模型，总想用一些历史数据测试一下看结果，感谢

**Comment by wang-lucy** [comment]
您好，感谢关注！代码可以参考exp_short_term_forecasting和exp_long_term_forecasting这两种预测的exp文件

**Comment by shunai** [comment]
感谢您的解答，但是我看了exp_long_term_forecasting代码后，产生个问题，生成的结果如何转成原内容，有点疑惑，希望解答

**Comment by wang-lucy** [comment]
您好，不知道我对您所说的“原内容”的理解是否正确。在数据处理阶段对数据进行了标准化，可以通过逆变换将生成结果转成原内容。
