### ISSUE TITLE
how to solve ModuleNotFoundError: No module named 'mamba_ssm'

### ISSUE THREAD

**Issue by RuojiWang** [thuml/Time-Series-Library#471]
when i am runing run.py, i meet ModuleNotFoundError: No module named 'mamba_ssm', how can i solve this?

when i am running pip install mamba_ssm, i meet the following error:

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting mamba_ssm
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f7/80/69bc14816fda4b30be3ac724e3efc713969dd545cd0bcb35abee6b8dfbf9/mamba_ssm-2.2.2.tar.gz (85 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  ?python setup.py egg_info did not run successfully.
  \u2502 exit code: 1
  \u2570\u2500> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ge52m5zv/mamba-ssm_e4e792727658421782b6931815b7a14d/setup.py", line 20, in <module>
          from torch.utils.cpp_extension import (
      ImportError: cannot import name 'HIP_HOME' from 'torch.utils.cpp_extension' (/media/ssd3/anaconda3/envs/meiling4/lib/python3.8/site-packages/torch/utils/cpp_extension.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

?Encountered error while generating package metadata.
\u2570\u2500> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by wuhaixu2016** [comment]
Actually, we have solved the problem of installing mamba here https://github.com/thuml/Time-Series-Library/issues/386
If you want to run mamba in time series analysis, you may refer to their official code.
