### ISSUE TITLE
TimesNet中pred_len

### ISSUE THREAD

**Issue by LeqiGu** [thuml/Time-Series-Library#472]
TimeBlock在卷积处理数据的时候是seq_len+pred_len，那么模型训练和测试的时候，对应的pred_len的值是经过卷积处理的值还是原始的值？这样做有什么用？
谢谢作者大大

**Comment by wuhaixu2016** [comment]
https://github.com/thuml/Time-Series-Library/issues/38
您好，相关讨论可以在这里找到。
