### ISSUE TITLE
请问能否进行多序列multiple series预测？

### ISSUE THREAD

**Issue by Yewx0310** [thuml/Time-Series-Library#477]
我有多个item的序列，在pytorch-forcasting中的TimeSeriesDataset可以创建多item的序列数据集，请问我要如何处理我的数据集才能使用你的库呢

**Comment by wuhaixu2016** [comment]
您好，TSLib天然支持多变量预测，请改写dataloader：https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py

**Comment by Yewx0310** [comment]
This is an automatic reply, confirming that your e-mail was received. Thank you.--------------------------------------------Best WishesWenxue Ye.
