### ISSUE TITLE
How to train, test, and forecast my own datasets?

### ISSUE THREAD

**Issue by TungyuYoung** [thuml/Time-Series-Library#48]
Dear Authors,
Thanks for your job and open source code.

Here is a question I would like to ask you in all honesty. My own datasets do not contain a 'Date' column because it is a long time data sampled at a certain sample rate (sr). Instead, it may only last a few tens of minutes, but there are actually minutes * 60 * sr of data in each dataset. How should I apply my personal data set to FedFormer?

I would be grateful if you could answer my questions.

**Comment by wuhaixu2016** [comment]
Hi, I think you can generate the timestamp yourself (fake time is ok). The temporal embedding is not a key factor to the final performance.
