### ISSUE TITLE
set channel independence as '0', occur dimension error

### ISSUE THREAD

**Issue by raiy236** [thuml/Time-Series-Library#480]
<img width="568" alt="error" src="https://github.com/user-attachments/assets/017ac5ef-e689-4ca9-a975-2dbace8b36e3">

Run 'TimeMixer_ETTh1.sh', only change channel independence from 1(default) to 0,  error occurs.
The reason is in TimeMixer.py, the x_mark is processed as:
![image](https://github.com/user-attachments/assets/5282a3a8-f7b2-4e55-9a37-e55f0f974995)

So in Embed.py, when try to do like this:
![image](https://github.com/user-attachments/assets/115ed3a7-898b-45e5-b7cb-18b5539c3ca2)

Error occurs.

How to handle it, thanks.

**Comment by wuhaixu2016** [comment]
Hi, thanks for finding out about this problem. We have fixed it in the latest commit: https://github.com/thuml/Time-Series-Library/commit/f2c8af44c025205af913f1d7bb3e0c5908bd370f
