### ISSUE TITLE
短期的预测可以使用小波变换吗？

### ISSUE THREAD

**Issue by ChesonHuang** [thuml/Time-Series-Library#482]
模型的处理是基于快速傅立叶变换的，但由于傅立叶变换的缺点，可能没法在瞬态特征的信号中表现很好。所以，想问问对于短期的预测，是否可以改为小波变换处理

**Comment by wuhaixu2016** [comment]
您好，感谢关注。使用小波变换是很好的建议，不过在TimesNet中我们只是想找到一个周期长度，因此FFT也可以表现的不错。
