### ISSUE TITLE
Not actually an issue, just a potential problem.

### ISSUE THREAD

**Issue by revv00** [thuml/Time-Series-Library#485]
Great work on trying to unify the neural ts prediction algos. That could benefit the community quite a lot. I notice that the padding logic in TimesBlock of TimesNet is always to the right side. I'm thinking that if left-side padding could lead to better results because 1) More recent signals are better for prediction 2) it reliefs the model to learn a better prediction at different length/preriod.

**Comment by wuhaixu2016** [comment]
Thanks for your suggestion. The padding operation is just to align the sequence length to ensure the exact division. We also try the left-padding, and find the padding direction will not affect the final performance.
