### ISSUE TITLE
初学者如何用自己的数据集训练吖？

### ISSUE THREAD

**Issue by feifei05** [thuml/Time-Series-Library#488]
大神们，我是初学者，请问data_load.py中的self.features == 'M' or self.features == 'MS'特征指的是什么，ETTh.csv数据集中包含日期总共8列都没有这名称的字段，好奇怪，如果换成自己的数据集，包含日期总共15列，也就是特征13个，1列日期，1列目标，改成了OT字段为回归目标，总样本数1000条，如果用iTransformer和TimesNet.sh，需要修改哪些地方，哪些参数吖？
请大神们指导下哈。

![111](https://github.com/user-attachments/assets/45cef1cf-f850-4aa8-812b-d5690f76499a)

**Comment by wuhaixu2016** [comment]
您好，M和MS分别指多变量预测，使用多变量预测目标变量。如果您想使用自己的数据集，可以把目标列的名字改成OT。
直接看数据加载代码更加清晰：https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L207

**Comment by feifei05** [comment]
> 您好，M和MS分别指多变量预测，使用多变量预测目标变量。如果您想使用自己的数据集，可以把目标列的名字改成OT。 直接看数据加载代码更加清晰：https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L207
1、请问，除去时间列还有14列，13列是特征，OT列是目标，那这是回归任务对吗？
2、在sh脚本里面，没有MS这个参数？
3、pre_len 预测长度是什么意思？
4、自己的数据一共1000个样本，如何改参数？昨天把8改成了14，没有跑成功。

**Comment by xiyangyang99** [comment]
> > 您好，M和MS分别指多变量预测，使用多变量预测目标变量。如果您想使用自己的数据集，可以把目标列的名字改成OT。 直接看数据加载代码更加清晰：https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L207
> > 1、请问，除去时间列还有14列，13列是特征，OT列是目标，那这是回归任务对吗？
> > 2、在sh脚本里面，没有MS这个参数？
> > 3、pre_len 预测长度是什么意思？
> > 4、自己的数据一共1000个样本，如何改参数？昨天把8改成了14，没有跑成功。

我能看看吗？
