### ISSUE TITLE
May I ask what do 'seq_len', 'label_len', 'pred_len' mean in 'Dataset_ETT_hour' for long-time forecasting, respectively?

### ISSUE THREAD

**Issue by Zeyu-Zhu** [thuml/Time-Series-Library#49]

**Comment by wuhaixu2016** [comment]
Hi, you can ref to this paper Informer (https://ojs.aaai.org/index.php/AAAI/article/view/17325/17132)
This setting is firstly proposed by Informer.

**Comment by Zeyu-Zhu** [comment]
Thanks a lot! I will read it.

**Comment by sysublackstar** [comment]
The README doc of Informer contains what all hyperparameters mean.
https://github.com/zhouhaoyi/Informer2020

**Comment by Zeyu-Zhu** [comment]
Thx, it helps a lot
