### ISSUE TITLE
When running imputation tasks ,it raise invalid size

### ISSUE THREAD

**Issue by xiao-donghu** [thuml/Time-Series-Library#490]
![p2](https://github.com/user-attachments/assets/68ad1dc6-3b8e-4849-81f5-9f933d5cbf25)
Without any changes

**Comment by xiao-donghu** [comment]
when running ETTh1.csv

**Comment by wuhaixu2016** [comment]
您好，我们运行了算法库自带的脚本是没有问题的：https://github.com/thuml/Time-Series-Library/blob/main/scripts/imputation/ETT_script/TimesNet_ETTh1.sh

这个报错，我个人觉得是seq_len和pred_len没有设置匹配

**Comment by xiao-donghu** [comment]
好的，谢谢。我看一下原来脚本的设置
