### ISSUE TITLE
预测数据为什么和目标数据OT不一样？

### ISSUE THREAD

**Issue by feifei05** [thuml/Time-Series-Library#491]
![p1](https://github.com/user-attachments/assets/7eab07b1-d737-4408-849b-261ed3b7dc80)
您好。使用自己的数据集跑PatchTST模型，有几个问题不懂请教大佬们。
参数如下：
  --data custom \
  --features MS \
  --seq_len 10 \
  --label_len 5 \
  --pred_len 5 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 14 \
  --dec_in 14 \
  --c_out 1 \
  --freq 'd' \
  --des 'Exp' \
  --itr 1

1、用历史10天数据，预测未来20天数据，OT目标列都是7点几，为什么绘制出来的图的值都是2点几？为什么只绘制这几个点的数据，不画出全部数据？
2、使用1000条样本数据，预测效果这么看非常差，能否给些调参的建议？
3、上面的参数  --features、 --enc_in  、--dec_in、--c_out 我设置的是不是存在问题呀？

**Comment by feifei05** [comment]
请问这个参数--inverse是什么作用？

**Comment by wang-lucy** [comment]
您好，在数据处理阶段，我们首先对数据集进行了归一化，--inverse设置是否将预测结果进行逆归一化。如果您有更多的绘制需求，可以参考相关代码：https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_long_term_forecasting.py#L235，
