### ISSUE TITLE
关于classification任务的seq_len和pred_len设定

### ISSUE THREAD

**Issue by sqhsysu17** [thuml/Time-Series-Library#497]
在项目给出的运行分类任务的命令行示例中，没有输入seq_len和pred_len，不过在训练的setting变量中似乎会根据实际输入数据的样子给出正确的seq_len和pred_len，比如保存下来的checkpoint目录名字里是_sl12_pl0_
1、问题：但这在我将is_training设为0时出现了问题，在搜索checkpoint时，会使用默认的参数，打印出来的setting会是_sl96_pl96_，然后导致找不到对应的checkpoint

2、诉求：尝试找了一下是哪个部分的代码可以根据实际输入数据来设定seq_len、pred_len，以便我将其放入test函数中去，但眼拙没有找到。

3、解决：有简单的解决办法，就是在测试的情况下，自己添加上正确的seq_len和pred_len，使得setting和训练时的setting名称一致，就可以找到训练好的checkpoint。但按理说不需要的。

很感谢作者团队的工作和开源精神！甚至还以TimesNet为例提供了这么详细的notebook教程！提出一个小问题，不解决也行哈哈，反正手动加一下参数就可以了

**Comment by sqhsysu17** [comment]
我发现在exp_classification.py的build model函数中设定了pred_len为0，但不知为何在is_training = 0时未生效

**Comment by wuhaixu2016** [comment]
您好，感谢关注与使用，分类任务是根据全量数据中最长的序列来确定pred_len和seq_len，具体的代码在这里：https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L704-L705 以及 https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_classification.py#L24
