### ISSUE TITLE
python 3.6 or 3.8

### ISSUE THREAD

**Issue by SaltedfishLZX** [thuml/Time-Series-Library#5]
I followed the instruction, installed **python 3.6** on windows and tried `pip install -r requirements.txt`
but it reminded me that `1.22.4 Requires-Python >=3.8`
So I recreated a py3.8 environment and successfully installed all the packages required. I'm wondering that which version I should install and if there will be some problems to use py3.8？
thanks

**Comment by htg17** [comment]
Thank you for pointing out this issue. Python 3.8 is the correct version, and we have updated README.md.
