### ISSUE TITLE
关于训练集，验证集，测试集的尺寸问题

### ISSUE THREAD

**Issue by xiao-donghu** [thuml/Time-Series-Library#500]
您好,我想问一下，在用TimesNet做ETT_h1的长期预测任务时，训练集，验证集和测试集的大小不是在data_loader中定死的吗，为什么最后训练时会随着pred_len的变化而变化
![tu](https://github.com/user-attachments/assets/f3a4566e-fe5f-43da-8b8e-c33a4cb1f97a)
![tu2](https://github.com/user-attachments/assets/8d4ec324-3e81-4e72-9ea3-48ee6fd76e72)

**Comment by wuhaixu2016** [comment]
您好，这个原因是：为了保证训练与测试的严格区分，需要在测试集中预留出输入和输出长度的空白，请见：https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L106

这个问题其实也导致了很多论文的比较不公平，比如一些论文例如DLinear，PatchTST输入长度更长（或者搜素seq_len作为超参数），其实某种程度上会影响测试集大小。这也是为什么我们对长期预测保留了两个榜单，搜索超参数（输入长度96-720）与统一超参数（输入长度96）。
