### ISSUE TITLE
Imputation代码使用

### ISSUE THREAD

**Issue by xiao-donghu** [thuml/Time-Series-Library#501]
作者您好，我想问一下如果想要Imputation的代码用在真正存在有缺失的数据集上去填补缺失时，需要怎么修改呢？感谢

**Comment by wuhaixu2016** [comment]
您好，需要重新改写mask部分，将这里的遮挡过程https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_imputation.py#L109-L113 改成把缺失值用0填充。

**Comment by xiao-donghu** [comment]
感谢，缺失值用0填充后loss应该计算没被填充的部分吗
