### ISSUE TITLE
关于逆变换问题

### ISSUE THREAD

**Issue by xiao-donghu** [thuml/Time-Series-Library#503]
作者您好，我在exp_imputation中仿照长期预测，加入了inverse逆变换的内容。但最终得到的结果和原数据不在一个尺度上，有点疑问。非常感谢！
![微信图片_20240816091509](https://github.com/user-attachments/assets/997e980e-d7de-4c84-b057-0338e02757f2)

**Comment by wuhaixu2016** [comment]
你好，感谢关注，Line 338行有个typo，inverse_tranform函数内部应该输入batch_x
