### ISSUE TITLE
Anomaly Detection特征重建，模型如果是全1不就可以完全重建输入了？

### ISSUE THREAD

**Issue by Junyu-ucla** [thuml/Time-Series-Library#504]
如题，如果想重建特征，为什么不能阻止模型是全1的平凡形式（即强行让输入等于输出）输出一个loss为0的解？即使说模型非常复杂，很难达到平凡参数，但是模型趋近于平凡参数，loss也会接近0.这样的参数是没有意义的。无论说中间模型的结构多么复杂，我们怎么能够确保模型是在学习数据本身的pattern而非单纯复刻数据呢？请问可以帮我解答一下这个问题吗？感谢！

**Comment by wuhaixu2016** [comment]
您好，一般来说异常检测任务有两种思路，一是基于重建，二是基于预测。

（1）对于第一种思路：重建任务的误差是MSE，其实等价于在逼近数据集数值的高斯分布，这个时候可以用离群点来判断到底那个点是异常的。

你提到的“为什么模型不可以学习到全是1”，这是因为深度模型中有很多非线性函数，预测结果一般来说比较平滑。另外，大部分的基于重建的异常检测算法都会有一些额外设计来避免全1的结果。例如，在我们之前提到的Anomaly Transformer中，我们是对Attn map的对角线额外增加了惩罚项，以避免模型退化。

同样的正则化思想可以用在几乎所有模型中，即“逼迫模型更多地关注周围信息，而不是只依赖自己”。因为在TimesNet中，我们更关注的是一个表征学习能力测试，所以并没有额外设计。

（2）对于第二种思路：可以参考我们实验室在ICML 2024发表的Timer：https://github.com/thuml/Large-Time-Series-Model
