### ISSUE TITLE
exp_classification训练时是否是将测试集作为验证集？

### ISSUE THREAD

**Issue by xiiaochuang** [thuml/Time-Series-Library#505]
在Exp_Classification.train方法的前几行，训练数据取自训练集，验证数据、测试数据都取自测试集，请问这样做是什么原因？

按照通常的理解，测试集在训练阶段应该是完全未知的，至少不应该用作验证集。验证集是从训练集中划分出独立的一部分。

![1723867993975](https://github.com/user-attachments/assets/54134e66-cfe7-49c6-93a1-5b42fc167dd4)

**Comment by wuhaixu2016** [comment]
您好，感谢关注与细致的使用。您说的是正确的，在分类问题中，测试集不应该作为验证集。

我们的结果以及代码来自于这篇论文：https://arxiv.org/pdf/2010.02803，这篇论文的结果是每个类别下的best accuracy，即val set=test set。遵循这个设置，我们也保持了val set=test set。

这意味着我们其实在对比不同模型能够到达的“最好效果”，因为所有的模型都使用了这样的设置，所以比较也是公平的。我们会在readme中更新这个信息，以避免误导同行们。
