### ISSUE TITLE
关于获取最终预测结果

### ISSUE THREAD

**Issue by xiao-donghu** [thuml/Time-Series-Library#508]
作者您好，感谢您的工作和之前的回复！在填补和预测任务最终获取到的（B，T，N）的npy文件，如果我想要最终的二维预测结果，是不是只需要取T步长的第一步，即(B,0,N)就行

**Comment by wuhaixu2016** [comment]
您好，感谢使用，但是非常抱歉我不太理解您的问题。

预测和填补任务的数据加载使用的是划窗方式，每步步长是1，具体可以见：https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L92 。您可以基于这个信息再思考您想要的结果是什么。

**Comment by xiao-donghu** [comment]
抱歉我可能没表达清楚，就是如果想导出像TimesNet使用的csv格式的文件，是不是应该只取步长中的一步
