### ISSUE TITLE
现在基于大模型的分析方法逐渐兴起，如Timer，LTSM-Bundle等，是否该纳入对比？

### ISSUE THREAD

**Issue by YulingTian-YNU** [thuml/Time-Series-Library#509]
大模型的成本高，但是预测效果很好，这样是否需要纳入对比。纳入对比的在资源开销和成本上目前“小模型”占据非常大的优势，但是效果却不是很占优势，这样如何取舍？

**Comment by wuhaixu2016** [comment]
您好，这是一个非常好的问题。

我个人认为，现在大模型的优势在于使用大规模数据预训练，因此，如果将现在TSlib中的算法在同样的大规模数据集上训练，我觉得效果不一定会弱于现在的大模型。

但是显然大模型的“预训练-微调”、“预训练-泛化”，这两个范式与TSlib现在的框架不太适配，我们也正在思考这个问题。

**Comment by YulingTian-YNU** [comment]
感谢回答！！
