### ISSUE TITLE
模型在windows系统下的运行问题

### ISSUE THREAD

**Issue by GOOFFG** [thuml/Time-Series-Library#51]
作者您好：
       在windows系统下配置好环境后，会产生如下错误：
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

请问有什么解决方法吗，还是说必须使用linux系统运行。

**Comment by lmxy264** [comment]
同问 楼主解决了吗

**Comment by lmxy264** [comment]
> 作者您好： 在windows系统下配置好环境后，会产生如下错误： 运行时错误： 在当前进程完成其引导阶段之前，已尝试启动新进程。
> 
> ```
>     This probably means that you are not using fork to start your
>     child processes and you have forgotten to use the proper idiom
>     in the main module:
> 
>         if __name__ == '__main__':
>             freeze_support()
>             ...
> 
>     The "freeze_support()" line can be omitted if the program
>     is not going to be frozen to produce an executable.
> ```
> 
> 请问有什么解决方法吗，还是说必须使用Linux系统运行。

把<
parser.add_argument('--num_workers', type=int, default=0, help='data loader num workers')
>
这句那个default改成0就可以了 win系统不能多个子进程加载数据

**Comment by wuhaixu2016** [comment]
@lmxy264 感谢您的耐心解答。

我们的实验主要在linux下测试，确实没有在windows环境下尝试过，我们后面也会进行多平台测试，提升兼容性。
