### ISSUE TITLE
长期预测预测结果出现负数

### ISSUE THREAD

**Issue by xiao-donghu** [thuml/Time-Series-Library#511]
作者您好，在使用长期预测代码时，我发现输入全为正数的情况下，预测结果中会出现负数。我尝试在输出时加一个线性层和一个非负的激活函数，但这样效果并不好。我想问一下您有没有什么保证预测精度的情况下又能使预测输出为正数的思路，非常感谢！

**Comment by wuhaixu2016** [comment]
您好，对于深度模型来说，确实可能出现这样的问题，因为它只是在做分布拟合，而负数可能被判定为了极小概率事件。

其实最合适的思路是将小于0的数值，全部通过clamp的方式变成0，这个也是工程中常用的做法。
