### ISSUE TITLE
有外生变量的单变量时序预测

### ISSUE THREAD

**Issue by xuo001** [thuml/Time-Series-Library#512]
我们尝试用iTransformer对景区客流进行预测，考虑将节假日、降水、天气作为外生变量，但是iTransformer并没有使用传入的batch_y，相当于对pred_len的多变量同时进行了预测。这样对于周末这种规律性的变化规律，模型能够很好的学习；但是对于法定节假日、降水这种不规律的波动，由于模型对关联变量的预测不准确，导致很难学习到对应的规律。
        请教一下：有没有办法通过注意力机制学到多变量的关系，然后将pred_len的外生变量值直接给到模型，然后对客流进行预测？
       TimeXer能解决这个问题吗，期待能早点开源，谢谢！

**Comment by wuhaixu2016** [comment]
您好，TimeXer确实可以解决这个问题，它可以接受与输入长度不一致的斜变量，我们预计会在9月底开源。

**Comment by xuo001** [comment]
您好，期待早日开源Timxer，谢谢！
