### ISSUE TITLE
AssertionError in LightTS for classification with some dataset

### ISSUE THREAD

**Issue by holderhe** [thuml/Time-Series-Library#516]
`assert (self.seq_len % self.chunk_size == 0)` in LightTS.py will cause this AssertionError with some dataset.

**Comment by wuhaixu2016** [comment]
Thanks for your information. This is caused by that the seq_len of the classification task is determined by the maximum length of training samples. You can fix this by adaptive padding the input length. We will also update the code sasp.

**Comment by wuhaixu2016** [comment]
Hi, we have fixed this issue.
