### ISSUE TITLE
预测准确率问题

### ISSUE THREAD

**Issue by Chuan112233** [thuml/Time-Series-Library#517]
你好，我现在选用模型库里的itransformer在跑预测，用10个步长预测1步长，但是itransformer始终跑不过带注意力机制的lstm，我调参调了很久也跑不过，不知道问题出在了哪里？

**Comment by wuhaixu2016** [comment]
您好，short-term预测我觉得LSTM是一个很强的baseline，可以试试TimesNet/TimeMixer的效果

**Comment by Chuan112233** [comment]
> 您好，short-term预测我觉得LSTM是一个很强的baseline，可以试试TimesNet/TimeMixer的效果

但是有时候itransformer连机器学习模型（ridge与lasso）也跑不过，也是用10个步长预测1步长，这是什么原因呢？是我哪里出问题里面？
![image](https://github.com/user-attachments/assets/e0b998e6-03f2-4bd3-b7ce-fd098b2cc4ed)
![9cb3c691944b30b243392c5e3195d190](https://github.com/user-attachments/assets/0222d1c5-9b4d-4c23-ac5c-c861b2b4a712)
