### ISSUE TITLE
TimeXer对未来可知变量的学习效果

### ISSUE THREAD

**Issue by koukouer** [thuml/Time-Series-Library#518]
我想请教一下关于TimeXer的外生变量学习问题，我看到论文里说TimeXer使用Cross-Attention来捕捉内生变量和外生变量之间的依赖关系。在时序预测中，外生变量可以分成历史可知变量（长度=内生变量长度）和未来可知变量（长度=内生变量长度+预测步长），我看模型架构里并没有对这两者做区分，尽管我可以直接把未来可知变量加入到TimeXer进行预测，它支持不同长度的输入，但这种方式能否充分利用未来可知变量的前瞻性呢
比如我有个促销信息是未来可知的，相当于在预测周期内部分信息可知，那么在训练拟合对训练样本切分训练集和测试集，这个促销信息的预测步长部分应该出现在测试集的外生变量中，来辅助推理预测，理论上这样才能充分利用。我不知道TimeXer能否做到这一点
补充：以Vanilla Transformer模型为例，在neuralforecast库的代码实现中，会将未来可知变量切分成两部分，历史周期内的信息给编码器使用，预测周期内的信息给解码器使用，通过这种方式来使用未来可知变量

**Comment by wuhaixu2016** [comment]
您好，感谢关注，我觉得是可以的。

不过需要（1）训练数据集中需要包涵类似的未来可知变量（2）将未来销售信息的数据编码成序列。

**Comment by koukouer** [comment]
感谢回复，期待你们在9月底的开源
