### ISSUE TITLE
预测结果产生负值

### ISSUE THREAD

**Issue by Chuan112233** [thuml/Time-Series-Library#519]
![QQ_1725259832821](https://github.com/user-attachments/assets/71202827-b60f-48cc-9c6c-1c49eaf263c3)
您好，我用的itransformer模型在进行预测，用10步预测1步，我的预测目标变量的真实值都是正数，但预测值产生了较多负数，导致各评价指标不太理想（尤其rmse），基本大多数参数我都调试了，都没有明显改善。 我应该如何调整呢？以防产生较多的负数的预测值。不胜感谢。

**Comment by wuhaixu2016** [comment]
您好，之前也有研究人员问过类似的问题，可以见：https://github.com/thuml/Time-Series-Library/issues/511

目前深度模型还比较难以实现hard constraint（硬约束），所以一般做法就是直接clamp

**Comment by Chuan112233** [comment]
> 您好，之前也有研究人员问过类似的问题，可以见：#511
> 
> 目前深度模型还比较难以实现hard constraint（硬约束），所以一般做法就是直接clamp

好的，感谢

**Comment by Chuan112233** [comment]
> 您好，之前也有研究人员问过类似的问题，可以见：#511
> 
> 目前深度模型还比较难以实现hard constraint（硬约束），所以一般做法就是直接clamp

![QQ_1725504803167](https://github.com/user-attachments/assets/718de583-5652-4f96-824d-8d7a6d71d9d6)
用了clamp，但是预测准确率貌似没有提升，评估指标没有提升。   是我的clamp用错了吗？
