### ISSUE TITLE
Shared LayerNorm in TimesNet.

### ISSUE THREAD

**Issue by CODEJIN** [thuml/Time-Series-Library#520]
Hello,

Thank you for providing such a great library.

I am currently analyzing the code in the repository, and I have a question, so I am leaving an issue here.

I noticed that in TimesNet, a single LayerNorm is applied to normalize the output of all TimesBlocks [Here](https://github.com/thuml/Time-Series-Library/blob/04b8054aa6b8a16fe2594f4120ee455f5ef45b45/models/TimesNet.py#L116-L117). As far as I know, Pytorch’s implementation of LayerNorm has its own weights unless elementwise_affine=False. Is it intentional that the LayerNorm is shared? If so, could you please explain the intended effect of this?

Thanks.

**Comment by wuhaixu2016** [comment]
Hi, thanks for your question and using TSlib.
I think this design is a kind of coding accident. I cannot remember any special intentions for this. Maybe I wrote this code for parameter efficiency (but I am not sure). However, according to my experience, I think a non-shared version may achieve better performance.
