### ISSUE TITLE
用了clamp，评估指标没有提升

### ISSUE THREAD

**Issue by Chuan112233** [thuml/Time-Series-Library#522]
为了预测值产生较多负数，用了clamp，但是预测准确率貌似没有提升，评估指标没有提升。 是我的clamp用错了吗？

![019f1dcd8f48ec023c5a64db4c86fc21](https://github.com/user-attachments/assets/f06f5c5c-1757-446a-baff-407584b07813)

**Comment by wuhaixu2016** [comment]
您好，clamp的目标是为了去除异常值，如果您所有的点都在0以上，这样应该会产生一些帮助，但是如果预测负值本身较少，这样操作并不会带来太大收益
