### ISSUE TITLE
bash /scripts/short_term_forecast/M4/xxx.sh

### ISSUE THREAD

**Issue by rbm123456** [thuml/Time-Series-Library#527]
Why do the following errors occur when the m4 script file is run:
![a9444cda-d7da-497d-8280-dafa748aa94a](https://github.com/user-attachments/assets/88a5d597-0b27-4411-929e-abbf35618657)

**Comment by wuhaixu2016** [comment]
Hi, this is the official code of TimeMixer, please transfer this issue to its official repo.

According to my experience, this is caused by the package version. Please see https://github.com/thuml/Time-Series-Library/issues/499
