### ISSUE TITLE
维度不匹配

### ISSUE THREAD

**Issue by MR-HOLO** [thuml/Time-Series-Library#528]
你好，这边跑自己数据集，出现维度不匹配问题。
 File "C:\Users\BESP\TN_Methane_V0\models\TimesNet.py", line 57, in forward
    out = out.reshape(B, length // period, period, N).permute(0, 3, 1, 2).contiguous()
RuntimeError: shape '[64, 12, 16, 512]' is invalid for input of size 12582912

**Comment by wuhaixu2016** [comment]
您好，我觉得这个问题应该是pred_len/seq_len设置错误，可以检查一下
