### ISSUE TITLE
could not use multiple gpus in MICN

### ISSUE THREAD

**Issue by holderhe** [thuml/Time-Series-Library#535]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat)

**Comment by Musongwhk** [comment]
Hi. Could you please provide more detailed error information to help us fix the corresponding bug? Such as your experimental parameters and error location, etc.

**Comment by wuhaixu2016** [comment]
Hi, we have fixed this problem. Thanks for coming up with this issue.
