### ISSUE TITLE
Test on Ascend 910B 

### ISSUE THREAD

**Issue by onejune2018** [thuml/Time-Series-Library#538]
Thanks for the awesome repo! 

I was wondering that have you already tested Time-Series-Library on Ascend 910B? or in future plan?

**Comment by wuhaixu2016** [comment]
Thanks for your recommendation. We haven't tested TSlib in 910B. Since we mainly focus on algorithm design, we do not have a code migration plan. If you are interested in doing this transfer task, we are happy to offer any possible help (discussion or others).
