### ISSUE TITLE
Regarding the custom dataset CSV, there are data format issues in the train-loader for classification tasks.

### ISSUE THREAD

**Issue by xiyangyang99** [thuml/Time-Series-Library#540]
Thank you to the author for their open source work. In the classification task, they loaded their own dataset, and there are three types of data in the train-loader. But there were problems during training. What is the data format of the trainloader?
<img width="687" alt="企业微信截图_17267362198164" src="https://github.com/user-attachments/assets/adcd64ee-9ee8-4fb3-8be1-1d8bf8297b22">
<img width="549" alt="企业微信截图_17267363008761" src="https://github.com/user-attachments/assets/b6c3eb85-e9e1-4e0f-bc11-0d2b0d1b5d80">

this is my  bug log：
<img width="598" alt="企业微信截图_17267364837922" src="https://github.com/user-attachments/assets/45dc2c16-61bd-4c52-b231-79a904a41819">

I hope the author can provide a significant data format for train-loader。

**Comment by wuhaixu2016** [comment]
Sorry, this data loader design works well for our scripts. Are you trying to use your own data? You can read this file for the data organization (https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L616-L748 ).

**Comment by xiyangyang99** [comment]
> Sorry, this data loader design works well for our scripts. Are you trying to use your own data? You can read this file for the data organization (https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L616-L748 ).

I created my classification dataset in TS format and encountered a bug during training, which is a dimension mismatch issue. In the source code, there is a for loop that needs to subtract 1, which is to subtract the label. Why does subtracting 1 from the first iteration result in a mismatch in dimensions when the dimensions are the same in the first iteration? I hope the blogger can dispel doubts.
![Uploading 企业微信截图_1728530609346.png…]()
