### ISSUE TITLE
[Possible bug] Issue with M4 dataset inverse transform

### ISSUE THREAD

**Issue by NamburiSrinath** [thuml/Time-Series-Library#541]
Hi, 

I am not sure if M4 is using inverse transform function. Even if I pass the flag --inverse True, the function `inverse_transform` won't be called.

And there's no `self.scaler` set in `Dataset_M4`, The `__read_data__` doesn't have the `self.scaler` functionality for M4 class!

**Comment by wuhaixu2016** [comment]
Hi, we do not normalize the M4 data before input. Thus, you do not need employ the inverse transform.
