### ISSUE TITLE
Issue with output_attention argument in Long term forecasting

### ISSUE THREAD

**Issue by BenjaminRedhead** [thuml/Time-Series-Library#542]
I have had the following error after setting --output_attention as an argument in the bash file for iTransformer.
Traceback (most recent call last):
  File "/home/Time-Series-Library/run.py", line 208, in <module>
    exp.train(setting)
  File "/home/Time-Series-Library/exp/exp_long_term_forecasting.py", line 139, in train
    outputs = outputs[:, -self.args.pred_len:, f_dim:]
IndexError: too many indices for tensor of dimension 2
If I remove --output_attention this issue does not occur

**Comment by BenjaminRedhead** [comment]
I have made a pull request with the fix for this issue and also tested it does not cause problems when not using --output_attentions, this is the same as what was already implemented in the test part of the original code

**Comment by BenjaminRedhead** [comment]
Pull request #544

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interest and effort in debugging.

The current version does not support the output-attention argument. So, I think the correct way is to remove the 'output-attention' in the long-term forecasting file.
