### ISSUE TITLE
能否公开使用PatchTST进行时间序列异常检测的shell脚本，或者训练时使用的模型参数？

### ISSUE THREAD

**Issue by caixd-220529** [thuml/Time-Series-Library#543]
作者您好，非常感谢您的工作。在Deep Time Series Models: A Comprehensive Survey and Benchmark这篇文章中，我留意到您有使用PatchTST进行时间序列异常检测的实验（Fig. 10）。请问您能否公开相关shell脚本，或者训练时使用的模型参数？

**Comment by wuhaixu2016** [comment]
您好，您可以直接复用Autoformer的参数配置，替换模型名称即可
