### ISSUE TITLE
# forecasting 运行，GPU崩溃

### ISSUE THREAD

**Issue by zhaoyang-coder** [thuml/Time-Series-Library#545]
每次运行bash ./scripts/forecast/ECL.sh，跑了几个四五个epoch，gpu就崩溃了，这是什么原因啊
![image](https://github.com/user-attachments/assets/502f6ba8-f616-46b2-94ee-c140d255fa55)
![image](https://github.com/user-attachments/assets/b0455c8c-fbf5-49ea-8c6c-8b4a4f43fbbb)

**Comment by wuhaixu2016** [comment]
您好，我们官方repo里面没有这个脚本bash ./scripts/forecast/ECL.sh
根据我的经验，应该是硬件问题
