### ISSUE TITLE
On using ETT for short-term forecasting

### ISSUE THREAD

**Issue by lc7335** [thuml/Time-Series-Library#546]
Are there any differences between the parameters task_name=long_term_forecast and task_name=short_term_forecast when performing short-term forecasting on the ETT dataset? I noticed that in your codebase, short-term forecasting is only targeted at the M4 dataset, but the data structure of M4 is quite unique.

**Comment by wuhaixu2016** [comment]
Hi, thanks for asking this question.
The current version of short-term forecasting is only for M4. If you want to test short-term forecasting for general csv files, you can use the long-term forecasting setting and adjust the seq_len argument.
