### ISSUE TITLE
run.py output_attention默认值缺失

### ISSUE THREAD

**Issue by lostlau** [thuml/Time-Series-Library#55]
https://github.com/thuml/Time-Series-Library/blob/fb2ef740b30f13ec5cf366ea85733635a0bb0ae9/run.py#L70

hello，这儿好像缺了默认值，虽然可以默认为是None，我看案例代码里好像也没影响，但是我有点强迫症😂，还是提一下，你们评估一下，谢谢。

**Comment by wuhaixu2016** [comment]
您好，感谢您的细致建议。不过store_true这个类型都是不写默认值的，在运行script时，如果有--output_attention则是True，如果没有则默认是False。
