### ISSUE TITLE
输入张量的形状注释

### ISSUE THREAD

**Issue by aanxud888** [thuml/Time-Series-Library#550]
库里面很多网络层，张量处理函数、forward几乎都没有关于张量形状的注释和描述（还有张量对应的物理意义），使用起来很费解。对于由张量构建的数据链路图网络来说不太友好，使用考虑添加一些注释呢

**Comment by wuhaixu2016** [comment]
您好，其实只要知道输入的形状是B T C就可以了，模型中间层的形状很好推得。更多的细节可以看我们的tutorial得到
