### ISSUE TITLE
What does "label length" mean and what is the role of 'seq_y' in your dataloader?

### ISSUE THREAD

**Issue by WilliamLwj** [thuml/Time-Series-Library#555]
Hi! I hope this post finds you well. I'm kind of a newbee in this area and trying to use your models to do time series forecast. Great repo by the way.

Maybe a dumb question but I'm just really confused what 'label_len' means in your data-loaders, and how the corresponding data 'seq_y' is used in your models. For example https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L99. I don't understand why we need two sequences. Is this for some particular model?

Thanks a bunch in advance.

**Comment by wuhaixu2016** [comment]
Hi, this is for the encoder-decoder-type model, you can see this paper: https://arxiv.org/abs/2012.07436
