### ISSUE TITLE
Test Methods

### ISSUE THREAD

**Issue by ZTbreeder** [thuml/Time-Series-Library#556]
MSEMAE in TimesNet, is it obtained using normalized target columns as data? For example, normalizing the last column of the dataset ETTH1 and using the past 96 to predict the future {96, 192, 336, 720}? Or no normalization?

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interest.

We have discussed this topic in another repo. This metric is a conventional usage in previous papers. Please see: https://github.com/thuml/Autoformer/issues/27
