### ISSUE TITLE
长时间序列预测任务如何使用训练好的模型进行推理

### ISSUE THREAD

**Issue by klayc-gzl** [thuml/Time-Series-Library#557]
作者您好，我想请问如果我在自己的数据集进行长时间序列预测问题训练以后，我想将训练后的模型用于推理，比如输入过去一天的数据预测未来一天的值，这个应该怎么处理呢？

**Comment by wuhaixu2016** [comment]
您好，感谢使用，可以模仿这里（https://github.com/thuml/Autoformer/blob/main/predict.ipynb）写一个predict函数，完成单步推理

**Comment by klayc-gzl** [comment]
不好意思，因为是刚入门这个领域，所以我还是不太清楚这个predict函数应该怎么写呢？
