### ISSUE TITLE
Models with exogenous data

### ISSUE THREAD

**Issue by william1599** [thuml/Time-Series-Library#558]
Hello, thank you for this project. I have a question: in forecasting tasks, which of the available models allow the use of exogenous variables in the analysis? If so, do we need to modify the Dataloader in any way? Thanks in advance.

Best regards!

**Comment by wuhaixu2016** [comment]
Actually, you can try the MS setting https://github.com/thuml/Time-Series-Library/blob/main/run.py#L33-L34

MS setting is to predict one time series based on the others.
