### ISSUE TITLE
分类任务的数据集

### ISSUE THREAD

**Issue by WenSan-2001** [thuml/Time-Series-Library#559]
![7cd86efedd477b7beb43434b7b027994](https://github.com/user-attachments/assets/b2f16496-098a-461d-adc6-d4fa442482b3)
UEA数据集似乎只有关于train的代码，val与test似乎没有？请问要怎么划分数据集呢？

**Comment by wuhaixu2016** [comment]
您好，可以看这里https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L637
