### ISSUE TITLE
The implementation of PatchEmbedding in PatchTST misunderstands the original paper.

### ISSUE THREAD

**Issue by wiwi** [thuml/Time-Series-Library#56]
The implementation of PatchEmbedding in PatchTST misunderstands the original intent, which was to unfold the sequence and encode each patch with a Linear layer, resulting in linear projection along the most single dimension. However, your recurrence treats each patch as a channel input for PatchEmbedding, which is equivalent to applying one-dimensional convolution to the unfolded sequence. Assuming non-overlapping patches, the input convolution dimension would be [patch_len, seq_len//patch_len], and the output dimension would be [d_model, seq_len//patch_len], which represents the convolution of the second dimension. Unfortunately, this does not align with the original text's objective.

**Comment by wiwi** [comment]
If the kernel_size of convolution which is defined in the TokenEmbedding is set to 1, then the implementation is OK.

**Comment by ZDandsomSP** [comment]
Thank you for your reminder.We confirmed the existence of the problem through discussion,and we will fix this problem in our recent commits.
