### ISSUE TITLE
异常检测的测试代码存在bug

### ISSUE THREAD

**Issue by caixd-220529** [thuml/Time-Series-Library#561]
作者您好，在https://github.com/thuml/Time-Series-Library/blob/2fb5b84ecef67c45a759f7cf82023d27afe27882/exp/exp_anomaly_detection.py#L157 及其之后的代码中，文章使用测试集来计算异常时间点的threshold。我能够理解在这里使用测试集来进行阈值的计算，但是在代码中，使用的测试集是通过 https://github.com/thuml/Time-Series-Library/blob/2fb5b84ecef67c45a759f7cf82023d27afe27882/exp/exp_anomaly_detection.py#L129 得到的。
虽然测试集的样本没有被shuffle，但是相邻的两个样本之间存在着大量的重叠。通过综合测试集和训练集的所有样本，固然可以得到准确的threshold，但由于样本之间存在重叠，依次取得的测试集样本不应该被直接拼接在一起。如果直接拼在一起，最终得到的异常分数序列和标签序列会很奇怪。按照代码中的方式，得到的标签为：
[0, 1, 2, ..., 99, 1, 2, 3, ..., 100, 2]
而我认为标签应该是
[0, 1, 2, ..., 99, 100, 101, 102, ..., 199, 200]
数字i代表第i个时间点所对应的标签。
按照代码中的方式进行异常检测，破坏了时间序列本身的序列性。

不知道我说清楚了没有，希望得到您的回复。如果您觉得代码确实有问题，请允许我提出一个PR来解决这个问题。

**Comment by caixd-220529** [comment]
感觉自己好像还是没有说清楚，可能是因为我的表达能力确实有限吧。总而言之，我认为测试集标签的选择应该和 https://github.com/thuml/Anomaly-Transformer/blob/b0ee470c8012bff857fb600462aec6209c4a18d9/solver.py#L292 一样，通过遍历一个类似于 `thre_loader` 的对象，通过滑动窗口的方式来进行测试集的标注。同时每个窗口之间不应该存在重叠。至于阈值的计算方式，我认为这个repository是比较合理的，即训练集和测试集滑动窗口的方式都应该保持步长为1. 在您的代码中，评测前是需要经过点调整。我可以理解点调整在这里使用的原因（即使有很多工作指出了点调整的缺点）。但是，点调整是一个Sequential Adaptability的指标（http://arxiv.org/abs/2405.12096），而目前的代码破坏了时间序列本身的序列性。
虽然点调整的存在，这个bug的修改可能并不会对评测的结果带来很大的影响。但是，Time-Series-Library是一个非常有影响力的仓库，如果我提出的问题确实是个bug，那可能会对其他同学带来不好的影响。当然，如果是我对代码的理解有误，也麻烦您指出。我人工通过np.arange构造了一个递增的伪标签，验证了 https://github.com/thuml/Time-Series-Library/issues/561#issue-2581347773 中最终得到的标签序列确实是有问题的。
再次感谢您的贡献，期望得到您的解答！😋😋😋

**Comment by wuhaixu2016** [comment]
您好，感谢您的细致描述与阅读，非常抱歉回复比较晚。

我理解您的意思是将evaluation改为以100为步长（使用测试集上的不重叠窗口预测），我觉得这个设计是合理的。不过我认为原始设计也是合理的。如果单纯以获取测试数据集标签的角度来理解，确实应该设置不重叠窗口。但是如果以一个线上部署系统为视角，当数据不断到来的时候，也需要滚动预测未来，这也是目前evaluation使用重叠窗口的原因。

不知道是否回答了您的问题，如果您还有别的疑问，可以给我发邮件继续讨论：wuhx23@mails.tsinghua.edu.cn
