### ISSUE TITLE
作者您好，使用自己数据集，然后数据只有三个月，会出现报错，如果使用两年的数据就没有问题，应该在哪个地方修改呢？

### ISSUE THREAD

**Issue by klayc-gzl** [thuml/Time-Series-Library#562]
![image](https://github.com/user-attachments/assets/4e3a1685-67c9-42aa-baf9-59a28a87882a)

**Comment by WenWeiTHU** [comment]
你好，这个可能是验证集长度过短导致无法切分出一个样本的问题，可以尝试扩大验证集的划分比例，调整seq_len。或者使用更长时间的数据

**Comment by klayc-gzl** [comment]
好的，谢谢
