### ISSUE TITLE
Regarding classification tasks, how to match predicted labels with real labels.

### ISSUE THREAD

**Issue by xiyangyang99** [thuml/Time-Series-Library#570]
<img width="392" alt="企业微信截图_17291322868130" src="https://github.com/user-attachments/assets/9bae4e9f-c45b-4ec6-9ced-f7b41b50c0f1">
<img width="182" alt="企业微信截图_17291323067000" src="https://github.com/user-attachments/assets/0906421d-9780-4a92-9a5f-6a0a39a3a639">

This is the local test dataset and the inferred labels; There are a total of four categories. How do the inferred labels correspond to M1, M2, M3, M4?

**Comment by xiyangyang99** [comment]
> <img alt="企业微信截图_17291322868130" width="392" src="https://private-user-images.githubusercontent.com/32487883/377289976-9bae4e9f-c45b-4ec6-9ced-f7b41b50c0f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMzM1OTYsIm5iZiI6MTcyOTEzMzI5NiwicGF0aCI6Ii8zMjQ4Nzg4My8zNzcyODk5NzYtOWJhZTRlOWYtYzQ1Yi00ZWM2LTljZWQtZjdiNDFiNTBjMGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDAyNDgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZGE3YTU1N2UyOTk5MmQwM2VhODQ2NmUwOThhNDU4NjRiNzkwNjk2ZjE2ZTQ2YjA2MzM3ZDRkMjE1OGZiMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J99K7uBen0TW8x7QHKwG672hod0HITcfXUHQIWVNk-Q"> <img alt="企业微信截图_17291323067000" width="182" src="https://private-user-images.githubusercontent.com/32487883/377290325-0906421d-9780-4a92-9a5f-6a0a39a3a639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMzM1OTYsIm5iZiI6MTcyOTEzMzI5NiwicGF0aCI6Ii8zMjQ4Nzg4My8zNzcyOTAzMjUtMDkwNjQyMWQtOTc4MC00YTkyLTlhNWYtNmEwYTM5YTNhNjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDAyNDgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MTQ5MTExYThjZDAxODMxOGEwZTk0NWVkMTIxM2VlZjc3NzRkZDg2MzRkMzg5Y2YyNDE4OWRmNTg4OTZkYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LQ092gJjbdoy4G9_JDoTn_vj3iIaQQvTQ_cewMX1B6Q">
> This is the local test dataset and the inferred labels; There are a total of four categories. How do the inferred labels correspond to M1, M2, M3, M4?

就是自建了分类任务的UEA格式的数据集，数据集分类的标签是M1，M2，M3，M4，但是在推理的时候，预测的标签是0，1，2，3。请问作者如何将预测的标签0，1，2，3和M1，M2，M3，M4对应起来呢？在true2：下面的标签和数据集的标签顺序对应不起来。实际的标签是[31 个M1    28个M2  18个M3  30 个M4] 顺序是挨着的。程序里面的trues2标签顺序不正确感觉是bug。期待作者的回复。

**Comment by wuhaixu2016** [comment]
您好，对应的方式请见这里：https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_classification.py#L174

我觉得也有可能是模型训练不好，需要检查一下accuracy的指标。

**Comment by xiyangyang99** [comment]
> 您好，对应的方式请见这里：https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_classification.py#L174
> 
> 我觉得也有可能是模型训练不好，需要检查一下accuracy的指标。

我想作者大大误会我的问题了，起始是这样的：
我本地测试的数据集标签的顺序是00000000000001111111111112222222222223333333333类似于这样的，但是实际推理的时候，testloader加载出来的true标签顺序是023001030120310301030010301这总乱的也就导致我无法将0123标签和M1，M2，M3,M4这样做绑定。
