### ISSUE TITLE
Some questions about the arguments

### ISSUE THREAD

**Issue by dyhan316** [thuml/Time-Series-Library#574]
in the PatchTST example, there seems to be multiple arguments that are not used (`d_layers`, `factor`, `dec_in`, `c_out`) are these really not used? Or is there a reason they were included? 

Thank you in advance :) 

```
python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_96_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --batch_size 16 \
  --itr 1
```

**Comment by wuhaixu2016** [comment]
Hi, your understanding is correct. These arguments are not used. When we write the execute scripts, we reuse the scripts of Autoformer, thereby forgetting to delete the irrelevant arguments.

**Comment by dyhan316** [comment]
Thank you for your response :)
