### ISSUE TITLE
The images in test_desult differ significantly from the actual values

### ISSUE THREAD

**Issue by htWANG-C** [thuml/Time-Series-Library#576]
Thank you very much for the contribution made to this project. However, during the running process, I found that the values of mae and mse met the standards mentioned in the paper. However, the comparison chart of the results in test_desult showed a significant difference. I would like to know the reason for this and how to modify the code if I want to visualize the results graphically

**Comment by wuhaixu2016** [comment]
Hi, TSLib can support the prediction case visualization. Please see the code here: https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_long_term_forecasting.py#L223
