### ISSUE TITLE
TimesNet在插值模式下运行中的bug

### ISSUE THREAD

**Issue by John-McCartney** [thuml/Time-Series-Library#577]
TimesNet在插值模式下，FFT函数中运行中
length = (((self.seq_len + self.pred_len) // period) + 1) * period求得length=6
padding = torch.zeros([x.shape[0], (length - (self.seq_len+ self.pred_len )), x.shape[2]]).to(x.device)求得padding大小为（4,1,16）
out = torch.cat([x, padding], dim=1)大小为（4,5,16）共计320（在长序模式下该处为（4,6,16））
out = out.reshape(B, length // period, period,N).permute(0, 3, 1, 2).contiguous()分割out的尺寸为（4, 3, 2, 16）共计384
因此会报错RuntimeError: shape '[4, 3, 2, 16]' is invalid for input of size 320
如果将padding改为：padding = torch.zeros([x.shape[0], (length - (self.seq_len+ self.pred_len ))+1, x.shape[2]]).to(x.device)
则会导致res = torch.sum(res * period_weight, -1)报错：RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1
请问该如何解决？

**Comment by wuhaixu2016** [comment]
您好，您运行的是哪个脚本呢？可以贴一下运行的命令行

**Comment by John-McCartney** [comment]
感谢您的回复！后续我仔细翻阅提供的script，原来是我没有把label_len和pred_len设置为0，抱歉打扰了！




> 您好，您运行的是哪个脚本呢？可以贴一下运行的命令行
