### ISSUE TITLE
Can TimeXer handle classification tasks?

### ISSUE THREAD

**Issue by weidaolee** [thuml/Time-Series-Library#580]

**Comment by wuhaixu2016** [comment]
Hi, thanks for your interest. I think it is possible. Actually, you can adapt TimeXer to classification by replacing the forecasting head with a classification one. See here: https://github.com/thuml/Time-Series-Library/blob/main/models/TimeXer.py#L154 and here: https://github.com/thuml/Time-Series-Library/blob/main/models/TimesNet.py#L183-L199
