### ISSUE TITLE
add EPF dataset to Google Drive

### ISSUE THREAD

**Issue by koukouer** [thuml/Time-Series-Library#581]
Thanks to the open source model of TimeXer, I realised that the EPF dataset is not added to the Google Drive, could I think about adding it?
I've tried to go to the EPF dataset paper to find the link to download it, but the database address they gave is no longer valid.

**Comment by wang-lucy** [comment]
Hi, we have provided EPF datasets in TimeXer's official [repo](https://github.com/thuml/TimeXer).  Thanks for your valuable suggestion, we will take it into consideration.
