### ISSUE TITLE
关于异常检测的test逻辑

### ISSUE THREAD

**Issue by njy17** [thuml/Time-Series-Library#584]
为什么要将训练数据和测试数据concatenate来取异常阈值啊，异常检测是需要依赖训练集么？

**Comment by wuhaixu2016** [comment]
您好，如果认为异常检测的场景是一个online系统的话，我们需要更长的序列来判断系统的整体情况，所以用到了训练数据集来寻找阈值。

**Comment by njy17** [comment]
好的，感谢
