### ISSUE TITLE
目前tslib中都是96步回望与部分预设脚本，后续是否会有超参搜索和自动调参？

### ISSUE THREAD

**Issue by bursonz** [thuml/Time-Series-Library#589]
目前在使用tslib进行研究，但在调参使用过程中遇到了两个方面的问题：
1. baseline脚本缺失较多，例如itransformer的ETT数据集脚本只有h2；
2. 自定义模型调参繁琐，对于e_layers, d_model, d_ff 等调参只能手动修改shell脚本去搜索。
考虑到iTransformer，timesnet等都是出自贵组，因此想请教一下在模型超参搜索与调参优化过程中使用tslib时有没有便捷的处理方法，后续是否会改进tslib以增加自动化功能。
谢谢

**Comment by wuhaixu2016** [comment]
您好，感谢关注。
1. tslib只是为了方便研究者实验构建的，我们尝试了一部分实验脚本，基本保证了复现效果，如果想要了解具体脚本实现的话，可以去到论文官方的github查看。
2. 我们在这个算法库中其实强调的是尽量不做超参数搜索，所以才统一采用input 96，也不打算在tslib中增加这个功能。不过超参数搜索应该有很多非常成熟的工具，比如weights & bias，您可以尝试。

**Comment by bursonz** [comment]
好的，谢谢！
