### ISSUE TITLE
Could you add MTS-Mixers into your library?

### ISSUE THREAD

**Issue by nightscorpio** [thuml/Time-Series-Library#59]
hi,

I saw MTS-Mixers: Multivariate Time Series Forecasting via Factorized Temporal and Channel Mixing was published 6 days before your TimesNet paper.
Could you add this model into your library?
Here is their code. https://github.com/plumprc/MTS-Mixers

**Comment by wuhaixu2016** [comment]
Cool, thanks for your recommandation. We will add this into out todo list.

**Comment by wuhaixu2016** [comment]
Hi, after a deep discussion, we decided to delay the development of this work. You may find its code from their authors.
