### ISSUE TITLE
Error in UEA data classification: Can't pickle local object 'data_provider.<locals>.<lambda>'

### ISSUE THREAD

**Issue by fritter-lada** [thuml/Time-Series-Library#592]
Hi!
Thanks a lot for this library!
I'm running a UEA data classification of the EthanolConcentration dataset. When starting 
`bash ./scripts/classification/TimesNet.sh`
encountered the error: 
`AttributeError: Can't pickle local object 'data_provider.<locals>.<lambda>'`
Can you tell me how to fix it?

**Comment by Musongwhk** [comment]
Hi, I think  the issue#129 may be helpful to you.
Or you can set the arg "num_workers" to 0, which means not using subprocesses in DataLoader.
