### ISSUE TITLE
Difference in FFN Implementation Between Official PatchTST Repo and Reimplementation

### ISSUE THREAD

**Issue by Ironieser** [thuml/Time-Series-Library#595]
Dear authors,

Thank you for your excellent repository.

Upon reviewing the code, I noticed a difference in the implementation of the feed-forward network (FFN) between the official PatchTST repository and the reimplementation in this repository.

In the official PatchTST repository, as shown below, the authors implement the FFN using two layers of MLP:

https://github.com/yuqinie98/PatchTST/blob/204c21efe0b39603ad6e2ca640ef5896646ab1a9/PatchTST_supervised/layers/PatchTST_backbone.py#L220-L224 

However, in this repository, the reimplementation of PatchTST uses two layers of Conv1D instead of MLPs for the FFN, as shown in the following code snippets:

https://github.com/thuml/Time-Series-Library/blob/3204cdd9b89ad470cef6e17c94f9b0925c332598/models/PatchTST.py#L52-L65

https://github.com/thuml/Time-Series-Library/blob/3204cdd9b89ad470cef6e17c94f9b0925c332598/layers/Transformer_EncDec.py#L27-L51

Could you please clarify the reason for this discrepancy? I would appreciate any insights or comments you can provide.

Thank you!

Sincerely,
Ironieser

**Comment by wuhaixu2016** [comment]
Hi, thanks for your detailed question.

In our implementation, we adopt the conv with a kernel size of 1, which is equal to nn.Linear. Please see https://pytorch.org/docs/stable/generated/torch.ao.nn.quantized.Conv1d.html#conv1d . Thus, I think these two implementations are the same.
