### ISSUE TITLE
so, how to transform inversely to compare the result?

### ISSUE THREAD

**Issue by skmanzg** [thuml/Time-Series-Library#596]
Hi, I have tried to use this library and have always failed to inversely transform the output results into original data format. Currnet code provides the result without inverse scaling and inverse transformation. Moreover, when I use the multivariate cases like ETT dataset, the only thing I can receive from the output is just one graph. I do not know where the graph belongs to the columns. Moreover, the final output shows a very complicated 4 dimensions shape when the original data shape is at best 2 dimensions. This made me more difficult to interpret the result. Of course, I have tried to transform inversely on my own only to fail and waste time. I want anyone to share the code for inversely transforming the result(output) like the original data. Otherwise, this library became only for writing papers and experiment rather than practical usage.

**Comment by wuhaixu2016** [comment]
Hi, we have provided the inverse transform code, please see here (https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_long_term_forecasting.py#L203-L206 ) and use the argument --inverse .

Also, if you want to visualize the model's predict, please rewrite the visualization code here (https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_long_term_forecasting.py#L217-L223) according to your demand.
