### ISSUE TITLE
关于数据集处理的问题

### ISSUE THREAD

**Issue by Halthward** [thuml/Time-Series-Library#598]
注意到您团队在TimesNet以及后续的iTransformer等论文中列出的数据划分
<img width="579" alt="1732583816801" src="https://github.com/user-attachments/assets/00e6ecb8-77b7-4e46-bedf-9edcfa0d6257">

将训练集验证集测试集相加后 其总长度 与您在数据集链接中提供的数据集长度并不一致 请问是您采用了某些数据清洗的预处理还是说是因为滑动窗口大小导致的该问题 如果是因为滑动窗口导致的 为何在96 192 336 720等步长下都是同样的划分长度呢
![微信图片编辑_20241126084909](https://github.com/user-attachments/assets/b90b1dea-d787-472f-bab3-c1513d63cc51)

**Comment by wuhaixu2016** [comment]
您好，请以这个算法库中的数据预处理代码为准。目前看iTransformer中的数据是正确的，timesnet中我们存在一些统计错误。

**Comment by Halthward** [comment]
但是目前仅就long-term forecast 任务中用到的数据集来看 iTransformer中和TimesNet共同用到的数据集的划分是一模一样的
此处为TimesNet的长序预测部分的数据划分
<img width="383" alt="1732589023328" src="https://github.com/user-attachments/assets/f4966eb3-6fe6-4528-b1fe-2ff967c3e9ac">
此处为iTransformer的数据划分
<img width="456" alt="1732589088095" src="https://github.com/user-attachments/assets/0528de0e-d35d-4e77-a567-4beb8c263923">

我的问题是您团队在这两篇文章之中所提出的数据划分 （以ECL的划分为例18317+2633+8261=29211）并不等于您在数据集链接中提供的electricity.csv文件的数据总条数26304
因此我想了解您是否在使用这些数据进行long-term forecast任务之前有对链接中的数据集进行数据清洗 或者是出于一些其他的原因导致了这一现象
