### ISSUE TITLE
频率的选择

### ISSUE THREAD

**Issue by wh1994-phd** [thuml/Time-Series-Library#6]
作者您好，多元的时间序列应该每单个序列都有自己的频率，从您的源代码可以看出您的主频率的选择是通过做了两次平均之后得到的。这样做会不会影响到时间序列不同周期的选择？

**Comment by wuhaixu2016** [comment]
您好，这个问题很关键，我是这么理解的
（1）目前多变量预测是首先使用一层embeding网络将变量维度C映射为深度特征的通道维度d_{model}，这个过程会使得不同变量之间的信息相互融合，因此在TimesNet中使用fft计算的已经是「融合后特征」的周期性的，这个周期性已经隐式包含了不同变量的信息。同时TimesNet中还使用了多周期性的设计，用于覆盖不同长度的周期。因此，我觉得目前的设计是可以比较好的覆盖多元时间序列不同频率的。不过，目前这种平均的设计也是trade-off performance and efficiency之后的结果，如果做更加细粒度的建模是会得到更好的结果的。
（2）最近也有很多文章探索了variate-independent的设计，例如Dlinear、PatchTST，不过他们也都是将模型在不同变量间share。总体来看，目前多元时间序列预测上，不同变量的差异性目前探索还比较初步。
