### ISSUE TITLE
ipynb文件在这是具体做什么呀

### ISSUE THREAD

**Issue by zhurong-dot** [thuml/Time-Series-Library#604]
ipynb文件在这是具体做什么呀

**Comment by wuhaixu2016** [comment]
您好，ipynb主要用于介绍TSLib中TimesNet模型的运行逻辑。

**Comment by zhurong-dot** [comment]
我还想知道个问题就是一般的预测方法都是用滑动窗口来预测，文章中的方法好像不是滑动窗口，是怎么预测的呢？
