### ISSUE TITLE
Regarding train_epochs

### ISSUE THREAD

**Issue by isCopyman** [thuml/Time-Series-Library#607]
![image](https://github.com/user-attachments/assets/bae6389d-2570-4406-bc4e-9c9f1d1db9da)
(TimesNet)
some models have very small train_epochs settings, what is the reason? To prevent the training time from getting too long, or to prevent overfitting. But why do you use such small train_epochs when you have already set up an early stop mechanism?

**Comment by wuhaixu2016** [comment]
Hi, thanks for pointing out this issue. these are typos, you can just remove them and adopt the default setting.
