### ISSUE TITLE
python package local-attention release 1.9.14 causes ModuleNotFoundError: No module named 'torch.amp'

### ISSUE THREAD

**Issue by wmr119** [thuml/Time-Series-Library#608]
i have seen the related question，so i choose change the code：from torch.cuda.amp import autocast.But it show  @autocast('cuda', enabled = False)   TypeError: __init__() got multiple values for argument 'enabled'.Could you tell me how to fix it?

**Comment by wmr119** [comment]
i find it is cause by pytorch must be cuda version

**Comment by cutepiggy123** [comment]
can you show me how to fix this
