### ISSUE TITLE
Please add instructions on how to set experiment parameters 

### ISSUE THREAD

**Issue by TheHuangs** [thuml/Time-Series-Library#609]
There are so many parameters to set in TimeXer or other model. Is there some instructions on how to set these parameters. It's hard for people in other industry to use your state-of-art work.

**Comment by wang-lucy** [comment]
We have provided the implementation details of the hyper-parameter settings in Appendix A.2 of TimeXer. Experimentally, the number of layers (e_layers), the dimension of latent space (d_model), and the dimension of the inner layer of the feed-forward network (d_ff) are key parameters that need to be selected with respect to the task.
