### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Lcq2002** [thuml/Time-Series-Library#611]
![image](https://github.com/user-attachments/assets/d2efec13-a4f7-40ac-9636-a49a8f3c6143)

**Comment by Bright-Hsu** [comment]
建议搜索网络寻找解决方案，可能是因为torch版本和CUDA不匹配造成的

**Comment by wuhaixu2016** [comment]
感谢回复 @Bright-Hsu
