### ISSUE TITLE
关于使用TimesNet预测ETTh1结果的疑问

### ISSUE THREAD

**Issue by Bright-Hsu** [thuml/Time-Series-Library#613]
您好，TS-Lib是一个非常棒的工作，让我们这些时序分析初学者能够学习到关于时序数据的相关知识并进行实践。

我在按照readme的使用介绍中进行时序预测任务，采用的命令是`bash ./scripts/long_term_forecast/ETT_script/TimesNet_ETTh1.sh`，具体内容如下：
```
export CUDA_VISIBLE_DEVICES=2

model_name=TimesNet

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_96_96 \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --d_model 16 \
  --d_ff 32 \
  --des 'Exp' \
  --itr 1 \
  --top_k 5 
```

我得到了一些测试结果，但是我对测试结果有一些疑问，想请您解答。

## 1. 实验结果文件名的含义
如下图所示，对于每一个长期预测实验，都会保存5个pdf文件，请问这些文件之间的关联是什么，文件名的数字0或者20代表着什么意思？

![image](https://github.com/user-attachments/assets/2b4e9540-f943-4b86-bbe9-a8308131269d)

## 2. 实验结果效果问题

![image](https://github.com/user-attachments/assets/87bc369e-4856-48ba-b93c-8c6b4ff282d6)

比如对于这张实验结果而言，我有以下问题：
- 图中的纵轴均为负数，与实际的OT数据不同（OT数据均大于20），这可能是因为代码中对数据进行了归一化或其他处理，请问如何得到原始数据的直观观测结果图，是需要修改什么参数或者代码呢？
- 从sh文件的参数可以看到有三个长度参数分别是`  --seq_len 96   --label_len 48   --pred_len 96 `，其中seq_len 和pred_len 好理解，分别是输入长度和预测长度，在结果中也有表现，但是label_len 是什么含义呢，它的取值会对结果有什么影响？
- 根据上面的问题，我理解输出图像应该是一整段的真实值（groudtruth），而预测值应该只占图像的后半段。可是看这个图像却并非如此，图中的预测值（黄线）为什么是一整段，而真实值（蓝线）却只有后半段，是否是输出的画图代码有问题？
- 预测效果问题（最重要的问题）：按照图中展示，可以发现后半段的预测值与真实值偏差较大，并且预测值似乎存在过拟合情况导致预测输出始终为一个稳定周期循环往复。这种效果是符合预期的吗？

## 3. 运行脚本参数设置问题

按照run.py的注释说明，上面的features 参数设置为M，应当是一个多变量预测多变量的问题，但是按照实验的输出来看，似乎最后只输出了OT的预测，并没有涉及到其他变量的预测，因为下面可以看到  Target:  OT ，但实际Target不应该为所有变量吗？
下面是实验的关键部分命令行输出：
```
Basic Config
  Task Name:          long_term_forecast  Is Training:        1                   
  Model ID:           ETTh1_96_96        Model:              TimesNet            

Data Loader
  Data:               ETTh1               Root Path:          ./dataset/ETT-small/
  Data Path:          ETTh1.csv           Features:           M                   
  Target:             OT                  Freq:               h                   
  Checkpoints:        ./checkpoints/      

Forecasting Task
  Seq Len:            96                  Label Len:          48                  
  Pred Len:           96                 Seasonal Patterns:  Monthly             
  Inverse:            0                 
```

以及这里的Freq和Seasonal Patterns命令行中并未设置，这些参数的取值是取决于数据还是取决于代码的默认值？

一些疑问请您解答，非常感谢！

**Comment by wuhaixu2016** [comment]
您好，感谢使用，不过这些问题大部分都比较基础，如果您可以看一下这几个代码文件的话会很清楚。

https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py
https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_long_term_forecasting.py

具体来讲，可视化是间隔20可视化多变量之中的一个。https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_long_term_forecasting.py#L225

目前模型的输出都是经过z-score归一化之后的数值，您可以通过--inverse进行反归一化，请见：https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_long_term_forecasting.py#L220

**Comment by Vector-Cross** [comment]
1. 坐标是因为有做标准化
2. label_len是seq_len和pred_len 中间的那个，分别令 seq_len=A， label_len=B，pred_len=C，任务是用A跳过B预测C。（我瞎说的，代码忘了）
3. 他画图label标反了，我一年前发现了，没想到到现在还没修复，总之画图有个bug
4. 没学习好，建议调整模型
