### ISSUE TITLE
还有个小问题M不应该是多个变量预测多个吗，MS才是多个变量预测一个，文章是针对于一个变量去预测，为啥还要用M

### ISSUE THREAD

**Issue by zhurong-dot** [thuml/Time-Series-Library#624]
parser.add_argument('--features', type=str, default='M',
                        help='forecasting task, options:[M, S, MS]; M:multivariate predict multivariate, S:univariate predict univariate, MS:multivariate predict univariate')

**Comment by wuhaixu2016** [comment]
您好，我个人认为MS setting是比较正确的且贴近实际的，即利用尽可能多的信息辅助目标变量的预测，这个想法也体现在我们最近的两篇论文中，比如
- TimeXer: https://arxiv.org/abs/2402.19072
- MetaTST: https://arxiv.org/abs/2410.03806

但是与MS相比，M还有一些好处，比如
（1）当有多个目标变量时，M更快，如果使用MS则需要依次把每个变量都设定为目标变量，会增加M倍的开销。典型的应用是交通/多个股票预测，需要比较快速的决策。
（2）单纯的MS setting可能无法建模完备的变量关系，比如变量A与变量B之间的关系存在相互影响，在利用AB预测A的过程中，A的预测结果也会改变B对A的影响程度。一个典型的过程还是金融系统，当对股票A做出预测时，股票B可能会收到A预测的影响，在这个时候，如果固定AB去预测A，则失去了对A反馈至B的通路。
