### ISSUE TITLE
关于测试阶段的一些疑惑

### ISSUE THREAD

**Issue by SteelHu** [thuml/Time-Series-Library#628]
您好，对于异常检测任务，在测试阶段我有几点疑惑，希望能不吝赐教。
1. 在测试阶段的test_loader中使用了划窗技术，因此test_energy的数量是所有划窗之和，这是远远大于测试集的数量，在这个基础上计算出来的结果和直接在测试集上计算得到的结果是有差异的，请问这里你们是如何考虑的呢？
2. 在计算阈值时，使用train_energy和test_energy拼接，请问这里为什么要使用train_energy呢？
3. 测试阶段能否可以使用train_energy来确定阈值，然后在不使用划窗的测试集上进行评估呢？这样的评估是否更为合理？

**Comment by wuhaixu2016** [comment]
您好，感谢提问
1. 我个人直观觉得是否使用滑窗不会影响太多，但是并没有做实验验证。使用滑窗的好处是，每一个点都有可能出现在窗口的各个位置，如果使用不overlap的滑窗，则一些点只出现在窗口的某一些位置。虽然Transformer在理论上对于每个不同位置的点等价，但是如果使用了pos embedding会造成出现在窗口内不同位置的点存在差异。
2. 使用train是为了尽可能多的扩充计算threshold的数据，得到更加可靠的结果。
3. 可以，这个看您的应用场景，如果是对事故数据进行回顾分析，现在的方法是可行的，但是如果做streaming deploy，可以只用train energy.

**Comment by SteelHu** [comment]
好的，感谢您的解答

**Comment by a1473838623** [comment]
虽然这个问题close了，我想问下，val_energy是不是也应该考虑进去。
