### ISSUE TITLE
我设置   "--features", "MS"后,我想要反归一化后的PDF，报错我怎么改

### ISSUE THREAD

**Issue by zhurong-dot** [thuml/Time-Series-Library#629]
>>>>>>>testing : long_term_forecast_ETTh1_96_96_iTransformer_ETTh1_ftMS_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_expand2_dc4_fc3_ebtimeF_dtTrue_Exp_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 2785
Traceback (most recent call last):
  File "run.py", line 194, in <module>
    exp.test(setting)
  File "G:\Time-Series-Library-main\Time-Series-Library-main\exp\exp_long_term_forecasting.py", line 207, in test
    outputs = test_data.inverse_transform(outputs.reshape(shape[0] * shape[1], -1)).reshape(shape)
  File "G:\Time-Series-Library-main\Time-Series-Library-main\data_provider\data_loader.py", line 109, in inverse_transform
    return self.scaler.inverse_transform(data)
  File "F:\shuoAPP\anaconda\envs\QHZS\lib\site-packages\sklearn\preprocessing\_data.py", line 1052, in inverse_transform
    X *= self.scale_
ValueError: operands could not be broadcast together with shapes (3072,49) (7,) (3072,49)

**Comment by wuhaixu2016** [comment]
您好，我们这边实验没有问题，可以使用这个脚本。

model_name=iTransformer

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_96_96 \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  --inverse

**Comment by zhurong-dot** [comment]
非常感谢您的耐心回复，您给上述脚本是没问题的，我的想法是我想设置 "--features", "MS"去预测，然后可视化PDF，会报错，怎么去解决这个问题

**Comment by zhurong-dot** [comment]
补充一下师兄，还有inverse取为True  设置 "--features", "MS"去预测，然后可视化PDF，会报错，怎么去解决这个问题

**Comment by wuhaixu2016** [comment]
您好，感谢反馈，我们在最新的commit中已经解决了。具体改动请见：https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_long_term_forecasting.py#L205-L206

这个bug是因为想适配TimeXer但是没有注意对于其他模型的兼容，非常抱歉。
