### ISSUE TITLE
Segmentation fault when running classification exp

### ISSUE THREAD

**Issue by xuehaouwa** [thuml/Time-Series-Library#63]
Hi,

This Segmentation fault issue appeared every time I run a classification setting (no matter which network is used). Any ideas? It happens when the first epoch is finished.

![image](https://user-images.githubusercontent.com/26236658/229959550-bf61dd78-4486-43a8-b47e-8954467d0ef2.png)

**Comment by ZDandsomSP** [comment]
Hello!
We retried some of our network to make a confirm,and it shows no Segmentation fault at present.Perhaps the following methods can help you:
1.Check if the library version in your environment meets the requirements of requirements.txt
2.We noticed that you used a self-made dataset.You can check if your dataset format is incorrect and if it meets the parameters you provided for the network.
3.If the above methods cannot solve your problem, you can consider replacing the GPU device you are using,which has more graphics memory for example.
