### ISSUE TITLE
ETTh1测试集为2785，按每隔20步预测，不应该输出0.20.40.60.80....2780吗？怎么就到80

### ISSUE THREAD

**Issue by zhurong-dot** [thuml/Time-Series-Library#630]
![image](https://github.com/user-attachments/assets/f2421fc9-67d2-48ae-82cb-edf1d0a2d8cb)

**Comment by wuhaixu2016** [comment]
您好，这些问题都可以通过阅读代码了解，请见可视化代码：https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_long_term_forecasting.py#L218-L225
测试时batch size大于1
