### ISSUE TITLE
TimeXer如何判断其利用协变量的效果？

### ISSUE THREAD

**Issue by liujian123223** [thuml/Time-Series-Library#631]
您好，我对你们的工作很感兴趣。我在使用TimeXer进行实验时，想验证论文中在协变量缺失情况下的预测效果。因此我将我的数据集的协变量部分按照不同比例设置缺失值，并用论文中同样的方式使用0来代替缺失的部分。但我发现随着协变量缺失比例的升高（目标变量完整不变）我的预测结果反而整体更好了。当我将所有的协变量全部设置为0的时候效果达到最好。你能指出我的错误在哪吗？我需要如何正确的设置才能完成这个实验？

**Comment by wang-lucy** [comment]
您好，相关问题已在TimeXer仓库中进行了回答：[https://github.com/thuml/TimeXer/issues/16](url)
