### ISSUE TITLE
Fix Typo in UEAloader load_all Function Annotation (csv -> ts)

### ISSUE THREAD

**Issue by HUANG-Kaibo** [thuml/Time-Series-Library#632]
<img width="887" alt="issue" src="https://github.com/user-attachments/assets/e8dafda3-e13f-4f08-bc46-5e1911364a83" />
Hello, there is a clerical error here, in the UEAloader of data_loader.py, the load_all function annotation should be ts file, but the clerical error is written as csv file

**Comment by wuhaixu2016** [comment]
Thanks for pointing out this. We have fixed this bug in the lastest commit.
