### ISSUE TITLE
这些异常检测模型泛化性怎么样？

### ISSUE THREAD

**Issue by puyiwen** [thuml/Time-Series-Library#634]
大佬您好，我是这方面的小白，我想知道这些模型的异常检测泛化性怎么样？在某一个数据上训练，然后在别的数据集上测试效果好像掉了。。这是模型问题吗还是说这个异常检测任务泛化性就不太行？

**Comment by wuhaixu2016** [comment]
您好，目前时序的OOD泛化问题还没有特别多研究，一般都是利用历史数据训练，未来数据测试，这样只存在temporal shift，不存在domain gap。所以您提到的“在别的数据集上测试的效果“我觉得无法保证。
