### ISSUE TITLE
在自己单变量数据集上效果很差

### ISSUE THREAD

**Issue by puyiwen** [thuml/Time-Series-Library#636]
大佬您好，我有一个数据集，2000多条，数据形式是这样的，想要做异常值的异常检测。
![image](https://github.com/user-attachments/assets/193553a2-122b-46fc-bbdf-2ba0c26b7b70)
复制的是SMAP的加载数据方法，首先将我的数据给做了绝对值，然后作为原始数据进行加载。train.npy的shape是(2063,1)，test_label.npy的shape是(761,)。
训练脚本为
`export CUDA_VISIBLE_DEVICES=0

python -u run.py \
  --task_name anomaly_detection \
  --is_training 1 \
  --root_path /data2/flow_x \
  --model_id Flow \
  --model TimesNet \
  --data Flow \
  --features S \
  --seq_len 100 \
  --pred_len 0 \
  --d_model 16 \
  --d_ff 16 \
  --e_layers 2 \
  --enc_in 1 \
  --c_out 1 \
  --top_k 3 \
  --anomaly_ratio 1 \
  --batch_size 16 \
  --train_epochs 10`

结果很差，`Acc:0.0469，Precision： 0.8140, Recall：0.0340, F-score: 0.0653`。
我目前不清楚为什么会这样，可能是`seq_len`或者其他参数设置的不对？您能帮助我一下吗？非常感谢您

**Comment by wuhaixu2016** [comment]
您好，我感觉您可以试试调大一下anomaly ratio。因为明显这里的recall比较低，说明其实很多异常点没有捕捉到（但是捕捉到的异常准确率比较高）。
另外还需要您确认一下label的格式，是数值异常的才会被识别为异常吗？因为异常的种类有很多中，需要针对模型预测的结果做case study，您可以详细看看case再做判断。

**Comment by puyiwen** [comment]
> 您好，我感觉您可以试试调大一下anomaly ratio。因为明显这里的recall比较低，说明其实很多异常点没有捕捉到（但是捕捉到的异常准确率比较高）。 另外还需要您确认一下label的格式，是数值异常的才会被识别为异常吗？因为异常的种类有很多中，需要针对模型预测的结果做case study，您可以详细看看case再做判断。

非常感谢您的回答，我把anomaly ratio调大了，结果正常了。我还有个问题，这些能处理变长序列的异常检测吗？就是类似5,10,15这种变长序列，如果能的话，我需要修改哪些参数？
