### ISSUE TITLE
How to make a forecast for data of size seq_len?

### ISSUE THREAD

**Issue by pskucherov** [thuml/Time-Series-Library#637]
Hi!
I want to pass data that I want to forecast in production, limited by the seq_len dimension. So basically the latest available data to get a forecast, without the reference y value.

I removed the borders so that 100% of the data passed to the model is loaded. Here: https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L248-L255

But I have data size equal to seq_len, and the error occurs with different dimensions in the model. The model expects seq_len + label_len.
1. https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L92-L103
2. https://github.com/thuml/Time-Series-Library/blob/main/data_provider/data_loader.py#L290-L301
3. https://github.com/thuml/Time-Series-Library/blob/main/exp/exp_long_term_forecasting.py#L45-L60

I'm thinking of padding the data with zeros and date stamps. How do you like this solution or is there a better one?

**Comment by wuhaixu2016** [comment]
Hi, I think you need an inference function. You may find this code helpful: https://github.com/thuml/Autoformer/blob/main/exp/exp_main.py#L241
