### ISSUE TITLE
Anomaly detection on MSL

### ISSUE THREAD

**Issue by cccuuu6666** [thuml/Time-Series-Library#66]
I run anomaly detection on MSL many times use the provided scripts (epoch is 10), but the  F-score is always 0.8066. But the in paper is 0.8515 ?

**Comment by wuhaixu2016** [comment]
Hi, have you use the pytorch with 1.7.1 (https://github.com/thuml/Time-Series-Library/issues/12)

**Comment by secretfish2000** [comment]
torch==1.7.1，python版本3.8 ,cuda版本11.0
epoch=1:
anomaly_detection_MSL_TimesNet_MSL_ftM_sl100_ll48_pl0_dm8_nh8_el1_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_test_0  
Accuracy : 0.9647, Precision : 0.8954, Recall : 0.7536, F-score : 0.8184 
epoch=10:
anomaly_detection_MSL_TimesNet_MSL_ftM_sl100_ll48_pl0_dm8_nh8_el1_dl1_df16_expand2_dc4_fc1_ebtimeF_dtTrue_test_0  
Accuracy : 0.9627, Precision : 0.8874, Recall : 0.7401, F-score : 0.8071 
也是跑不出论文里的结果，请问作者是哪里出问题了
