### ISSUE TITLE
Running on CPU instead of GPU

### ISSUE THREAD

**Issue by tiago-lam** [thuml/Time-Series-Library#68]
Hello,

Thanks for making this work publicly available. 

I'm currently running `./scripts/long_term_forecast/ETT_script/TimesNet_ETTh1.sh` on Google Colab. But it is always running on CPU, instead of GPU. I'm wondering if there's something in the code I should set as True in order to make it run on GPU.

I set the default of the functions below as True in the `run.py` file:
```
parser.add_argument('--use_gpu', type=bool, default=True, help='use gpu')
parser.add_argument('--use_multi_gpu', action='store_true', help='use multiple gpus', default=True)
```
Thank you!

**Comment by ZDandsomSP** [comment]
Hello!
We have retested our code and executing `./scripts/long_term_forecast/ETT_script/TimesNet_ETTh1.s`h will not cause any issues with CPU operation. You can consider the following solutions:
1. Check the `export CUDA_VISIBLE_DEVICES=xxx` statement in the script, which selects your GPU number
2. Check if your GPU has sufficient graphics memory
