### ISSUE TITLE
请问如何预测未在batch_x内出现的单变量？

### ISSUE THREAD

**Issue by Nonikka** [thuml/Time-Series-Library#69]
假设输入中的序列中只有V1,V2,V3，输入不包含OT，预测下一步的OT
比如输入油门、加速度的时间序列，输出预测的当前时速(OT)
请问如何实现？我使用MS参数后依然会把OT作为输入。

Thanks.

**Comment by wuhaixu2016** [comment]
您好，这个是一个回归问题，不需要预测，最简单的做法是重写dataloader。
不过您想基于目前的代码来写的话，可以在exp文件中遮住OT对应的列。
