### ISSUE TITLE
周期选择和变2D时的length设定

### ISSUE THREAD

**Issue by water-wbq** [thuml/Time-Series-Library#7]
作者您好，非常感谢您做的扎实、具有启发性的工作。
我在学习您文章和代码时，遇到了如下问题，希望您能帮忙解惑：
Q1: 在FFT_for_Period中，有一步 frequency_list[0] = 0，请问这边赋值为0的目的/好处是什么？
Q2: 在1D变2D时，涉及到了 length = (((self.seq_len + self.pred_len) // period) + 1) * period，我不是很明白这边为什么要把self.pred_len也加入进去？
期待回复，谢谢！

**Comment by wuhaixu2016** [comment]
您好，感谢关注！
Q1: Freq[0]具有一些特殊含义，表示的是整个信号的能量值。所以相比于周期性，它更多地代表的是信号整体的特征，所以我们把它置0来避免选到这个频率。如果序列没有周期性的话，只要选到Freq[1]就可以了。
Q2: 对于预测任务来说，TimesNet的pipeline是：在embedding之后先将序列长度扩充为self.seq_len + self.pred_len，然后再不断refine预测结果。所以在中间层的TimesBlock其实在处理预测的中间结果（其长度为self.seq_len + self.pred_len）。但是对于其他任务，self.pred_len=0，所以加和不加self.pred_len没有影响。

**Comment by water-wbq** [comment]
非常感谢！我的疑问已被解决。
我这边就把这个issue close了
