### ISSUE TITLE
FFT相关

### ISSUE THREAD

**Issue by luoxia-wen** [thuml/Time-Series-Library#70]
在代码中，针对时序预测部分
先对原始数据进行了转换，从seq_len 变为 seq_len + pred_len，然后传入timesblock进行FFT运算，FFT提取的周期并不是原始数据的周期，请问这样做具有合理性吗？

**Comment by wuhaixu2016** [comment]
Hi, you may find this useful (https://github.com/thuml/Time-Series-Library/issues/38).
