### ISSUE TITLE
能否进行单变量预测

### ISSUE THREAD

**Issue by fiksdano** [thuml/Time-Series-Library#72]
作者你好，我想请问一下你所提供的多种模型里面，假设数据只有1000多个，能否利用你们的模型来进行预测呢？我自己有尝试跑了之后好像经常报错说是长度不够。不知道这些模型对于少量数据集来说是否有效呢？同时假设我只有一个变量，那我是否能根据这些变量预测到后面的数值呢？期待你的回复。

**Comment by wuhaixu2016** [comment]
您好，需要您减小输入时刻和输出时刻的长度，即调一下seq_len、label_len和pred_len这三个参数
