### ISSUE TITLE
ImportError：cannot import name 'pack' from 'einops'

### ISSUE THREAD

**Issue by LY-must-win** [thuml/Time-Series-Library#73]
For the einops library, the versions of the Python library are installed according to the requirements file, but when running run. py, errors such as those in the title were prompted. My Python version is 3.10, I'm not sure if it's related to the Python version,I look forward to hearing from you very much.

**Comment by LY-must-win** [comment]
![image](https://user-images.githubusercontent.com/103368413/232020436-3a954b52-3a44-4ba2-8d4d-822ac9dd7562.png)
![image](https://user-images.githubusercontent.com/103368413/232020445-8ea2c3d1-9f05-48fc-b17a-264699c2ee4a.png)

**Comment by wuhaixu2016** [comment]
Hi, maybe you can try python 3.8

**Comment by LY-must-win** [comment]
Okay, I'll give it a try.Thank you!

**Comment by blacksnail789521** [comment]
It appears the issue is with `local_attention`. My suggested solution is to update `einops` to the latest version (0.6.1).
