### ISSUE TITLE
是否尝试过单变量预测的效果

### ISSUE THREAD

**Issue by fiksdano** [thuml/Time-Series-Library#74]
作者你好，我想请问一下，我的数据集只有单变量，那我能否用你所提供的timenet模型进行预测呢？
同时代码里面的data_loader文件是否需要修改，还是修改scripts里文件的数据呢？

**Comment by fiksdano** [comment]
作者大大，我想再请教一下，我现在在用你所提供短期预测里面的m4数据集进行预测，想把数据集换成我自己的，但我的数据集只有单变量，是否能够直接更改m4数据集呢？还有一个疑问点，短期和长期预测，步长你们是如何定义的呢？

**Comment by ZDandsomSP** [comment]
你好！
如果您的数据集只有单变量，您需要在script里面根据您的需求手动修改enc_in、dec_in、c_out的值。同时，您也可以看一下data_loader.py、data_factory.py等文件的实现，如果您的数据集大小比较特殊，或者您对有对数据集特定的使用需求，可能需要您自行实现相应的类。
