### ISSUE TITLE
About the excerpts of the paper

### ISSUE THREAD

**Issue by LY-must-win** [thuml/Time-Series-Library#77]
![image](https://user-images.githubusercontent.com/103368413/232208592-58e162bd-35b8-4e28-b5cc-92ff009ccfd1.png)
**Regarding the  imputation section for data in the paper**, I saw that  imputation is done by randomly masking time series proportionally. I would like to know if it is possible to process it for personal datasets, where there is truly missing data? I tried it and it didn't seem right.The loss value is null in the program.
![image](https://user-images.githubusercontent.com/103368413/232208854-a3dd5f87-c460-4ab3-8b67-d8016d79a199.png)
![image](https://user-images.githubusercontent.com/103368413/232209132-70e06252-c4ad-4941-8fe8-4b093fc7b52d.png)
Should I set  value from the following imputation task to zero?

**Comment by wuhaixu2016** [comment]
Hi, you can set the missing time points with zero.

**Comment by LY-must-win** [comment]
Okay, I will give it a try，thank you for your answer



---Original---
From: ***@***.***&gt;
Date: Thu, Apr 20, 2023 20:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [thuml/Time-Series-Library] About the excerpts of the paper(Issue #77)




 
Hi, you can set the missing time points with zero.

**Comment by wasay464** [comment]
@LY-must-win Did your program work?
