### ISSUE TITLE
Error when loading custom dataset

### ISSUE THREAD

**Issue by SeungHunHan11** [thuml/Time-Series-Library#78]
Appreciate all of your fine work done :)

I have a tiny suggesion regarding implementation of custom dataset.

```
test 773
test shape: (773, 1, 96, 1) (773, 1, 96, 1)
test shape: (773, 96, 1) (773, 96, 1)
Traceback (most recent call last):
  File "run.py", line 149, in <module>
    exp.test(setting)
  File "/workspace/Time-Series-Library/exp/exp_long_term_forecasting.py", line 245, in test
    register_metric(mae, mse, self.args)
  File "/workspace/Time-Series-Library/utils/tools.py", line 147, in register_metric
    target_x = seq_len_index + dataset_name_dict[dataset_name] * 20
KeyError: 'KACO1.csv'

```
Error message above pops up when I try to implement custom dataset.

`def register_metric(mae, mse, configs):
    seq_len = configs.seq_len
    pred_len = configs.pred_len
    model = configs.model
    dataset_name = configs.data_path
    pred_len_dict = {
        96: 0,
        192: 1,
        336: 2,
        720: 3,
    }
    dataset_name_dict = {
        "ETTh1.csv": 0,
        "ETTh2.csv": 1,
        "ETTm1.csv": 2,
        "ETTm2.csv": 3,
        "electricity.csv": 4,
        "traffic.csv": 5,
        "weather.csv": 6,
        "exchange_rate.csv": 7,
        "national_illness.csv": 8,
    }`

Apparently, register_metric function in [Tools.py](https://github.com/thuml/Time-Series-Library/blob/f7302ff30f49b11aaf7f1ba951e2c78617e0ed96/utils/tools.py#L130-L138) does not automatically include datasetname into the defined dictionary. Perhaps custom dataset name should be added to the dictionary automatically?

Thanks.

**Comment by yunchuan18** [comment]
data_provider里的文件看看，tool.py和run.py 也看看 你少添加自己数据集信息往字典里了。仔细检查一下

**Comment by ZDandsomSP** [comment]
Hello！
Thank you for your feedback. We will remove this unnecessary function in the next commit.
