### ISSUE TITLE
Error when using short_term_forecast

### ISSUE THREAD

**Issue by thornbsj** [thuml/Time-Series-Library#79]
Hi Team,

When I used my custom dataset, the script raised an error:
![image](https://user-images.githubusercontent.com/57366161/232728181-309679eb-cc0e-403d-895e-4ecf0f566d3b.png)
I found that the variable frequency_map may not be inited when I don't use M4 dataset.

Best Regards

**Comment by htg17** [comment]
Hello. If you are using dataset other than M4 dataset, please use exp_long_term_forecasting.py by setting 
`--task_name long_term_forecast`
in the scripts.
