### ISSUE TITLE
ImportError: cannot import name 'load_data' from 'sktime.utils' (D:\Anaconda\envs\dongshouxue\lib\site-packages\sktime\utils\__init__.py)

### ISSUE THREAD

**Issue by Jack-Dawson-Yao** [thuml/Time-Series-Library#8]
这个bug不知道大家有没有遇到

**Comment by wuhaixu2016** [comment]
您好，可以检查一下sktime的版本，0.4.1是可以的

**Comment by Jack-Dawson-Yao** [comment]
好的，问题已解决~。




姚习章
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thuml/Time-Series-Library"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月20日(星期一) 晚上10:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thuml/Time-Series-Library] ImportError: cannot import name 'load_data' from 'sktime.utils' (D:\Anaconda\envs\dongshouxue\lib\site-packages\sktime\utils\__init__.py) (Issue #8)





 
您好，可以检查一下sktime的版本，0.4.1是可以的
