### ISSUE TITLE
How to specify target cols in M task with custom data?

### ISSUE THREAD

**Issue by jh-qibebt** [thuml/Time-Series-Library#81]
Hello, I want to set several cols of inputs as my target cols, How should I set param "target" in train.sh?
besides, when I remove "target" in train sh, it will got an error because of code below:

https://github.com/thuml/Time-Series-Library/blob/b9c6f4c486b339eca185f52da1b913eb8ef48d80/data_provider/data_loader.py#L233-L235

**Comment by wuhaixu2016** [comment]
Hi, if you use the 'M' setting, all the cols will be the targets.
The OT col will only be meanfuling when you adopt the 'S' and 'MS' setting.
