### ISSUE TITLE
Is the exp_short_term_forecasting just for M4 dataset?

### ISSUE THREAD

**Issue by crest55** [thuml/Time-Series-Library#83]
In the 'train' method of the 'Exp_Short_Term_Forecast' class, there is a function call that requires a 'self.args.frequency_map' argument.

```
loss_value = criterion(batch_x, self.args.frequency_map, outputs, batch_y, batch_y_mark)
```

However, the 'frequency_map' is only defined for the M4 dataset.

```
    def _build_model(self):
        if self.args.data == 'm4':
            self.args.pred_len = M4Meta.horizons_map[self.args.seasonal_patterns]  # Up to M4 config
            self.args.seq_len = 2 * self.args.pred_len  # input_len = 2*pred_len
            self.args.label_len = self.args.pred_len
            self.args.frequency_map = M4Meta.frequency_map[self.args.seasonal_patterns]
        model = self.model_dict[self.args.model].Model(self.args).float()

        if self.args.use_multi_gpu and self.args.use_gpu:
            model = nn.DataParallel(model, device_ids=self.args.device_ids)
        return 
```
So I receive an error message if I use my custom data:

```
AttributeError: 'Namespace' object has no attribute 'frequency_map'
```

And there is also no implementation of the 'last_insample_window' method in the 'Custom_Data' class, which will be used in the 'vali' method in the 'Exp_Short_Term_Forecast' class.

```
    def vali(self, train_loader, vali_loader, criterion):
        x, _ = train_loader.dataset.last_insample_window()
        ...
```

what should I do if I want use my custom data to do short term forecasting task?

**Comment by wuhaixu2016** [comment]
Hi, short-term is just for M4 dataset. If you want to use custom dataset, you can adopt the long-term forecasting code base and set the pred_len as you want.
