### ISSUE TITLE
关于变量与变量之间的关系

### ISSUE THREAD

**Issue by SomeOneIsWLL** [thuml/Time-Series-Library#85]
你好，想请教一个问题，TimeNet考虑到变量与变量之间的关系了么，如果有考虑到，它是怎么做到么？可以帮我解答一下吗？十分感谢。

**Comment by wuhaixu2016** [comment]
您好，TimesNet没有做变量之间的关系，主要关注的是时间上的建模。

目前仅仅是通过MLP做一些变量之间信息的聚合

**Comment by zixuanxuanxuanxuan** [comment]
您好，那是怎么通过MLP进行信息聚合的呢？
