### ISSUE TITLE
Why is the result of my experiment so bad?

### ISSUE THREAD

**Issue by darry00** [thuml/Time-Series-Library#86]
According to the configuration of TimesNet in this paper, the performance of the ETTh1 dataset is very poor. I don't know why. I hope the author can solve the confusion. I'm much obliged.
This is the result:
long_term_forecast_ETTh1_96_192_TimesNet_ETTh1_ftM_sl96_ll48_pl192_dm32_nh8_el2_dl1_df512_fc3_ebtimeF_dtTrue_'Exp'_0  
mse:nan, mae:nan, corr:nan, nse:nan

**Comment by wuhaixu2016** [comment]
Hi, we have provided the corresponding script in this repo. Please see: https://github.com/thuml/Time-Series-Library/blob/main/scripts/long_term_forecast/ETT_script/TimesNet_ETTh1.sh

The difference lies in the setting of d_ff. We set d_ff as 32 here.

**Comment by darry00** [comment]
Thanks for your reply. I'll change the parameter settings to run again.




Darry00
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thuml/Time-Series-Library"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月26日(星期三) 下午5:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thuml/Time-Series-Library] Why is the result of my experiment so bad? (Issue #86)





 
Hi, we have provided the corresponding script in this repo. Please see: https://github.com/thuml/Time-Series-Library/blob/main/scripts/long_term_forecast/ETT_script/TimesNet_ETTh1.sh
 
The difference lies in the setting of d_ff. We set d_ff as 32 here.
