### ISSUE TITLE
CUDA device Error

### ISSUE THREAD

**Issue by minqukanq** [thuml/Time-Series-Library#90]
I have two GPUs, and I allocated only one of them using the '--gpu 1' option for training purposes.
However, when I attempted to load the trained model using torch.load, I encountered an error. 

https://github.com/thuml/Time-Series-Library/blob/6148d13ac519ca95934573f840a85823d831171d/exp/exp_long_term_forecasting.py#L174
```
raise RuntimeError('Attempting to deserialize object on CUDA device '
RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1.
Please use torch.load with map_location to map your storages to an existing device.
```
I would greatly appreciate your assistance in this matter.

**Comment by minqukanq** [comment]
Through map_location, it seems that you can apply the method of loading to cpu and then sending to gpu.

**Comment by wuhaixu2016** [comment]
Hi, you can set --gpu as 0. If you want to run the code on a specific device, you can use export CUDA_VISIBLE_DEVICES=0.

**Comment by lafans** [comment]
你好，请问问题解决了吗，我也想指定其它设备

**Comment by minqukanq** [comment]
Not resolved. I don't understand why this issue was closed.

**Comment by luobizheng** [comment]
Not resolved. I don't understand why this issue was closed？？？？？？
