### ISSUE TITLE
About TimesBlocks

### ISSUE THREAD

**Issue by ZHE0725** [thuml/Time-Series-Library#91]
我想将TimesNet中的TimesBlocks模块替换为ResNet，请问我可以怎样进行操作呢？

**Comment by wuhaixu2016** [comment]
您好，如果您想使用1D ResNet可以把TimesBlock直接换成1D ResNet；如果您想使用2D ResNet，可以把https://github.com/thuml/Time-Series-Library/blob/main/layers/Conv_Blocks.py 替换掉

**Comment by ZHE0725** [comment]
感谢。 使用1D ResNet的话那便失去了TimesNet 1D转为2D的功能了，我理解的对吗？
