### ISSUE TITLE
Normalization from Non-stationary Transformer

### ISSUE THREAD

**Issue by LanZhenFeng** [thuml/Time-Series-Library#92]
Can you tell me the reason why a small number of models in the models package implement Normalization from Non-stationary Transformer, while most of them do not? I thought the code existed in the official implementation of those models, but it doesn't.

**Comment by wuhaixu2016** [comment]
Hi, the Normalization and De-normalization framework in Non-stationary Transformer is a general design. If you want, you can add it to all the models.
