### ISSUE TITLE
There are some problems in running classification.py

### ISSUE THREAD

**Issue by Pike12** [thuml/Time-Series-Library#93]
Hi,
    thanks for your great work.I want to use Timesnet for the classification of the timing signal, when running your model (is according to your use of the data and the steps and also corrected some Timesnet. Sh mistakes like you), running bash. / scripts/classification/Timesnet. Sh code, In data_provider/uea.py, X = torch.zeros((batch_size, max_len, features[0].shape[-1])) TypeError: zeros(): argument 'size' must be tuple of ints, but found element of type function at pos 2. I can't understand why there are functions when the three arguments are numbers. I would appreciate it if you could help me out in your spare time.

**Comment by Pike12** [comment]
![image](https://user-images.githubusercontent.com/88581919/236979517-79c0dfe3-2809-4a2f-8d56-8151431cf832.png)

**Comment by wuhaixu2016** [comment]
Hi, sorry for the delayed reply and thanks for your usage.

In time series classification task, the lengths of different series can be different from each other. 
（1）We need to set the max temporal length of each time series (i.e. max_len arguement).
（2）For each input series, we need to fill the shorter series into max_len temporal size, namely the inputs with shape (batch_size, max_len, variates)

Hope this is helpful to you.
