### ISSUE TITLE
About other replace model

### ISSUE THREAD

**Issue by ZHE0725** [thuml/Time-Series-Library#95]
请问，在long_term_forecast上，如果我将Inception_Block_V1替换为2D-Resnet，那Resnet最后的输出结果需要再次聚合吗？还是直接输出预测结果？

**Comment by wuhaixu2016** [comment]
您好，感谢关注！
需要再次聚合，在代码实现上您只需要更新Inception_Block_V1函数即可，聚合的操作已经在TimesNet中完成了。
