### ISSUE TITLE
Advise

### ISSUE THREAD

**Issue by dustingan** [thuml/Time-Series-Library#96]
Great Job, but could you add more detailed example for tutorial?

**Comment by wuhaixu2016** [comment]
Hi, thanks for the great advise.
We will add this to the todo list.

**Comment by TDL77** [comment]
especially notebooks with examples

**Comment by wuhaixu2016** [comment]
Hi, you may find this helpful: https://github.com/thuml/Time-Series-Library/blob/main/tutorial/TimesNet_tutorial.ipynb
