### ISSUE TITLE
data_provider报错

### ISSUE THREAD

**Issue by ShiinoMashiro** [thuml/Time-Series-Library#97]
作者你好，我在运行分类任务时，出现了这样的问题
AttributeError: Can't pickle local object 'data_provider.<locals>.<lambda>'
请问该怎么解决呢？
![屏幕截图 2023-05-15 181511](https://github.com/thuml/Time-Series-Library/assets/64900339/ef78f253-a5c5-4dc4-a04a-623ef1124a81)

**Comment by wuhaixu2016** [comment]
您好，我们的实验都在linux环境下，这个报错可能是因为window系统，您可以尝试将num_workers设置为0进行尝试。

**Comment by BOTAK0803** [comment]
我的系统是MacOS，确实将num_workers设置成为0就ok了 感谢作者
