### ISSUE TITLE
About replace 

### ISSUE THREAD

**Issue by ZHE0725** [thuml/Time-Series-Library#99]
您好，请问在长时间序列预测问题的场景下，如果我将Inception_Block_V1替换为2D-Resnet，（原2D-Resnet模型数据的通道数不断增大，图片的H和W不断缩小为1，如[16, 32, 48, 48] -> [16, 192, 1, 1] ），那在该模型替换中，应如何设置Resnet内的数据通道数和H、W的变化呢？如果最后的H、W变为1就会报错，是需要保持数据维度一直不变吗？求解答

**Comment by wuhaixu2016** [comment]
您好，感谢细致实验，因为预测是一个细粒度生成任务，所以在使用2D-ResNet的时候不应该进行HW的变换。

**Comment by zhizhuaa** [comment]
TimesNet的作者您好！您的意思是使用任何vision backbone都不应该进行HW的变换吗？
